# Generated by Django 5.2.17 on 2026-08-28 11:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0005_opening_balance_control_intake'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetAuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_id', models.PositiveBigIntegerField(db_index=True)),
                ('department_label', models.CharField(max_length=160)),
                ('target_type', models.CharField(max_length=40)),
                ('target_id', models.CharField(max_length=64)),
                ('action', models.CharField(max_length=60)),
                ('actor_id', models.PositiveBigIntegerField()),
                ('actor_label', models.CharField(max_length=160)),
                ('reason', models.TextField(blank=True)),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='BudgetCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_id', models.PositiveBigIntegerField(db_index=True)),
                ('department_label', models.CharField(max_length=160)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=180)),
                ('authority_reference', models.CharField(max_length=180)),
                ('instructions', models.TextField()),
                ('proposal_opens_on', models.DateField()),
                ('proposal_due_on', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('for_review', 'For review'), ('published', 'Published'), ('returned', 'Returned'), ('closed', 'Closed')], default='draft', max_length=16)),
                ('created_by_id', models.PositiveBigIntegerField()),
                ('created_by_label', models.CharField(max_length=160)),
                ('submitted_by_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('submitted_by_label', models.CharField(blank=True, max_length=160)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('approved_by_label', models.CharField(blank=True, max_length=160)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('decision_reason', models.TextField(blank=True)),
                ('state_version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budget_calls', to='accounting.fiscalyear')),
            ],
            options={
                'ordering': ('-fiscal_year__year', '-created_at'),
                'permissions': (('view_budget_workspace', 'Can view the annual Budget workspace'), ('prepare_budget_calls', 'Can prepare annual budget calls and ceilings'), ('approve_budget_calls', 'Can independently approve annual budget calls'), ('prepare_budget_proposals', 'Can prepare annual budget proposals'), ('review_budget_proposals', 'Can review and consolidate annual budget proposals'), ('authorize_appropriations', 'Can authorize final operational appropriations'), ('view_budget_audit', 'Can view annual Budget audit evidence')),
            },
        ),
        migrations.CreateModel(
            name='BudgetVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_id', models.PositiveBigIntegerField(db_index=True)),
                ('department_label', models.CharField(max_length=160)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('kind', models.CharField(choices=[('department', 'Department proposal'), ('executive', 'Executive proposal'), ('sanggunian', 'Sanggunian version'), ('final', 'Final approved budget'), ('supplemental', 'Supplemental budget'), ('reenacted', 'Reenacted budget')], default='department', max_length=16)),
                ('version', models.PositiveIntegerField(default=1)),
                ('title', models.CharField(max_length=180)),
                ('requesting_department_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('requesting_department_label', models.CharField(blank=True, max_length=160)),
                ('change_explanation', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('for_review', 'For review'), ('returned', 'Returned'), ('approved', 'Approved proposal'), ('authorized', 'Authorized appropriation version')], default='draft', max_length=16)),
                ('created_by_id', models.PositiveBigIntegerField()),
                ('created_by_label', models.CharField(max_length=160)),
                ('submitted_by_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('submitted_by_label', models.CharField(blank=True, max_length=160)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('decided_by_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('decided_by_label', models.CharField(blank=True, max_length=160)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_reason', models.TextField(blank=True)),
                ('state_version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('budget_call', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='budget.budgetcall')),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budget_versions', to='accounting.fiscalyear')),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='successors', to='budget.budgetversion')),
            ],
            options={
                'ordering': ('-fiscal_year__year', 'kind', '-version'),
            },
        ),
        migrations.CreateModel(
            name='BudgetReviewComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_id', models.PositiveBigIntegerField(db_index=True)),
                ('department_label', models.CharField(max_length=160)),
                ('author_id', models.PositiveBigIntegerField()),
                ('author_label', models.CharField(max_length=160)),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='review_comments', to='budget.budgetversion')),
            ],
            options={
                'ordering': ('created_at', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='BudgetResourceEstimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_id', models.PositiveBigIntegerField(db_index=True)),
                ('department_label', models.CharField(max_length=160)),
                ('description', models.CharField(max_length=220)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('basis', models.TextField()),
                ('funding_source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budget_resource_estimates', to='accounting.fundingsource')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resource_estimates', to='budget.budgetversion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BudgetProposalLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_id', models.PositiveBigIntegerField(db_index=True)),
                ('department_label', models.CharField(max_length=160)),
                ('expense_class', models.CharField(max_length=40)),
                ('appropriation_type', models.CharField(choices=[('new', 'New'), ('continuing', 'Continuing'), ('statutory', 'Statutory / mandatory'), ('supplemental', 'Supplemental')], default='new', max_length=16)),
                ('particulars', models.CharField(max_length=240)),
                ('performance_target', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('change_explanation', models.TextField(blank=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budget_lines', to='accounting.ledgeraccount')),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budget_lines', to='accounting.fund')),
                ('funding_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='budget_lines', to='accounting.fundingsource')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='budget_lines', to='accounting.programactivityproject')),
                ('responsibility_center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budget_lines', to='accounting.responsibilitycenter')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='budget.budgetversion')),
            ],
            options={
                'ordering': ('responsibility_center__code', 'program__code', 'account__code', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='BudgetCeiling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_id', models.PositiveBigIntegerField(db_index=True)),
                ('department_label', models.CharField(max_length=160)),
                ('requesting_department_id', models.PositiveBigIntegerField()),
                ('requesting_department_label', models.CharField(max_length=160)),
                ('expense_class', models.CharField(max_length=40)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('basis', models.TextField()),
                ('budget_call', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ceilings', to='budget.budgetcall')),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budget_ceilings', to='accounting.fund')),
            ],
            options={
                'ordering': ('requesting_department_label', 'fund__code', 'expense_class'),
                'constraints': [models.UniqueConstraint(fields=('budget_call', 'requesting_department_id', 'fund', 'expense_class'), name='unique_budget_call_ceiling')],
            },
        ),
        migrations.AddConstraint(
            model_name='budgetversion',
            constraint=models.UniqueConstraint(fields=('budget_call', 'kind', 'requesting_department_id', 'version'), name='unique_budget_version_scope'),
        ),
    ]
