# Generated by Django 5.2.17 on 2026-08-28 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetVersionSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_id', models.PositiveBigIntegerField(db_index=True)),
                ('department_label', models.CharField(max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consolidation_links', to='budget.budgetversion')),
                ('target_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='source_links', to='budget.budgetversion')),
            ],
            options={
                'ordering': ('source_version__requesting_department_label', 'source_version__version'),
                'constraints': [models.UniqueConstraint(fields=('target_version', 'source_version'), name='unique_budget_consolidation_source')],
            },
        ),
    ]
