# Generated by Django 5.2.17 on 2026-08-28 12:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_budgetversionsource'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppropriationAuthorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_id', models.PositiveBigIntegerField(db_index=True)),
                ('department_label', models.CharField(max_length=160)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('authority_type', models.CharField(choices=[('ordinance', 'Annual appropriation ordinance'), ('supplemental', 'Supplemental appropriation'), ('reenacted', 'Reenacted budget authority')], max_length=16)),
                ('ordinance_number', models.CharField(max_length=100)),
                ('ordinance_date', models.DateField()),
                ('effectivity_date', models.DateField()),
                ('review_status', models.CharField(choices=[('pending', 'Pending review'), ('favorable', 'Favorable review'), ('conditional', 'Favorable with conditions'), ('adverse', 'Adverse / not executable')], default='pending', max_length=16)),
                ('review_reference', models.CharField(max_length=180)),
                ('review_date', models.DateField(blank=True, null=True)),
                ('conditions', models.TextField(blank=True)),
                ('evidence_reference', models.TextField(help_text='Reference the accepted ordinance, review, and signed schedule evidence; do not upload unredacted production evidence during synthetic UAT.')),
                ('signed_control_total', models.DecimalField(decimal_places=2, max_digits=18)),
                ('status', models.CharField(choices=[('draft', 'Draft evidence'), ('for_review', 'For independent authorization'), ('returned', 'Returned'), ('authorized', 'Operational appropriation authority')], default='draft', max_length=16)),
                ('snapshot_checksum', models.CharField(blank=True, max_length=64)),
                ('created_by_id', models.PositiveBigIntegerField()),
                ('created_by_label', models.CharField(max_length=160)),
                ('submitted_by_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('submitted_by_label', models.CharField(blank=True, max_length=160)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('authorized_by_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('authorized_by_label', models.CharField(blank=True, max_length=160)),
                ('authorized_at', models.DateTimeField(blank=True, null=True)),
                ('decision_reason', models.TextField(blank=True)),
                ('state_version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='appropriation_authorization', to='budget.budgetversion')),
            ],
            options={
                'ordering': ('-version__fiscal_year__year', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='AuthorizedAppropriationLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_id', models.PositiveBigIntegerField(db_index=True)),
                ('department_label', models.CharField(max_length=160)),
                ('source_line_id', models.PositiveBigIntegerField()),
                ('fund_code', models.CharField(max_length=40)),
                ('responsibility_center_code', models.CharField(max_length=40)),
                ('program_code', models.CharField(blank=True, max_length=60)),
                ('funding_source_code', models.CharField(blank=True, max_length=40)),
                ('account_code', models.CharField(max_length=40)),
                ('expense_class', models.CharField(max_length=40)),
                ('appropriation_type', models.CharField(max_length=16)),
                ('particulars', models.CharField(max_length=240)),
                ('performance_target', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('authorization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedule_lines', to='budget.appropriationauthorization')),
            ],
            options={
                'ordering': ('fund_code', 'responsibility_center_code', 'program_code', 'account_code', 'pk'),
                'constraints': [models.UniqueConstraint(fields=('authorization', 'source_line_id'), name='unique_authorized_appropriation_source_line')],
            },
        ),
    ]
