# Generated by Django 5.2.17 on 2026-08-28 12:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_opening_balance_control_intake'),
        ('budget', '0003_appropriationauthorization_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budgetcall',
            options={'ordering': ('-fiscal_year__year', '-created_at'), 'permissions': (('view_budget_workspace', 'Can view the annual Budget workspace'), ('prepare_budget_calls', 'Can prepare annual budget calls and ceilings'), ('approve_budget_calls', 'Can independently approve annual budget calls'), ('prepare_budget_proposals', 'Can prepare annual budget proposals'), ('review_budget_proposals', 'Can review and consolidate annual budget proposals'), ('authorize_appropriations', 'Can authorize final operational appropriations'), ('view_budget_audit', 'Can view annual Budget audit evidence'), ('view_allotment_control', 'Can view appropriation and allotment control'), ('prepare_allotment_releases', 'Can prepare allotment release orders'), ('approve_allotment_releases', 'Can independently post allotment release orders'))},
        ),
        migrations.CreateModel(
            name='AllotmentReleaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_id', models.PositiveBigIntegerField(db_index=True)),
                ('department_label', models.CharField(max_length=160)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('order_number', models.CharField(max_length=100)),
                ('kind', models.CharField(choices=[('initial', 'Initial allotment release'), ('later', 'Later allotment release'), ('reserve', 'Reserve / withholding'), ('deferral', 'Deferral'), ('adjustment', 'Allotment adjustment'), ('return', 'Allotment return'), ('cancellation', 'Allotment cancellation')], max_length=16)),
                ('release_date', models.DateField()),
                ('effective_date', models.DateField()),
                ('authority_reference', models.CharField(max_length=180)),
                ('evidence_reference', models.TextField(help_text='Reference the accepted ARO/equivalent and signed schedule; keep synthetic UAT evidence non-sensitive.')),
                ('purpose', models.TextField()),
                ('signed_control_total', models.DecimalField(decimal_places=2, max_digits=18)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('for_review', 'For independent review'), ('returned', 'Returned for correction'), ('posted', 'Posted to allotment ledger')], default='draft', max_length=16)),
                ('snapshot_checksum', models.CharField(blank=True, max_length=64)),
                ('created_by_id', models.PositiveBigIntegerField()),
                ('created_by_label', models.CharField(max_length=160)),
                ('submitted_by_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('submitted_by_label', models.CharField(blank=True, max_length=160)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('posted_by_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('posted_by_label', models.CharField(blank=True, max_length=160)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('decision_reason', models.TextField(blank=True)),
                ('state_version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('authorization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allotment_orders', to='budget.appropriationauthorization')),
                ('corrects', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='correction_orders', to='budget.allotmentreleaseorder')),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allotment_release_orders', to='accounting.fiscalyear')),
            ],
            options={
                'ordering': ('-fiscal_year__year', '-effective_date', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='AllotmentOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_id', models.PositiveBigIntegerField(db_index=True)),
                ('department_label', models.CharField(max_length=160)),
                ('movement_type', models.CharField(choices=[('release', 'Release allotment'), ('release_reduction', 'Reduce released allotment'), ('reserve', 'Place reserve / withholding'), ('reserve_release', 'Release reserve / withholding'), ('deferral', 'Defer available allotment'), ('deferral_release', 'Lift deferral'), ('return', 'Return allotment'), ('cancellation', 'Cancel allotment')], max_length=24)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('remarks', models.TextField(blank=True)),
                ('appropriation_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allotment_order_lines', to='budget.authorizedappropriationline')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='budget.allotmentreleaseorder')),
            ],
            options={
                'ordering': ('appropriation_line__fund_code', 'appropriation_line__responsibility_center_code', 'appropriation_line__account_code', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='AllotmentMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_id', models.PositiveBigIntegerField(db_index=True)),
                ('department_label', models.CharField(max_length=160)),
                ('source_line_id', models.PositiveBigIntegerField()),
                ('movement_type', models.CharField(choices=[('release', 'Release allotment'), ('release_reduction', 'Reduce released allotment'), ('reserve', 'Place reserve / withholding'), ('reserve_release', 'Release reserve / withholding'), ('deferral', 'Defer available allotment'), ('deferral_release', 'Lift deferral'), ('return', 'Return allotment'), ('cancellation', 'Cancel allotment')], max_length=24)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('release_effect', models.DecimalField(decimal_places=2, max_digits=18)),
                ('hold_effect', models.DecimalField(decimal_places=2, max_digits=18)),
                ('effective_date', models.DateField()),
                ('order_number_snapshot', models.CharField(max_length=100)),
                ('authority_reference_snapshot', models.CharField(max_length=180)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appropriation_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allotment_movements', to='budget.authorizedappropriationline')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='budget.allotmentreleaseorder')),
            ],
            options={
                'ordering': ('effective_date', 'pk'),
            },
        ),
        migrations.AddConstraint(
            model_name='allotmentreleaseorder',
            constraint=models.UniqueConstraint(fields=('department_id', 'fiscal_year', 'order_number'), name='unique_allotment_order_number'),
        ),
        migrations.AddConstraint(
            model_name='allotmentmovement',
            constraint=models.UniqueConstraint(fields=('order', 'source_line_id'), name='unique_allotment_movement_source'),
        ),
    ]
