# Generated by Django 5.2.17 on 2026-08-28 12:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_opening_balance_control_intake'),
        ('budget', '0004_alter_budgetcall_options_allotmentreleaseorder_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budgetcall',
            options={'ordering': ('-fiscal_year__year', '-created_at'), 'permissions': (('view_budget_workspace', 'Can view the annual Budget workspace'), ('prepare_budget_calls', 'Can prepare annual budget calls and ceilings'), ('approve_budget_calls', 'Can independently approve annual budget calls'), ('prepare_budget_proposals', 'Can prepare annual budget proposals'), ('review_budget_proposals', 'Can review and consolidate annual budget proposals'), ('authorize_appropriations', 'Can authorize final operational appropriations'), ('view_budget_audit', 'Can view annual Budget audit evidence'), ('view_allotment_control', 'Can view appropriation and allotment control'), ('prepare_allotment_releases', 'Can prepare allotment release orders'), ('approve_allotment_releases', 'Can independently post allotment release orders'), ('view_obligation_registry', 'Can view the obligation registry and accountability balances'), ('initiate_obligation_requests', 'Can initiate requesting-office obligation requests'), ('certify_obligations', 'Can independently certify obligations'))},
        ),
        migrations.CreateModel(
            name='ObligationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_id', models.PositiveBigIntegerField(db_index=True)),
                ('department_label', models.CharField(max_length=160)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('requesting_department_id', models.PositiveBigIntegerField(db_index=True)),
                ('requesting_department_label', models.CharField(max_length=160)),
                ('kind', models.CharField(choices=[('original', 'Original obligation'), ('adjustment', 'Obligation adjustment'), ('return', 'Obligation return'), ('cancellation', 'Obligation cancellation')], default='original', max_length=16)),
                ('form_type', models.CharField(choices=[('alobs', 'ALOBS'), ('ors', 'ORS'), ('obr', 'OBR')], default='obr', max_length=12)),
                ('request_reference', models.CharField(max_length=100)),
                ('obligation_number', models.CharField(blank=True, max_length=100)),
                ('obligation_date', models.DateField()),
                ('claimant_payee', models.CharField(max_length=220)),
                ('particulars', models.TextField()),
                ('evidence_reference', models.TextField(help_text='Reference the locally accepted request and support; keep synthetic UAT evidence non-sensitive.')),
                ('signed_control_total', models.DecimalField(decimal_places=2, max_digits=18)),
                ('linked_voucher_case_public_id', models.UUIDField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft request'), ('for_certification', 'For Budget certification'), ('returned', 'Returned for correction'), ('certified', 'Certified and posted')], default='draft', max_length=24)),
                ('snapshot_checksum', models.CharField(blank=True, max_length=64)),
                ('created_by_id', models.PositiveBigIntegerField()),
                ('created_by_label', models.CharField(max_length=160)),
                ('submitted_by_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('submitted_by_label', models.CharField(blank=True, max_length=160)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('certified_by_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('certified_by_label', models.CharField(blank=True, max_length=160)),
                ('certified_at', models.DateTimeField(blank=True, null=True)),
                ('decision_reason', models.TextField(blank=True)),
                ('state_version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('authorization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='obligation_requests', to='budget.appropriationauthorization')),
                ('corrects', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='correction_requests', to='budget.obligationrequest')),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='obligation_requests', to='accounting.fiscalyear')),
            ],
            options={
                'ordering': ('-fiscal_year__year', '-obligation_date', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='ObligationMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_id', models.PositiveBigIntegerField(db_index=True)),
                ('department_label', models.CharField(max_length=160)),
                ('source_line_id', models.PositiveBigIntegerField()),
                ('movement_type', models.CharField(choices=[('obligate', 'Obligate allotment'), ('reduce', 'Reduce / return obligation')], max_length=12)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('obligation_effect', models.DecimalField(decimal_places=2, max_digits=18)),
                ('effective_date', models.DateField()),
                ('obligation_number_snapshot', models.CharField(max_length=100)),
                ('requesting_department_snapshot', models.CharField(max_length=160)),
                ('claimant_payee_snapshot', models.CharField(max_length=220)),
                ('particulars_snapshot', models.TextField()),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appropriation_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='obligation_movements', to='budget.authorizedappropriationline')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='budget.obligationrequest')),
            ],
            options={
                'ordering': ('effective_date', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='ObligationRequestLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_id', models.PositiveBigIntegerField(db_index=True)),
                ('department_label', models.CharField(max_length=160)),
                ('movement_type', models.CharField(choices=[('obligate', 'Obligate allotment'), ('reduce', 'Reduce / return obligation')], default='obligate', max_length=12)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('remarks', models.TextField(blank=True)),
                ('appropriation_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='obligation_request_lines', to='budget.authorizedappropriationline')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='budget.obligationrequest')),
            ],
            options={
                'ordering': ('appropriation_line__fund_code', 'appropriation_line__responsibility_center_code', 'appropriation_line__account_code', 'pk'),
            },
        ),
        migrations.AddConstraint(
            model_name='obligationrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('obligation_number', ''), _negated=True), fields=('department_id', 'fiscal_year', 'obligation_number'), name='unique_certified_obligation_number'),
        ),
        migrations.AddConstraint(
            model_name='obligationrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'original')), fields=('requesting_department_id', 'fiscal_year', 'request_reference'), name='unique_original_obligation_request_reference'),
        ),
        migrations.AddConstraint(
            model_name='obligationmovement',
            constraint=models.UniqueConstraint(fields=('request', 'source_line_id'), name='unique_obligation_movement_source'),
        ),
    ]
