# Generated by Django 5.2.17 on 2026-08-29 00:55

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0005_alter_budgetcall_options_obligationrequest_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayableObligationAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_id', models.PositiveBigIntegerField(db_index=True)),
                ('department_label', models.CharField(max_length=160)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('voucher_case_public_id', models.UUIDField(db_index=True)),
                ('voucher_reference_snapshot', models.CharField(max_length=40)),
                ('relationship_type', models.CharField(choices=[('full', 'One-time / full claim'), ('partial', 'Partial claim; balance remains'), ('progress', 'Progress billing; balance remains'), ('final', 'Final claim; consume remaining balance')], max_length=16)),
                ('allocated_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('obligation_amount_snapshot', models.DecimalField(decimal_places=2, max_digits=18)),
                ('obligation_checksum_snapshot', models.CharField(max_length=64)),
                ('version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('active', 'Active allocation'), ('superseded', 'Superseded by guided revision'), ('cancelled', 'Removed before DV issuance')], default='active', max_length=16)),
                ('change_reason', models.TextField()),
                ('recorded_by_id', models.PositiveBigIntegerField()),
                ('recorded_by_label', models.CharField(max_length=160)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('obligation', models.ForeignKey(help_text='The certified original at the root of the corrected obligation lineage.', on_delete=django.db.models.deletion.PROTECT, related_name='payable_allocations', to='budget.obligationrequest')),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='successor_allocations', to='budget.payableobligationallocation')),
            ],
            options={
                'ordering': ('voucher_reference_snapshot', 'obligation__obligation_number', 'version'),
                'constraints': [models.UniqueConstraint(fields=('obligation', 'voucher_case_public_id', 'version'), name='unique_payable_allocation_version'), models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('obligation', 'voucher_case_public_id'), name='unique_active_payable_allocation'), models.CheckConstraint(condition=models.Q(('allocated_amount__gte', Decimal('0.00'))), name='payable_allocation_nonnegative')],
            },
        ),
    ]
