# Generated by Django 5.2.17 on 2026-09-09 13:06

from django.db import migrations, models


def require_unique_existing_identities(apps, schema_editor):
    obligations = apps.get_model('budget', 'ObligationRequest').objects.using(schema_editor.connection.alias)
    numbered = obligations.exclude(obligation_number='').values(
        'department_id', 'fiscal_year_id', 'obligation_number',
    ).annotate(count=models.Count('pk')).filter(count__gt=1)
    originals = obligations.filter(kind='original').values(
        'requesting_department_id', 'fiscal_year_id', 'request_reference',
    ).annotate(count=models.Count('pk')).filter(count__gt=1)
    if numbered.exists() or originals.exists():
        raise RuntimeError(
            'Duplicate obligation identities require controlled investigation before this migration. '
            'No financial records have been deduplicated or rewritten.'
        )


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0010_periodclosepolicy_periodcloserun_periodcloseevent_and_more'),
        ('budget', '0006_payableobligationallocation'),
    ]

    operations = [
        migrations.RunPython(require_unique_existing_identities, migrations.RunPython.noop),
        migrations.RemoveConstraint(
            model_name='obligationrequest',
            name='unique_certified_obligation_number',
        ),
        migrations.RemoveConstraint(
            model_name='obligationrequest',
            name='unique_original_obligation_request_reference',
        ),
        migrations.AddField(
            model_name='obligationrequest',
            name='original_request_reference',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(kind='original', then=models.F('request_reference')), default=models.Value(None)), null=True, output_field=models.CharField(max_length=100)),
        ),
        migrations.AddField(
            model_name='obligationrequest',
            name='unique_obligation_number',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(obligation_number='', then=models.Value(None)), default=models.F('obligation_number')), null=True, output_field=models.CharField(max_length=100)),
        ),
        migrations.AddConstraint(
            model_name='obligationrequest',
            constraint=models.UniqueConstraint(fields=('department_id', 'fiscal_year', 'unique_obligation_number'), name='unique_certified_obligation_number'),
        ),
        migrations.AddConstraint(
            model_name='obligationrequest',
            constraint=models.UniqueConstraint(fields=('requesting_department_id', 'fiscal_year', 'original_request_reference'), name='unique_original_obligation_request_reference'),
        ),
    ]
