# Generated by Django 5.2.17 on 2026-09-09 13:09

from django.db import migrations, models


def require_unique_active_allocations(apps, schema_editor):
    allocations = apps.get_model('budget', 'PayableObligationAllocation').objects.using(schema_editor.connection.alias)
    duplicates = allocations.filter(status='active').values(
        'obligation_id', 'voucher_case_public_id',
    ).annotate(count=models.Count('pk')).filter(count__gt=1)
    if duplicates.exists():
        raise RuntimeError(
            'Duplicate active payable allocations require controlled investigation before this migration. '
            'No allocation history has been deduplicated or rewritten.'
        )


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0007_remove_obligationrequest_unique_certified_obligation_number_and_more'),
    ]

    operations = [
        migrations.RunPython(require_unique_active_allocations, migrations.RunPython.noop),
        migrations.RemoveConstraint(
            model_name='payableobligationallocation',
            name='unique_active_payable_allocation',
        ),
        migrations.AddField(
            model_name='payableobligationallocation',
            name='active_identity_marker',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(status='active', then=models.Value(1)), default=models.Value(None)), null=True, output_field=models.PositiveSmallIntegerField()),
        ),
        migrations.AddConstraint(
            model_name='payableobligationallocation',
            constraint=models.UniqueConstraint(fields=('obligation', 'voucher_case_public_id', 'active_identity_marker'), name='unique_active_payable_allocation'),
        ),
    ]
