# Generated by Django 5.2.2 on 2025-06-06 12:28

import django.core.validators
import profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CitizenProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_number', models.CharField(max_length=11, null=True, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Contact Number')),
                ('address', models.CharField(max_length=255, null=True)),
                ('slug', models.SlugField(blank=True, default='')),
                ('social_auth', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_number', models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Contact Number')),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('profile_image', models.ImageField(blank=True, default='defaults/default_user_dp.png', upload_to=profiles.models.uploaded_images_directory_path, verbose_name='Profile Image')),
                ('slug', models.SlugField(blank=True, default='')),
                ('employment_type', models.CharField(blank=True, choices=[('', '---select one---'), ('REG', 'Regular Employee'), ('CT', 'Co-Terminus Employee'), ('JO', 'Job Order Employee')], default='', max_length=3)),
                ('assigned_department_memo', models.ImageField(blank=True, null=True, upload_to=profiles.models.temp_memo_path, verbose_name='Memo Image')),
            ],
        ),
    ]
