# Generated by Django 5.2 on 2025-06-10 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='civil_status',
            field=models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married'), ('Widowed', 'Widowed'), ('Divorced', 'Divorced'), ('Separated', 'Separated')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='gsis_id',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='GSIS ID'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='jo_date_hired',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='pagibig_id',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='PAG-IBIG ID'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='philhealth_id',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='PhilHealth ID'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='place_of_birth',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='position_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='reg_date_hired',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='salary_grade',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='sss_id',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='SSS ID'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='status_of_appointment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='step_increment',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='tin',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='TIN'),
        ),
    ]
