# Generated by Django 5.2 on 2025-06-25 06:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_employeeprofile_birthdate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileEditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_type', models.CharField(choices=[('employee', 'Employee'), ('citizen', 'Citizen')], max_length=10)),
                ('section', models.CharField(help_text='Section of the profile edited (e.g., HR Fields, Basic Info)', max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True, help_text='Optional note or reason for the update')),
                ('edited_by', models.ForeignKey(blank=True, help_text='Admin/HR/staff who made the change', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_edits_made', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='User whose profile was edited', on_delete=django.db.models.deletion.CASCADE, related_name='edited_profile_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
