# Generated by Django 5.1 on 2024-11-24 08:29

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='JO_Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_rate', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'verbose_name': 'JO Salary',
                'verbose_name_plural': 'JO Salaries',
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('ext_name', models.CharField(blank=True, max_length=3, null=True, verbose_name='Extension')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
            managers=[
                ('objects', users.models.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, choices=[('---select one---', 'select'), ('Accounting Office', 'ACCTG'), ('Agriculture Office', 'AGRI'), ('Business Processes & Licensing Office', 'BPLO'), ('Civil Security Unit', 'CSU'), ('General Services Office', 'GSO'), ('Human Resources', 'HR'), ("Local Civil Registrar's Office", 'LCR'), ("Municipal Administrator's Office", 'MA'), ('Environment & Natural Resources Office', 'MENRO'), ("Mayor's Office", 'MO'), ('Municipal Planning & Development Office', 'MPDO'), ('Social Welfare & Development', 'MSWD'), ("Treasurer's Office", 'MTO'), ('Nutrition Office', 'NUTRI'), ('Senior Citizen Affairs', 'OSCA'), ('Sangguniang Bayan Office', 'SB')], default='---select one---', max_length=80, verbose_name='Department: ')),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.manager')),
            ],
        ),
        migrations.CreateModel(
            name='RegOrCT_Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.PositiveIntegerField(null=True)),
                ('step', models.PositiveIntegerField(blank=True, default=0)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'verbose_name': 'RegOrCT Salary',
                'verbose_name_plural': 'RegOrCT Salaries',
                'unique_together': {('grade', 'step')},
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_number', models.CharField(max_length=11, null=True, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Contact Number')),
                ('address', models.CharField(max_length=255, null=True)),
                ('employment_type', models.CharField(blank=True, choices=[('---select one---', 'select'), ('Regular Employee', 'REG'), ('Co-Terminus Employee', 'CT'), ('Job Order Employee', 'JO')], default='---select one---', max_length=80)),
                ('designation', models.CharField(max_length=255, null=True)),
                ('image', models.ImageField(blank=True, default='defaults/default_user_dp.png', upload_to=users.models.Profile.dp_directory_path, verbose_name='Profile Picture: ')),
                ('slug', models.SlugField(blank=True, default='')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.department')),
                ('jo_salary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.jo_salary')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('reg_or_ct_salary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.regorct_salary')),
            ],
        ),
    ]
