# Generated by Django 5.1 on 2025-01-02 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='note',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
