# Generated by Django 5.1 on 2024-09-20 01:41

import django.core.validators
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.PositiveIntegerField(unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='sg_step',
        ),
        migrations.AddField(
            model_name='profile',
            name='salary_grade_step',
            field=models.PositiveIntegerField(default=0, help_text='Only visible to you or Administrators.', validators=[users.models.validate_salary_grade_step], verbose_name='Salary Grade Step'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(blank=True, choices=[('---select one---', 'select'), ('Accounting Office', 'ACCTG'), ('Agriculture Office', 'AGRI'), ('Business Processes & Licensing Office', 'BPLO'), ('Civil Security Unit', 'CSU'), ('General Services Office', 'GSO'), ('Human Resources', 'HR'), ("Local Civil Registrar's Office", 'LCR'), ("Municipal Administrator's Office", 'MA'), ('Environment & Natural Resources Office', 'MENRO'), ("Mayor's Office", 'MO'), ('Municipal Planning & Development Office', 'MPDO'), ('Social Welfare & Development', 'MSWD'), ("Treasurer's Office", 'MTO'), ('Nutrition Office', 'NUTRI'), ('Senior Citizen Affairs', 'OSCA'), ('Sangguniang Bayan Office', 'SB')], default='---select one---', max_length=80, verbose_name='Department: '),
        ),
        migrations.AlterField(
            model_name='profile',
            name='contact_number',
            field=models.CharField(max_length=11, null=True, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Contact Number'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='salary_grade',
            field=models.PositiveIntegerField(blank=True, help_text='Only visible to you or Administrators.', null=True, validators=[users.models.validate_salary_grade], verbose_name='Salary Grade'),
        ),
    ]
