# Generated by Django 5.1 on 2024-09-20 02:32

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_salary_remove_profile_sg_step_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='salary_grade_step',
            field=models.PositiveIntegerField(default=0, help_text='Only visible to you or Administrators.', null=True, validators=[users.models.validate_salary_grade_step], verbose_name='Salary Grade Step'),
        ),
    ]
