# Generated by Django 5.1 on 2025-03-24 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave_mgt', '0008_rename_total_sl_credits_leavecredit_sl_credits_from_prev_yr_and_more'),
        ('users', '0002_profile_note'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='EmployeeProfile',
        ),
    ]
