# Generated by Django 5.1 on 2025-03-24 14:31

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_profile_employeeprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='image',
            field=models.ImageField(blank=True, default='defaults/default_user_dp.png', upload_to=users.models.EmployeeProfile.dp_directory_path, verbose_name='Profile Image '),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
