# Generated by Django 5.1 on 2024-09-20 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_salary_grade_step'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='salary',
            name='grade',
            field=models.PositiveIntegerField(null=True, unique=True),
        ),
    ]
