# Generated by Django 5.2 on 2025-05-28 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_first_name_alter_user_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(blank=True, choices=[('---select one---', 'select'), ('Accounting Office', 'ACCTG'), ('Agriculture Office', 'AGRI'), ('Business Processes & Licensing Office', 'BPLO'), ('Civil Security Unit', 'CSU'), ('General Services Office', 'GSO'), ('Human Resource Management Office', 'HR'), ("Local Civil Registrar's Office", 'LCR'), ("Municipal Administrator's Office", 'MA'), ('Environment & Natural Resources Office', 'MENRO'), ("Mayor's Office", 'MO'), ('Municipal Planning & Development Office', 'MPDO'), ('Municipal Social Welfare & Development Office', 'MSWD'), ("Treasurer's Office", 'MTO'), ('Nutrition Office', 'NUTRI'), ('Senior Citizen Affairs', 'OSCA'), ('Sangguniang Bayan Office', 'SB')], default='---select one---', max_length=80, verbose_name='Department: '),
        ),
    ]
