# Generated by Django 5.1 on 2024-09-20 06:46

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_salary_options_salary_step_alter_profile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='salary_grade',
            field=models.PositiveIntegerField(null=True, validators=[users.models.validate_salary_grade], verbose_name='Salary Grade'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='salary_grade_step',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Only visible to you or Administrators.', validators=[users.models.validate_salary_grade_step], verbose_name='Salary Grade Step'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='grade',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.CreateModel(
            name='SalaryIncrement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.PositiveIntegerField()),
                ('step', models.PositiveIntegerField()),
                ('increment', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'Salary Increments',
                'unique_together': {('grade', 'step')},
            },
        ),
    ]
