# Generated by Django 5.1 on 2024-09-24 01:25

import django.db.models.deletion
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_profile_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('salary_grade', models.PositiveIntegerField(null=True, validators=[users.models.validate_salary_grade], verbose_name='Salary Grade')),
                ('salary_grade_step', models.PositiveIntegerField(blank=True, default=0, help_text='Only visible to you or Administrators.', validators=[users.models.validate_salary_grade_step], verbose_name='Salary Grade Step')),
            ],
        ),
        migrations.RemoveField(
            model_name='department',
            name='allowed_leaves_per_day',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='salary_grade',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='salary_grade_step',
        ),
        migrations.AlterField(
            model_name='profile',
            name='designation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.designation'),
        ),
    ]
