# Generated by Django 5.1 on 2025-06-03 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_department_plantilla_from'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='plantilla_from',
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='plantilla_from',
            field=models.CharField(blank=True, choices=[('---select one---', 'select'), ('Accounting Office', 'ACCTG'), ('Agriculture Office', 'AGRI'), ('Business Processes & Licensing Office', 'BPLO'), ('Civil Security Unit', 'CSU'), ('General Services Office', 'GSO'), ('Human Resource Management Office', 'HR'), ("Local Civil Registrar's Office", 'LCR'), ("Municipal Administrator's Office", 'MA'), ('Environment & Natural Resources Office', 'MENRO'), ("Mayor's Office", 'MO'), ('Municipal Planning & Development Office', 'MPDO'), ('Municipal Social Welfare & Development Office', 'MSWD'), ("Treasurer's Office", 'MTO'), ('Nutrition Office', 'NUTRI'), ('Senior Citizen Affairs', 'OSCA'), ('Sangguniang Bayan Office', 'SB')], default='---select one---', max_length=80, verbose_name='Platilla from '),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(blank=True, choices=[('---select one---', 'select'), ('Accounting Office', 'ACCTG'), ('Agriculture Office', 'AGRI'), ('Business Processes & Licensing Office', 'BPLO'), ('Civil Security Unit', 'CSU'), ('General Services Office', 'GSO'), ('Human Resource Management Office', 'HR'), ("Local Civil Registrar's Office", 'LCR'), ("Municipal Administrator's Office", 'MA'), ('Environment & Natural Resources Office', 'MENRO'), ("Mayor's Office", 'MO'), ('Municipal Planning & Development Office', 'MPDO'), ('Municipal Social Welfare & Development Office', 'MSWD'), ("Treasurer's Office", 'MTO'), ('Nutrition Office', 'NUTRI'), ('Senior Citizen Affairs', 'OSCA'), ('Sangguniang Bayan Office', 'SB')], default='---select one---', max_length=80, verbose_name='Department '),
        ),
    ]
