# Generated by Django 5.1 on 2024-09-27 06:46

from django.db import migrations

def create_default_designation(apps, schema_editor):
    Designation = apps.get_model('users', 'Designation')
    Designation.objects.create(
        name='Default Designation',
        salary_grade=1,
        salary_grade_step=0
    )

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_designation),
    ]