# Generated by Django 5.1 on 2024-09-27 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_designation_salary_grade'),
        ('users', '0010_auto_20240927_1446'),
    ]

    operations = [
    ]
