# Generated by Django 5.2.2 on 2025-06-06 12:28

import leave_mgt.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_year_sl_credits', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('current_year_vl_credits', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('current_year_special_credits', models.DecimalField(decimal_places=2, default=10, max_digits=5)),
                ('sl_credits_from_prev_yr', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('vl_credits_from_prev_yr', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('credits_accrued_this_month', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveCreditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_date', models.DateTimeField(auto_now_add=True)),
                ('action_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('SL', 'Sick Leave'), ('VL', 'Vacation Leave'), ('SP', 'Special Leave')], max_length=2)),
                ('date_filed', models.DateField(auto_now_add=True)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('number_of_days', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('form_photo', models.ImageField(blank=True, null=True, upload_to=leave_mgt.models.leave_form_directory_path, verbose_name='Form Photo (w/ Signatures): ')),
            ],
            options={
                'ordering': ['-date_filed'],
            },
        ),
        migrations.CreateModel(
            name='SL_Accrual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accrual_value', models.DecimalField(decimal_places=2, default=1.2, help_text='This defaults to 1.2 per month.', max_digits=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SL Accrual',
                'verbose_name_plural': 'SL Accruals',
            },
        ),
        migrations.CreateModel(
            name='VL_Accrual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accrual_value', models.DecimalField(decimal_places=2, default=1.2, help_text='This defaults to 1.2 per month.', max_digits=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'VL Accrual',
                'verbose_name_plural': 'VL Accruals',
            },
        ),
    ]
