# Generated by Django 5.1 on 2024-10-10 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0011_merge_20240927_1452'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveCredits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_year_sl_credits', models.FloatField(default=0)),
                ('current_year_vl_credits', models.FloatField(default=0)),
                ('speacial_leaves_taken', models.FloatField(default=0)),
                ('total_sl_credits', models.FloatField(default=0)),
                ('total_vl_credits', models.FloatField(default=0)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
    ]
