# Generated by Django 5.1 on 2024-10-14 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_mgt', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leavecredits',
            name='speacial_leaves_taken',
        ),
        migrations.AddField(
            model_name='leavecredits',
            name='credits_accrued_this_month',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='SL_Accrual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accrual_value', models.DecimalField(decimal_places=2, default=1.2, max_digits=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SL Accrual',
                'verbose_name_plural': 'SL Accruals',
                'constraints': [models.UniqueConstraint(fields=('id',), name='unique_sl_accrual')],
            },
        ),
        migrations.CreateModel(
            name='SpecialLeaves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('date_taken', models.DateField()),
                ('number_of_days', models.IntegerField()),
                ('leave_credits', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_leaves', to='leave_mgt.leavecredits')),
            ],
        ),
        migrations.CreateModel(
            name='VL_Accrual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accrual_value', models.DecimalField(decimal_places=2, default=1.2, max_digits=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'VL Accrual',
                'verbose_name_plural': 'VL Accruals',
                'constraints': [models.UniqueConstraint(fields=('id',), name='unique_vl_accrual')],
            },
        ),
    ]
