# Generated by Django 5.2.2 on 2025-06-06 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leave_mgt', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavecredit',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='profiles.employeeprofile'),
        ),
        migrations.AddField(
            model_name='leavecreditlog',
            name='leave_credits',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='leave_mgt.leavecredit'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='leave_mgt.leavecredit'),
        ),
        migrations.AddConstraint(
            model_name='sl_accrual',
            constraint=models.UniqueConstraint(fields=('id',), name='unique_sl_accrual'),
        ),
        migrations.AddConstraint(
            model_name='vl_accrual',
            constraint=models.UniqueConstraint(fields=('id',), name='unique_vl_accrual'),
        ),
    ]
