# Generated by Django 5.1 on 2024-10-14 07:43

import django.db.models.deletion
import leave_mgt.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_mgt', '0002_remove_leavecredits_speacial_leaves_taken_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavecredits',
            name='current_year_sl_credits',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='leavecredits',
            name='current_year_vl_credits',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='leavecredits',
            name='total_sl_credits',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='leavecredits',
            name='total_vl_credits',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('SL', 'Sick Leave'), ('VL', 'Vacation Leave'), ('SP', 'Special Leave')], max_length=2)),
                ('date_filed', models.DateField()),
                ('number_of_days', models.IntegerField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('date_taken', models.DateField(blank=True, null=True)),
                ('form_photo', models.ImageField(blank=True, null=True, upload_to=leave_mgt.models.leave_form_directory_path, verbose_name='Form Photo (w/ Signatures): ')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='leave_mgt.leavecredits')),
            ],
        ),
        migrations.DeleteModel(
            name='SpecialLeaves',
        ),
    ]
