# Generated by Django 5.2.17 on 2026-08-11 16:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_default_leave_policy(apps, schema_editor):
    LeavePolicy = apps.get_model('leave_mgt', 'LeavePolicy')
    LeavePolicy.objects.get_or_create(
        is_active=True,
        defaults={
            'name': 'Standard leave policy',
            'effective_from': '2025-01-01',
            'monthly_sick_accrual': 1.20,
            'monthly_vacation_accrual': 1.20,
            'special_leave_annual_allocation': 10,
            'minimum_request_increment': 0.50,
            'vacation_carryover_cap': 20,
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ('leave_mgt', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='day_portion',
            field=models.CharField(choices=[('FULL', 'Full day'), ('AM', 'Morning half-day'), ('PM', 'Afternoon half-day')], default='FULL', max_length=4),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='number_of_days',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True),
        ),
        migrations.CreateModel(
            name='LeavePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Standard leave policy', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('effective_from', models.DateField()),
                ('monthly_sick_accrual', models.DecimalField(decimal_places=2, default=1.2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('monthly_vacation_accrual', models.DecimalField(decimal_places=2, default=1.2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('special_leave_annual_allocation', models.DecimalField(decimal_places=2, default=10, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('minimum_request_increment', models.DecimalField(decimal_places=2, default=0.5, help_text="Smallest leave unit employees may request. Grand's UI supports 0.5 or 1 day.", max_digits=3, validators=[django.core.validators.MinValueValidator(0.5)])),
                ('sick_carryover_cap', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('vacation_carryover_cap', models.DecimalField(decimal_places=2, default=20, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_policies_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-effective_from', '-pk'],
                'permissions': [('manage_leave_credits', 'Can manage leave policies and credit adjustments')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='one_active_leave_policy')],
            },
        ),
        migrations.CreateModel(
            name='LeaveCreditTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('SL', 'Sick Leave'), ('VL', 'Vacation Leave'), ('SP', 'Special Leave')], max_length=2)),
                ('transaction_type', models.CharField(choices=[('ACCRUAL', 'Automatic accrual'), ('ADJUSTMENT', 'Manual adjustment'), ('DEDUCTION', 'Approved leave deduction'), ('REVERSAL', 'Reversal'), ('CARRYOVER', 'Yearly carry-over')], max_length=12)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('current_delta', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('carried_delta', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=7)),
                ('period', models.DateField(blank=True, help_text='First day of an automatic accrual month.', null=True)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('leave_credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='leave_mgt.leavecredit')),
                ('leave_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_transactions', to='leave_mgt.leaverequest')),
                ('reversal_of', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversal', to='leave_mgt.leavecredittransaction')),
                ('policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leave_mgt.leavepolicy')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('period__isnull', False), ('transaction_type', 'ACCRUAL')), fields=('leave_credit', 'leave_type', 'transaction_type', 'period'), name='unique_monthly_leave_accrual'), models.UniqueConstraint(condition=models.Q(('period__isnull', False), ('transaction_type', 'CARRYOVER')), fields=('leave_credit', 'leave_type', 'transaction_type', 'period'), name='unique_yearly_leave_carryover')],
            },
        ),
        migrations.RunPython(create_default_leave_policy, migrations.RunPython.noop),
    ]
