# Generated by Django 5.1 on 2024-10-14 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_mgt', '0003_alter_leavecredits_current_year_sl_credits_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavecredits',
            name='current_year_special_credits',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=5),
        ),
        migrations.AlterField(
            model_name='leave',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=10),
        ),
    ]
