# Generated by Django 5.1 on 2024-10-15 07:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_mgt', '0004_leavecredits_current_year_special_credits_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='date_taken',
        ),
        migrations.AddField(
            model_name='leave',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2024, 10, 15, 7, 39, 57, 779909, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leave',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2024, 10, 15, 7, 40, 10, 924075, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='leave',
            name='date_filed',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='number_of_days',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='sl_accrual',
            name='accrual_value',
            field=models.DecimalField(decimal_places=2, default=1.2, help_text='This defaults to 1.2 per month.', max_digits=4),
        ),
        migrations.AlterField(
            model_name='vl_accrual',
            name='accrual_value',
            field=models.DecimalField(decimal_places=2, default=1.2, help_text='This defaults to 1.2 per month.', max_digits=4),
        ),
    ]
