# Generated by Django 5.1 on 2024-10-17 02:39

import django.db.models.deletion
import leave_mgt.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_mgt', '0005_remove_leave_date_taken_leave_end_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveCreditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_date', models.DateTimeField(auto_now_add=True)),
                ('action_type', models.CharField(max_length=50)),
                ('leave_credits', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='leave_mgt.leavecredits')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('SL', 'Sick Leave'), ('VL', 'Vacation Leave'), ('SP', 'Special Leave')], max_length=2)),
                ('date_filed', models.DateField(auto_now_add=True)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('number_of_days', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('form_photo', models.ImageField(blank=True, null=True, upload_to=leave_mgt.models.leave_form_directory_path, verbose_name='Form Photo (w/ Signatures): ')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='leave_mgt.leavecredits')),
            ],
        ),
        migrations.DeleteModel(
            name='Leave',
        ),
    ]
