# Generated by Django 5.1 on 2024-12-10 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave_mgt', '0007_rename_leavecredits_leavecredit_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leavecredit',
            old_name='total_sl_credits',
            new_name='sl_credits_from_prev_yr',
        ),
        migrations.RenameField(
            model_name='leavecredit',
            old_name='total_vl_credits',
            new_name='vl_credits_from_prev_yr',
        ),
    ]
