"""Explicit invoice and instrument allocations for consolidated prior-payable DVs."""
from decimal import Decimal

from django.core.exceptions import ValidationError

from accounting.claim_groups import money, reserve, resolve, retired_amount
from accounting.models import JournalLine
from accounting.payables import _digest
from .models import PaymentInstrument


def deduction_sources(case):
    return [{"id": str(d.pk), "code": d.code, "amount": str(d.amount),
        "tax_evidence_checksum": d.tax_evidence_checksum}
        for d in case.disbursement_voucher.deductions.order_by("pk")]


def snapshot_for(case, rows, as_of):
    voucher = case.disbursement_voucher
    funds = set(case.obligation.allocation_lines.values_list("fund_code", flat=True))
    if not case.payee_id or len(funds) != 1:
        raise ValidationError("Allocate a consolidated DV to claims for one governed payee and one fund.")
    deductions = deduction_sources(case)
    totals = {d["id"]: Decimal("0.00") for d in deductions}
    claims, seen = [], set()
    if not isinstance(rows, list) or not rows:
        raise ValidationError("Enter the original claims and the gross amount allocated to each.")
    for row in rows:
        try:
            if not isinstance(row["source_id"], (int, str)) or isinstance(row["source_id"], bool):
                raise ValueError
            source_id = int(row["source_id"])
            parts = row.get("deductions", {})
            if not isinstance(parts, dict) or set(parts) - set(totals):
                raise ValueError
        except (KeyError, TypeError, ValueError):
            raise ValidationError("Choose original claims and the current DV deduction lines.")
        if source_id in seen:
            raise ValidationError("Enter each original claim only once.")
        seen.add(source_id)
        gross = money(row.get("gross"))
        allocated = {key: money(parts.get(key, "0")) for key in totals}
        net = gross - sum(allocated.values(), Decimal("0.00"))
        if gross <= 0 or net < 0:
            raise ValidationError("Each claim needs positive gross with deductions no greater than its gross.")
        for key, amount in allocated.items():
            totals[key] += amount
        claims.append({"source_id": source_id, "gross": str(gross), "net": str(net),
            "deductions": {key: str(amount) for key, amount in allocated.items()}})
    if sum((money(r["gross"]) for r in claims), Decimal("0.00")) != voucher.gross_amount:
        raise ValidationError("Claim allocations must equal the DV gross amount exactly.")
    if any(totals[d["id"]] != money(d["amount"]) for d in deductions):
        raise ValidationError("Allocate every DV deduction exactly across the selected claims.")
    if sum(totals.values(), Decimal("0.00")) != voucher.total_deductions:
        raise ValidationError("The DV deduction lines differ from the retained deduction total.")
    return {"voucher": voucher.pk, "date": as_of.isoformat(), "department": case.configuration_release.department_id,
        "party": f"finance-party:{case.payee.code}", "fund": funds.pop(),
        "gross": str(voucher.gross_amount), "net": str(voucher.net_amount), "deductions": deductions,
        "claims": sorted(claims, key=lambda r: r["source_id"])}


def reserve_for_validation(case, actor, rows, as_of):
    from .prior_payables import check_payment_policy, check_rule
    from finance.models import FinancePostingRule as Rule
    from finance.services import posting_rule_snapshot
    snapshot = snapshot_for(case, rows, as_of)
    if any(r.payload.get("earlier_accrual") for r in case.posting_requests.exclude(status="cancelled")):
        raise ValidationError("Use the single original claim generated by this payable's earlier accrual.")
    for row in snapshot["claims"]:
        source = JournalLine.objects.filter(pk=row["source_id"]).first()
        if source is None:
            raise ValidationError("Select a posted original payable claim.")
        variant = check_payment_policy(case, source)
        if case.disbursement_voucher.total_deductions:
            adjustment = variant.posting_rules.filter(event_kind=Rule.ADJUSTMENT).first()
            if not adjustment or adjustment.recognition_point != Rule.DV_VALIDATION:
                raise ValidationError("Configure the prior-payable deduction adjustment at DV validation.")
            check_rule(posting_rule_snapshot(adjustment)[0], deduction=True, source=source, transaction_type=case.transaction_type)
    return reserve(key=f"{case.public_id}:{case.state_version}", case_public_id=case.public_id,
        snapshot=snapshot, actor_id=actor.pk, as_of=as_of)


def verify_case(case, evidence):
    from datetime import date
    stored = evidence["allocation"]
    if snapshot_for(case, stored["claims"], date.fromisoformat(stored["date"])) != stored:
        raise ValidationError("The current DV differs from its retained claim and deduction allocation.")


def instrument_amounts(snapshot, evidence, amount):
    data = dict(snapshot)
    checksum = data.pop("checksum", None)
    if (checksum != _digest(data) or data.get("group") != evidence.get("group")
            or data.get("allocation_checksum") != evidence.get("checksum")):
        raise ValidationError("The check differs from its retained claim allocation.")
    amounts = data.get("amounts", {})
    limits = {member["reservation"]: money(row["net"])
        for member, row in zip(evidence["claims"], evidence["allocation"]["claims"])}
    if not isinstance(amounts, dict) or set(amounts) != set(limits):
        raise ValidationError("The check must retain every selected claim, including zero allocations.")
    amounts = {key: money(value) for key, value in amounts.items()}
    if sum(amounts.values(), Decimal("0.00")) != money(amount) or any(amounts[k] > limits[k] for k in limits):
        raise ValidationError("Claim payment amounts must equal the check and fit each claim's net allocation.")
    return amounts


def allocate_instrument(case, evidence, amount, requested=None, replaces=None):
    if evidence.get("schema") != 2:
        if requested:
            raise ValidationError("Claim payment allocations apply only to a consolidated DV.")
        return {}
    remaining = {member["reservation"]: money(row["net"])
        for member, row in zip(evidence["claims"], evidence["allocation"]["claims"])}
    for reservation in resolve(evidence, case_public_id=case.public_id):
        remaining[str(reservation.public_id)] -= retired_amount(reservation)
    for instrument in case.payment_instruments.exclude(status__in=(PaymentInstrument.CANCELLED, PaymentInstrument.BANK_RETURNED)):
        amounts = instrument_amounts(instrument.prior_payable_allocation, evidence, instrument.amount)
        for key in remaining:
            remaining[key] -= amounts[key]
    if replaces:
        original = instrument_amounts(replaces.prior_payable_allocation, evidence, replaces.amount)
        if money(amount) != replaces.amount or (requested and {k: money(v) for k, v in requested.items()} != original):
            raise ValidationError("A replacement must retain the original check amount and claim allocations.")
        amounts = original
    elif requested:
        if set(requested) != set(remaining):
            raise ValidationError("Enter each claim's share of this check, including zero shares.")
        amounts = {key: money(value) for key, value in requested.items()}
    elif sum(remaining.values(), Decimal("0.00")) == money(amount):
        amounts = remaining  # Paying the exact remainder has only one allocation.
    else:
        raise ValidationError("For a partial check, enter the amount paid against each claim.")
    if any(amounts[key] > remaining[key] or remaining[key] < 0 for key in remaining):
        raise ValidationError("A claim's net amount is already allocated to another active check.")
    data = {"group": evidence["group"], "allocation_checksum": evidence["checksum"],
        "amounts": {key: str(value) for key, value in amounts.items()}}
    snapshot = {**data, "checksum": _digest(data)}
    instrument_amounts(snapshot, evidence, amount)
    return snapshot


def event_evidence(case, evidence, trigger, amount):
    if evidence.get("schema") != 2:
        return {}
    instrument = case.payment_instruments.filter(public_id=trigger.get("instrument_public_id")).first()
    if instrument is None or instrument.amount != money(amount):
        raise ValidationError("The payment event must retain its exact check and claim allocation.")
    instrument_amounts(instrument.prior_payable_allocation, evidence, amount)
    return {"prior_payable_payment": instrument.prior_payable_allocation}


def posting_amounts(request, reservations):
    evidence = request.payload["prior_payable"]
    if evidence.get("schema") != 2:
        return None
    from finance.models import FinancePostingRule as Rule
    if request.kind == Rule.ADJUSTMENT:
        return {r.pk: money(row["gross"]) - money(row["net"])
            for r, row in zip(reservations, evidence["allocation"]["claims"])}
    amounts = instrument_amounts(request.payload.get("prior_payable_payment", {}), evidence, request.payload["event_amount"])
    # A request is immutable, but its link must still match the retained instrument.
    if event_evidence(request.case, evidence, request.payload.get("trigger", {}), request.payload["event_amount"])["prior_payable_payment"] != request.payload.get("prior_payable_payment"):
        raise ValidationError("The payment request differs from the original check allocation.")
    return {r.pk: amounts[str(r.public_id)] for r in reservations}


def amount_still_payable(case):
    from .prior_payables import current_evidence
    evidence = current_evidence(case)
    retired = (sum((retired_amount(r) for r in resolve(evidence, case_public_id=case.public_id)), Decimal("0.00"))
        if evidence.get("schema") == 2 else Decimal("0.00"))
    return case.disbursement_voucher.net_amount - retired
