from django.urls import path

from . import views

app_name = "reporting"

urlpatterns = [
    path("", views.workspace, name="workspace"),
    path("statement-mappings/", views.statement_mapping_list, name="statement_mapping_list"),
    path("statement-mappings/new/", views.statement_mapping_create, name="statement_mapping_create"),
    path("statement-mappings/<uuid:public_id>/", views.statement_mapping_detail, name="statement_mapping_detail"),
    path("statement-mappings/<uuid:public_id>/edit/", views.statement_mapping_update, name="statement_mapping_update"),
    path("statement-mappings/<uuid:public_id>/lines/new/", views.statement_line_create, name="statement_line_create"),
    path("statement-mappings/<uuid:public_id>/lines/<int:pk>/edit/", views.statement_line_update, name="statement_line_update"),
    path("statement-mappings/<uuid:public_id>/lines/<int:pk>/delete/", views.statement_line_delete, name="statement_line_delete"),
    path("statement-mappings/<uuid:public_id>/submit/", views.statement_mapping_submit, name="statement_mapping_submit"),
    path("statement-mappings/<uuid:public_id>/<str:action>/", views.statement_mapping_review, name="statement_mapping_review"),
    path("statement-notes/", views.statement_note_set_list, name="statement_note_set_list"),
    path("statement-notes/new/", views.statement_note_set_create, name="statement_note_set_create"),
    path("statement-notes/<uuid:public_id>/", views.statement_note_set_detail, name="statement_note_set_detail"),
    path("statement-notes/<uuid:public_id>/edit/", views.statement_note_set_update, name="statement_note_set_update"),
    path("statement-notes/<uuid:public_id>/topics/new/", views.statement_note_create, name="statement_note_create"),
    path("statement-notes/<uuid:public_id>/topics/<int:pk>/edit/", views.statement_note_update, name="statement_note_update"),
    path("statement-notes/<uuid:public_id>/topics/<int:pk>/delete/", views.statement_note_delete, name="statement_note_delete"),
    path("statement-notes/<uuid:public_id>/submit/", views.statement_note_set_submit, name="statement_note_set_submit"),
    path("statement-notes/<uuid:public_id>/export/", views.statement_note_set_export, name="statement_note_set_export"),
    path("statement-notes/<uuid:public_id>/<str:action>/", views.statement_note_set_review, name="statement_note_set_review"),
    path("runs/<uuid:run_public_id>/reference-comparisons/new/", views.reference_comparison_create, name="reference_comparison_create"),
    path("reference-comparisons/<uuid:public_id>/", views.reference_comparison_detail, name="reference_comparison_detail"),
    path("reference-comparisons/<uuid:public_id>/edit/", views.reference_comparison_update, name="reference_comparison_update"),
    path("reference-comparisons/<uuid:public_id>/submit/", views.reference_comparison_submit, name="reference_comparison_submit"),
    path("reference-comparisons/<uuid:public_id>/reference/", views.reference_comparison_download, name="reference_comparison_download"),
    path("reference-comparisons/<uuid:public_id>/export/", views.reference_comparison_export, name="reference_comparison_export"),
    path("reference-comparisons/<uuid:public_id>/<str:action>/", views.reference_comparison_review, name="reference_comparison_review"),
    path("definitions/new/", views.definition_create, name="definition_create"),
    path("definitions/<int:pk>/", views.definition_detail, name="definition_detail"),
    path("definitions/<int:pk>/edit/", views.definition_update, name="definition_update"),
    path("definitions/<int:pk>/templates/new/", views.template_create, name="template_create"),
    path("templates/<int:pk>/approve/", views.template_approve, name="template_approve"),
    path("templates/<int:pk>/mapping/", views.template_mapping, name="template_mapping"),
    path("templates/<int:pk>/mapping/preflight/", views.template_preflight, name="template_preflight"),
    path("templates/<int:pk>/mapping/<int:mapping_pk>/delete/", views.template_mapping_delete, name="template_mapping_delete"),
    path("templates/<int:pk>/reference/", views.template_reference_download, name="template_reference_download"),
    path("templates/<int:pk>/validate-fidelity/", views.template_validate_fidelity, name="template_validate_fidelity"),
    path("schedules/new/", views.schedule_create, name="schedule_create"),
    path("runs/<uuid:public_id>/", views.run_detail, name="run_detail"),
    path("runs/<uuid:public_id>/download/", views.run_download, name="run_download"),
    path("runs/<uuid:public_id>/control-evidence/", views.run_control_export, name="run_control_export"),
    path("runs/<uuid:public_id>/reproduction-receipt/", views.run_reproduction_receipt, name="run_reproduction_receipt"),
    path("runs/<uuid:public_id>/print/", views.run_print_preview, name="run_print_preview"),
    path("runs/<uuid:public_id>/<str:action>/", views.run_transition, name="run_transition"),
]
