# Generated by Django 5.2.17 on 2026-08-20 15:41

import django.core.validators
import django.db.models.deletion
import finance.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0004_alter_department_dashboard_template_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceConfigurationRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=80)),
                ('version', models.PositiveIntegerField(default=1)),
                ('title', models.CharField(max_length=180)),
                ('fiscal_year', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted for review'), ('approved', 'Approved'), ('scheduled', 'Scheduled'), ('active', 'Active'), ('superseded', 'Superseded'), ('retired', 'Retired')], default='draft', max_length=16)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('accounting_approval_note', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activated_finance_releases', to=settings.AUTH_USER_MODEL)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_finance_releases', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_finance_releases', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finance_releases', to='departments.department')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submitted_finance_releases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-fiscal_year', 'code', '-version'),
                'permissions': (('view_finance_setup', 'Can view Finance Setup Center'), ('manage_finance_configuration', 'Can prepare finance configuration'), ('approve_finance_configuration', 'Can approve finance configuration'), ('manage_finance_templates', 'Can prepare finance workbook templates'), ('manage_finance_providers', 'Can manage technical finance providers')),
            },
        ),
        migrations.CreateModel(
            name='FinanceConfigurationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('category', models.CharField(choices=[('transaction_type', 'Voucher / transaction type'), ('payee_classification', 'Payee classification'), ('fund', 'Fund'), ('responsibility_center', 'Office / responsibility center'), ('bank_account', 'Bank / payment account'), ('payment_method', 'Payment method'), ('account_classification', 'Account / expenditure classification'), ('obligation_behavior', 'OBR / obligation behavior'), ('tax_rule', 'Tax / deduction / rounding rule'), ('document_requirement', 'Supporting-document requirement'), ('approval_route', 'Approval step / threshold / route'), ('confidentiality', 'Confidentiality / retention setting')], max_length=32)),
                ('code', models.SlugField(max_length=80)),
                ('version', models.PositiveIntegerField(default=1)),
                ('label', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('configuration', models.JSONField(blank=True, default=dict, help_text='Controlled, category-specific values; never paste credentials or production personal data.')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted for review'), ('approved', 'Approved'), ('scheduled', 'Scheduled'), ('active', 'Active'), ('superseded', 'Superseded'), ('retired', 'Retired')], default='draft', max_length=16)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_finance_items', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finance_configuration_items', to='departments.department')),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='successor_versions', to='finance.financeconfigurationitem')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='finance.financeconfigurationrelease')),
            ],
            options={
                'ordering': ('category', 'code', '-version'),
            },
        ),
        migrations.CreateModel(
            name='FinanceAuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(max_length=40)),
                ('target_id', models.CharField(max_length=64)),
                ('action', models.CharField(max_length=60)),
                ('reason', models.TextField(blank=True)),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finance_audit_events', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finance_audit_events', to='departments.department')),
                ('release', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='finance.financeconfigurationrelease')),
            ],
            options={
                'ordering': ('-created_at', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='FinanceNumberingSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_year', models.PositiveSmallIntegerField()),
                ('document_type', models.SlugField(max_length=80)),
                ('prefix', models.CharField(blank=True, max_length=30)),
                ('padding', models.PositiveSmallIntegerField(default=6)),
                ('next_number', models.PositiveBigIntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted for review'), ('approved', 'Approved'), ('scheduled', 'Scheduled'), ('active', 'Active'), ('superseded', 'Superseded'), ('retired', 'Retired')], default='draft', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_finance_sequences', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finance_numbering_sequences', to='departments.department')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='numbering_sequences', to='finance.financeconfigurationrelease')),
            ],
        ),
        migrations.CreateModel(
            name='FinanceSignatory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_code', models.SlugField(max_length=80)),
                ('display_name', models.CharField(max_length=180)),
                ('position_title', models.CharField(max_length=180)),
                ('acting', models.BooleanField(default=False)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted for review'), ('approved', 'Approved'), ('scheduled', 'Scheduled'), ('active', 'Active'), ('superseded', 'Superseded'), ('retired', 'Retired')], default='draft', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_finance_signatories', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finance_signatories', to='departments.department')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='signatories', to='finance.financeconfigurationrelease')),
            ],
            options={
                'ordering': ('role_code', '-valid_from'),
            },
        ),
        migrations.CreateModel(
            name='FinanceTemplateVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.SlugField(default='disbursement-voucher', max_length=80)),
                ('version', models.PositiveIntegerField(default=1)),
                ('title', models.CharField(max_length=180)),
                ('workbook', models.FileField(max_length=500, upload_to=finance.models.finance_template_path, validators=[django.core.validators.FileExtensionValidator(('xlsx',))])),
                ('mapping', models.JSONField(blank=True, default=dict)),
                ('workbook_checksum', models.CharField(blank=True, max_length=64)),
                ('mapping_checksum', models.CharField(blank=True, max_length=64)),
                ('preflight_result', models.JSONField(blank=True, default=dict)),
                ('preflighted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted for review'), ('approved', 'Approved'), ('scheduled', 'Scheduled'), ('active', 'Active'), ('superseded', 'Superseded'), ('retired', 'Retired')], default='draft', max_length=16)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_finance_templates', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finance_templates', to='departments.department')),
                ('preflighted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='preflighted_finance_templates', to=settings.AUTH_USER_MODEL)),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='templates', to='finance.financeconfigurationrelease')),
            ],
            options={
                'ordering': ('document_type', '-version'),
            },
        ),
        migrations.AddConstraint(
            model_name='financeconfigurationrelease',
            constraint=models.UniqueConstraint(fields=('department', 'code', 'version'), name='unique_finance_release_version'),
        ),
        migrations.AddConstraint(
            model_name='financeconfigurationitem',
            constraint=models.UniqueConstraint(fields=('department', 'category', 'code', 'version'), name='unique_finance_item_version'),
        ),
        migrations.AddConstraint(
            model_name='financenumberingsequence',
            constraint=models.UniqueConstraint(fields=('department', 'fiscal_year', 'document_type'), name='unique_finance_numbering_sequence'),
        ),
        migrations.AddConstraint(
            model_name='financetemplateversion',
            constraint=models.UniqueConstraint(fields=('department', 'document_type', 'version'), name='unique_finance_template_version'),
        ),
    ]
