# Generated by Django 5.2.17 on 2026-08-25 15:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0004_alter_department_dashboard_template_and_more'),
        ('finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=80)),
                ('version', models.PositiveIntegerField(default=1)),
                ('display_name', models.CharField(max_length=220)),
                ('party_type', models.CharField(choices=[('supplier', 'Supplier / contractor'), ('individual', 'Individual claimant'), ('employee', 'Employee claimant'), ('agency', 'Government agency / organization')], default='supplier', max_length=20)),
                ('address', models.TextField(blank=True)),
                ('tax_identifier', models.CharField(blank=True, help_text='Store only when required by approved local policy.', max_length=40)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted for review'), ('approved', 'Approved'), ('scheduled', 'Scheduled'), ('active', 'Active'), ('superseded', 'Superseded'), ('retired', 'Retired')], default='draft', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_finance_parties', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finance_parties', to='departments.department')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parties', to='finance.financeconfigurationrelease')),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='successor_versions', to='finance.financeparty')),
            ],
            options={
                'ordering': ('display_name', '-version'),
            },
        ),
        migrations.CreateModel(
            name='FinancePartyClaimant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=220)),
                ('relationship', models.CharField(blank=True, max_length=120)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted for review'), ('approved', 'Approved'), ('scheduled', 'Scheduled'), ('active', 'Active'), ('superseded', 'Superseded'), ('retired', 'Retired')], default='draft', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_finance_claimants', to=settings.AUTH_USER_MODEL)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authorized_claimants', to='finance.financeparty')),
            ],
            options={
                'ordering': ('display_name', 'pk'),
            },
        ),
        migrations.AddConstraint(
            model_name='financeparty',
            constraint=models.UniqueConstraint(fields=('department', 'code', 'version'), name='unique_finance_party_version'),
        ),
    ]
