# Generated by Django 5.2.17 on 2026-08-25 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_financeparty_financepartyclaimant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financetemplateversion',
            name='document_type',
            field=models.SlugField(choices=[('disbursement-voucher', 'Disbursement voucher'), ('obr', 'Obligation request / OBR'), ('bank-advice', "Accountant's bank advice"), ('check-register', 'Check issuance register'), ('release-receipt', 'Check release receipt')], default='disbursement-voucher', max_length=80),
        ),
    ]
