# Generated by Django 5.2.17 on 2026-08-28 02:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("departments", "0004_alter_department_dashboard_template_and_more"),
        ("finance", "0003_alter_financetemplateversion_document_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FinanceWorkflowExemption",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("control_code", models.SlugField(choices=[
                    ("finance-release-self-approval", "Finance release preparer may approve the same release"),
                    ("budget-certifier-dv-preparation", "Budget certifier may prepare the same DV"),
                    ("dv-preparer-self-validation", "DV preparer may validate the same voucher"),
                    ("journal-preparer-self-posting", "Journal preparer may post the same JEV"),
                ], max_length=80)),
                ("rationale", models.TextField(help_text="Document the approved operational basis and compensating review control.")),
                ("effective_from", models.DateField(default=django.utils.timezone.localdate)),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="created_finance_workflow_exemptions", to=settings.AUTH_USER_MODEL)),
                ("department", models.ForeignKey(help_text="The exemption applies only while the actor is assigned to this department.", on_delete=django.db.models.deletion.PROTECT, related_name="finance_workflow_exemptions", to="departments.department")),
                ("subject_group", models.ForeignKey(blank=True, help_text="A group-based exemption follows the assigned role without naming each employee.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name="finance_workflow_exemptions", to="auth.group")),
                ("subject_user", models.ForeignKey(blank=True, help_text="Choose either one named user or one role/group, never both.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name="finance_workflow_exemptions", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ("department", "control_code", "-effective_from", "-pk"),
                "permissions": (("manage_workflow_exemptions", "Can manage governed finance workflow exemptions"),),
                "constraints": [models.CheckConstraint(condition=models.Q(models.Q(("subject_group__isnull", True), ("subject_user__isnull", False)), models.Q(("subject_group__isnull", False), ("subject_user__isnull", True)), _connector="OR"), name="finance_exemption_exactly_one_subject")],
            },
        ),
    ]
