# Generated by Django 5.2.17 on 2026-08-28 13:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0005_internal_howtos'),
        ('finance', '0005_finance_classification_categories'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceTransactionVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.SlugField(max_length=80)),
                ('label', models.CharField(max_length=180)),
                ('kind', models.CharField(choices=[('ordinary_supplier', 'Ordinary supplier / contractor'), ('payroll', 'Payroll'), ('reimbursement', 'Employee reimbursement'), ('utility', 'Utility / recurring billing'), ('financial_assistance', 'Financial assistance'), ('cash_advance', 'Cash advance'), ('liquidation', 'Cash advance liquidation'), ('infrastructure', 'Infrastructure / progress billing'), ('other', 'Other locally approved variant')], max_length=32)),
                ('description', models.TextField()),
                ('authority_reference', models.TextField(help_text='Cite the reviewed COA/DBM/local authority and applicability decision; do not imply acceptance from a public source alone.')),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted for review'), ('approved', 'Approved'), ('scheduled', 'Scheduled'), ('active', 'Active'), ('superseded', 'Superseded'), ('retired', 'Retired')], default='draft', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_finance_transaction_variants', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finance_transaction_variants', to='departments.department')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transaction_variants', to='finance.financeconfigurationrelease')),
            ],
            options={
                'ordering': ('label', 'code'),
            },
        ),
        migrations.CreateModel(
            name='FinanceDocumentRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.SlugField(max_length=80)),
                ('label', models.CharField(max_length=180)),
                ('evidence_kind', models.CharField(choices=[('request', 'Request / initiating authority'), ('procurement', 'Procurement evidence'), ('contract', 'Contract / purchase order'), ('delivery', 'Delivery / accomplishment evidence'), ('inspection_acceptance', 'Inspection / acceptance'), ('invoice_billing', 'Invoice / billing'), ('payroll', 'Payroll schedule / certification'), ('travel_reimbursement', 'Travel / reimbursement claim'), ('assistance_claim', 'Assistance eligibility / claim authority'), ('liquidation', 'Liquidation evidence'), ('other', 'Other reviewed evidence')], max_length=32)),
                ('required', models.BooleanField(default=True)),
                ('waiver_allowed', models.BooleanField(default=False)),
                ('condition_description', models.TextField(blank=True)),
                ('authority_reference', models.TextField()),
                ('display_order', models.PositiveSmallIntegerField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_finance_document_rules', to=settings.AUTH_USER_MODEL)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_rules', to='finance.financetransactionvariant')),
            ],
            options={
                'ordering': ('display_order', 'code'),
            },
        ),
        migrations.AddConstraint(
            model_name='financetransactionvariant',
            constraint=models.UniqueConstraint(fields=('release', 'code'), name='unique_finance_variant_per_release'),
        ),
        migrations.AddConstraint(
            model_name='financedocumentrule',
            constraint=models.UniqueConstraint(fields=('variant', 'code'), name='unique_document_rule_per_variant'),
        ),
    ]
