# Generated by Django 5.2.17 on 2026-08-30 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0005_internal_howtos'),
        ('finance', '0006_financetransactionvariant_financedocumentrule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financesignatory',
            name='custody_department',
            field=models.ForeignKey(blank=True, help_text='Office that physically receives the paper for this signature. Leave blank to use the Finance office.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_signature_routes', to='departments.department'),
        ),
        migrations.AddField(
            model_name='financesignatory',
            name='custody_instructions',
            field=models.TextField(blank=True, help_text="Plain-language packet instruction, such as 'Leave with the Mayor's receiving clerk for signature.'"),
        ),
        migrations.AddField(
            model_name='financetemplateversion',
            name='authority_reference',
            field=models.TextField(blank=True, help_text='Reviewed COA/DBM/local issuance or procedure used to assess this layout.'),
        ),
        migrations.AddField(
            model_name='financetemplateversion',
            name='comparison_reference',
            field=models.TextField(blank=True, help_text='Blank form, redacted sample, comparison record, and accepting office reference.'),
        ),
        migrations.AddField(
            model_name='financetemplateversion',
            name='controlled_print_required',
            field=models.BooleanField(default=True, help_text='Require a recorded print version and TracePoint packet before wet-signature recording.'),
        ),
        migrations.AddField(
            model_name='financetemplateversion',
            name='default_copy_count',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='financetemplateversion',
            name='form_reference',
            field=models.CharField(blank=True, help_text='Familiar form number or local title shown to users. Do not call it official unless locally accepted.', max_length=180),
        ),
        migrations.AddField(
            model_name='financetemplateversion',
            name='form_status',
            field=models.CharField(choices=[('starter', 'Editable starter — not yet locally accepted'), ('pilot', 'Pilot comparison — acceptance pending'), ('locally_accepted', 'Locally accepted against recorded evidence')], default='starter', max_length=24),
        ),
        migrations.AddField(
            model_name='financetemplateversion',
            name='orientation',
            field=models.CharField(choices=[('portrait', 'Portrait'), ('landscape', 'Landscape')], default='portrait', max_length=12),
        ),
        migrations.AddField(
            model_name='financetemplateversion',
            name='paper_size',
            field=models.CharField(choices=[('a4', 'A4'), ('letter', 'Letter'), ('legal', 'Legal')], default='a4', max_length=12),
        ),
        migrations.AddField(
            model_name='financetemplateversion',
            name='printer_instructions',
            field=models.TextField(blank=True, help_text='Ordinary operator guidance: paper stock, tray, duplex setting, margins, or copy handling.'),
        ),
    ]
