# Generated by Django 5.2.17 on 2026-08-30 15:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_financesignatory_custody_department_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancePostingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.SlugField(max_length=80)),
                ('title', models.CharField(max_length=180)),
                ('event_kind', models.CharField(choices=[('recognition', 'Recognize expense, asset, or payable'), ('adjustment', 'Adjust an earlier recognition'), ('liquidation', 'Record liquidation'), ('payment', 'Settle payable / record payment'), ('remittance', 'Remit deductions or withholdings'), ('cancellation', 'Record cancellation effect'), ('reversal', 'Reverse an earlier entry'), ('replacement', 'Record replacement effect')], max_length=24)),
                ('recognition_point', models.CharField(choices=[('delivery_acceptance', 'Delivery / inspection acceptance'), ('billing_validation', 'Billing or claim validation'), ('dv_validation', 'DV Accounting validation'), ('payment_issuance', 'Check / payment-instrument issuance'), ('payment_release', 'Actual payment release'), ('liquidation_acceptance', 'Liquidation acceptance'), ('period_end', 'Period-end review'), ('other', 'Other locally confirmed point')], max_length=32)),
                ('description', models.TextField(help_text='Explain in ordinary Accounting language when this entry is used.')),
                ('authority_reference', models.TextField(help_text='Reviewed COA/local accounting basis and local applicability or acceptance reference.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_finance_posting_rules', to=settings.AUTH_USER_MODEL)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posting_rules', to='finance.financetransactionvariant')),
            ],
            options={
                'ordering': ('variant__label', 'event_kind', 'code'),
            },
        ),
        migrations.CreateModel(
            name='FinancePostingRuleLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveSmallIntegerField()),
                ('label', models.CharField(help_text='Plain-language purpose shown to Accounting reviewers.', max_length=180)),
                ('side', models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], max_length=8)),
                ('account_source', models.CharField(choices=[('allocation_accounts', 'Each voucher allocation account'), ('deduction_mappings', "Each deduction's configured payable account"), ('payable_mapping', "Transaction's configured payable account"), ('bank_mapping', "Payment account's configured bank/cash account"), ('fixed_account', 'One locally confirmed ledger account code')], max_length=28)),
                ('amount_source', models.CharField(choices=[('each_allocation', 'Each allocation amount'), ('each_deduction', 'Each deduction amount'), ('gross', 'Voucher gross amount'), ('net', 'Voucher net amount'), ('total_deductions', 'Total deductions')], max_length=24)),
                ('mapping_code', models.CharField(blank=True, help_text='Optional mapping override. Leave blank to use the transaction or payment-account code.', max_length=80)),
                ('ledger_account_code', models.CharField(blank=True, help_text='Required only for one locally confirmed fixed ledger account.', max_length=80)),
                ('memo', models.CharField(blank=True, max_length=180)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='finance.financepostingrule')),
            ],
            options={
                'ordering': ('sequence', 'pk'),
            },
        ),
        migrations.AddConstraint(
            model_name='financepostingrule',
            constraint=models.UniqueConstraint(fields=('variant', 'event_kind'), name='unique_finance_posting_event_per_variant'),
        ),
        migrations.AddConstraint(
            model_name='financepostingruleline',
            constraint=models.UniqueConstraint(fields=('rule', 'sequence'), name='unique_finance_posting_rule_line_sequence'),
        ),
    ]
