# Generated by Django 5.2.17 on 2026-08-30 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_financepostingrule_financepostingruleline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financepostingrule',
            name='accounting_effect',
            field=models.CharField(choices=[('journal_entry', 'Create a governed journal entry'), ('no_entry', 'Record that no journal entry is required')], default='journal_entry', help_text='Choose an explicit no-entry decision when the reviewed local treatment has no ledger effect.', max_length=16),
        ),
        migrations.AlterField(
            model_name='financepostingrule',
            name='recognition_point',
            field=models.CharField(choices=[('delivery_acceptance', 'Delivery / inspection acceptance'), ('billing_validation', 'Billing or claim validation'), ('dv_validation', 'DV Accounting validation'), ('payment_issuance', 'Check / payment-instrument issuance'), ('payment_release', 'Actual payment release'), ('payment_cancellation', 'Payment-instrument cancellation'), ('payment_replacement', 'Replacement payment-instrument issuance'), ('deduction_remittance', 'Deduction / withholding remittance'), ('liquidation_acceptance', 'Liquidation acceptance'), ('period_end', 'Period-end review'), ('other', 'Other locally confirmed point')], max_length=32),
        ),
        migrations.AlterField(
            model_name='financepostingruleline',
            name='amount_source',
            field=models.CharField(choices=[('each_allocation', 'Each allocation amount'), ('each_deduction', 'Each deduction amount'), ('gross', 'Voucher gross amount'), ('net', 'Voucher net amount'), ('total_deductions', 'Total deductions'), ('event_amount', 'Current payment / cancellation / replacement / remittance amount')], max_length=24),
        ),
    ]
