# Generated by Django 5.2.17 on 2026-08-30 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_financepostingrule_accounting_effect_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financepostingrule',
            name='recognition_point',
            field=models.CharField(choices=[('delivery_acceptance', 'Delivery / inspection acceptance'), ('billing_validation', 'Billing or claim validation'), ('dv_validation', 'DV Accounting validation'), ('payment_issuance', 'Check / payment-instrument issuance'), ('payment_release', 'Actual payment release'), ('payment_return', 'Bank-returned payment instrument'), ('payment_cancellation', 'Payment-instrument cancellation'), ('payment_replacement', 'Replacement payment-instrument issuance'), ('deduction_remittance', 'Deduction / withholding remittance'), ('liquidation_acceptance', 'Liquidation acceptance'), ('period_end', 'Period-end review'), ('other', 'Other locally confirmed point')], max_length=32),
        ),
    ]
