# Generated by Django 5.2.17 on 2026-08-31 03:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0005_internal_howtos'),
        ('finance', '0010_alter_financepostingrule_recognition_point'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceShadowCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.SlugField(max_length=80)),
                ('title', models.CharField(max_length=180)),
                ('fiscal_year', models.PositiveSmallIntegerField()),
                ('run_kind', models.CharField(choices=[('shadow', 'Limited shadow pilot'), ('parallel', 'Controlled parallel run')], default='shadow', max_length=16)),
                ('enabled_scope', models.TextField(help_text='State the offices, funds, transaction types, and dates included in this cycle.')),
                ('source_system_label', models.CharField(default='Current locally authoritative process', max_length=120)),
                ('source_extract_reference', models.TextField(help_text='Reference the redacted/read-only source extract or retained register; do not upload production data here.')),
                ('source_checksum', models.CharField(help_text='SHA-256 checksum of the exact redacted/read-only source used for comparison.', max_length=64)),
                ('source_schema_signature', models.CharField(help_text='SHA-256 signature of the reviewed column/schema contract used to detect drift.', max_length=64)),
                ('planned_start', models.DateField()),
                ('planned_end', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft plan'), ('running', 'Shadow / parallel run in progress'), ('reconciliation_review', 'Awaiting independent reconciliation'), ('reconciled', 'Independently reconciled'), ('returned', 'Returned for another cycle')], default='draft', max_length=32)),
                ('evidence_checksum', models.CharField(blank=True, max_length=64)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reconciled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_finance_shadow_cycles', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finance_shadow_cycles', to='departments.department')),
                ('predecessor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='successor_cycles', to='finance.financeshadowcycle')),
                ('reconciled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reconciled_finance_shadow_cycles', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submitted_finance_shadow_cycles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-fiscal_year', '-planned_start', 'code'),
                'permissions': (('manage_shadow_operation', 'Can prepare finance shadow operation evidence'), ('review_shadow_reconciliation', 'Can independently reconcile finance shadow operation'), ('authorize_finance_cutover', 'Can authorize or decline finance cutover')),
            },
        ),
        migrations.CreateModel(
            name='FinanceShadowComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comparison_level', models.CharField(choices=[('case', 'Case / transaction'), ('batch', 'Batch'), ('period', 'Period control'), ('register', 'Register'), ('ledger', 'Ledger'), ('report', 'Report / statement')], max_length=16)),
                ('control_code', models.SlugField(max_length=80)),
                ('label', models.CharField(max_length=180)),
                ('source_reference', models.TextField()),
                ('grand_reference', models.TextField()),
                ('source_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('grand_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('source_count', models.PositiveIntegerField(blank=True, null=True)),
                ('grand_count', models.PositiveIntegerField(blank=True, null=True)),
                ('amount_difference', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=20, null=True)),
                ('count_difference', models.IntegerField(blank=True, editable=False, null=True)),
                ('outcome', models.CharField(choices=[('matched', 'Matched exactly'), ('explained', 'Difference explained and accepted for review'), ('open_defect', 'Open defect / unresolved difference')], max_length=16)),
                ('explanation', models.TextField(blank=True)),
                ('evidence_reference', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_finance_shadow_comparisons', to=settings.AUTH_USER_MODEL)),
                ('defect_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owned_finance_shadow_defects', to=settings.AUTH_USER_MODEL)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comparisons', to='finance.financeshadowcycle')),
            ],
            options={
                'ordering': ('comparison_level', 'control_code', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='FinanceCutoverDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authority_matrix_reference', models.TextField()),
                ('enabled_scope', models.TextField()),
                ('cutover_at', models.DateTimeField()),
                ('opening_reconciliation_reference', models.TextField()),
                ('rollback_criteria', models.TextField()),
                ('legacy_read_only_retention_plan', models.TextField()),
                ('backup_recovery_evidence', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft decision record'), ('submitted', 'Awaiting cutover authority'), ('authorized', 'Cutover authorized for stated scope/date'), ('declined', 'Cutover not authorized'), ('rolled_back', 'Recorded rollback invoked')], default='draft', max_length=16)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='authorized_finance_cutover_decisions', to=settings.AUTH_USER_MODEL)),
                ('prepared_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prepared_finance_cutover_decisions', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submitted_finance_cutover_decisions', to=settings.AUTH_USER_MODEL)),
                ('cycle', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='cutover_decision', to='finance.financeshadowcycle')),
            ],
            options={
                'ordering': ('-cutover_at', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='FinanceStakeholderAcceptance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stakeholder_kind', models.CharField(choices=[('requesting_office', 'Requesting office'), ('budget', 'Budget'), ('accounting', 'Accounting'), ('treasury', 'Treasury'), ('it', 'IT / system administration'), ('management', 'Management / cutover authority'), ('audit', 'Audit stakeholder')], max_length=24)),
                ('enabled_scope', models.TextField()),
                ('training_evidence_reference', models.TextField(blank=True)),
                ('uat_evidence_reference', models.TextField(blank=True)),
                ('decision', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted for stated scope'), ('conditional', 'Accepted with conditions'), ('rejected', 'Not accepted')], default='pending', max_length=16)),
                ('conditions_or_reason', models.TextField(blank=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_finance_shadow_acceptances', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_finance_shadow_acceptances', to=settings.AUTH_USER_MODEL)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stakeholder_acceptances', to='finance.financeshadowcycle')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='decided_finance_shadow_acceptances', to=settings.AUTH_USER_MODEL)),
                ('office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_shadow_acceptances', to='departments.department')),
            ],
            options={
                'ordering': ('stakeholder_kind', 'office__name', 'pk'),
            },
        ),
        migrations.AddConstraint(
            model_name='financeshadowcycle',
            constraint=models.UniqueConstraint(fields=('department', 'code'), name='unique_finance_shadow_cycle_code'),
        ),
        migrations.AddConstraint(
            model_name='financeshadowcomparison',
            constraint=models.UniqueConstraint(fields=('cycle', 'comparison_level', 'control_code'), name='unique_shadow_comparison_control'),
        ),
    ]
