# Generated by Django 5.2.17 on 2026-08-31 04:14

import django.core.validators
import django.db.models.deletion
import finance.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_financeshadowcycle_financeshadowcomparison_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='financeshadowcycle',
            name='source_checksum',
            field=models.CharField(blank=True, help_text='GRAND calculates this lock when a redacted CSV is staged.', max_length=64),
        ),
        migrations.AlterField(
            model_name='financeshadowcycle',
            name='source_schema_signature',
            field=models.CharField(blank=True, help_text='GRAND calculates this column-layout signature to detect drift.', max_length=64),
        ),
        migrations.CreateModel(
            name='FinanceShadowSourceVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('intake_kind', models.CharField(choices=[('uploaded_csv', 'Redacted CSV staged in GRAND'), ('external_lock', 'Externally calculated source lock')], max_length=20)),
                ('source_file', models.FileField(blank=True, help_text='Retained redacted/read-only CSV. GRAND does not execute or import its rows.', max_length=500, upload_to=finance.models.finance_shadow_source_path, validators=[django.core.validators.FileExtensionValidator(('csv',))])),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('source_checksum', models.CharField(max_length=64)),
                ('normalized_headers', models.JSONField(blank=True, default=list)),
                ('row_count', models.PositiveIntegerField(blank=True, null=True)),
                ('schema_signature', models.CharField(max_length=64)),
                ('predecessor_schema_signature', models.CharField(blank=True, max_length=64)),
                ('schema_comparison', models.CharField(choices=[('baseline', 'Baseline; no predecessor to compare'), ('matched', 'Matches predecessor layout'), ('drift', 'Column layout changed')], max_length=16)),
                ('sensitive_header_warnings', models.JSONField(blank=True, default=list)),
                ('redaction_confirmed', models.BooleanField(default=False)),
                ('redaction_note', models.TextField()),
                ('change_reason', models.TextField(blank=True)),
                ('is_current', models.BooleanField(default=True)),
                ('review_status', models.CharField(choices=[('not_required', 'No separate drift review required'), ('pending', 'Awaiting independent drift review'), ('accepted', 'Drift independently accepted for this cycle'), ('rejected', 'Drift rejected')], default='not_required', max_length=16)),
                ('review_note', models.TextField(blank=True)),
                ('staged_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='source_versions', to='finance.financeshadowcycle')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_finance_shadow_source_drifts', to=settings.AUTH_USER_MODEL)),
                ('staged_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staged_finance_shadow_sources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-version', '-pk'),
                'constraints': [models.UniqueConstraint(fields=('cycle', 'version'), name='unique_shadow_source_version'), models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('cycle',), name='unique_current_shadow_source_version')],
            },
        ),
    ]
