# Generated by Django 5.2.17 on 2026-08-31 04:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_alter_financeshadowcycle_source_checksum_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceShadowReconciliationPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cadence', models.CharField(choices=[('calendar_daily', 'Every calendar day'), ('business_daily', 'Every working day (Monday–Friday)')], max_length=20)),
                ('first_due_at', models.DateTimeField()),
                ('grace_minutes', models.PositiveIntegerField(default=60)),
                ('minimum_reviewed_runs', models.PositiveIntegerField(default=1)),
                ('enabled_transaction_types', models.TextField(help_text='Name the transaction types covered by each scheduled comparison run.')),
                ('local_authority_reference', models.TextField()),
                ('local_acceptance_note', models.TextField()),
                ('critical_resolution_hours', models.PositiveIntegerField(default=4)),
                ('critical_escalation_route', models.CharField(max_length=200)),
                ('high_resolution_hours', models.PositiveIntegerField(default=8)),
                ('high_escalation_route', models.CharField(max_length=200)),
                ('medium_resolution_hours', models.PositiveIntegerField(default=24)),
                ('medium_escalation_route', models.CharField(max_length=200)),
                ('low_resolution_hours', models.PositiveIntegerField(default=72)),
                ('low_escalation_route', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('draft', 'Draft local plan'), ('submitted', 'Awaiting independent approval'), ('approved', 'Approved for this cycle'), ('returned', 'Returned for correction')], default='draft', max_length=16)),
                ('evidence_checksum', models.CharField(blank=True, max_length=64)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_finance_shadow_reconciliation_plans', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_finance_shadow_reconciliation_plans', to=settings.AUTH_USER_MODEL)),
                ('cycle', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='reconciliation_plan', to='finance.financeshadowcycle')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submitted_finance_shadow_reconciliation_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='FinanceShadowReconciliationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('scheduled_for', models.DateTimeField()),
                ('due_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('open', 'Open comparison run'), ('submitted', 'Awaiting independent review'), ('reconciled', 'Independently reconciled'), ('reviewed_exceptions', 'Reviewed with open exceptions'), ('returned', 'Returned for correction')], default='open', max_length=24)),
                ('comparison_snapshot', models.JSONField(blank=True, default=list)),
                ('defect_snapshot', models.JSONField(blank=True, default=list)),
                ('comparison_count', models.PositiveIntegerField(default=0)),
                ('matched_count', models.PositiveIntegerField(default=0)),
                ('explained_count', models.PositiveIntegerField(default=0)),
                ('open_defect_count', models.PositiveIntegerField(default=0)),
                ('evidence_checksum', models.CharField(blank=True, max_length=64)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reconciliation_runs', to='finance.financeshadowcycle')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='finance.financeshadowreconciliationplan')),
                ('prepared_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prepared_finance_shadow_reconciliation_runs', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_finance_shadow_reconciliation_runs', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submitted_finance_shadow_reconciliation_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('sequence', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='FinanceShadowDefect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=80)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=12)),
                ('summary', models.CharField(max_length=200)),
                ('impact', models.TextField()),
                ('correction_due_at', models.DateTimeField()),
                ('escalation_route_snapshot', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('open', 'Open / being corrected'), ('resolution_review', 'Resolution awaiting independent review'), ('resolved', 'Resolution independently accepted')], default='open', max_length=20)),
                ('resolution_note', models.TextField(blank=True)),
                ('resolution_evidence_reference', models.TextField(blank=True)),
                ('resolution_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('last_escalation_note', models.TextField(blank=True)),
                ('last_escalation_at', models.DateTimeField(blank=True, null=True)),
                ('escalation_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comparison', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='defects', to='finance.financeshadowcomparison')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_finance_shadow_defects', to=settings.AUTH_USER_MODEL)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='defects', to='finance.financeshadowcycle')),
                ('last_escalated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='escalated_finance_shadow_defects', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_finance_shadow_defects', to=settings.AUTH_USER_MODEL)),
                ('resolution_submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submitted_finance_shadow_defect_resolutions', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resolved_finance_shadow_defects', to=settings.AUTH_USER_MODEL)),
                ('first_seen_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='first_seen_defects', to='finance.financeshadowreconciliationrun')),
            ],
            options={
                'ordering': ('status', 'correction_due_at', '-severity', 'code'),
            },
        ),
        migrations.AddConstraint(
            model_name='financeshadowreconciliationrun',
            constraint=models.UniqueConstraint(fields=('cycle', 'sequence'), name='unique_shadow_reconciliation_sequence'),
        ),
        migrations.AddConstraint(
            model_name='financeshadowreconciliationrun',
            constraint=models.UniqueConstraint(fields=('cycle', 'scheduled_for'), name='unique_shadow_reconciliation_schedule'),
        ),
        migrations.AddConstraint(
            model_name='financeshadowdefect',
            constraint=models.UniqueConstraint(fields=('cycle', 'code'), name='unique_shadow_defect_code'),
        ),
    ]
