# Generated by Django 5.2.17 on 2026-08-31 04:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_financeshadowreconciliationplan_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceCutoverReadinessPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curriculum_register_reference', models.TextField()),
                ('quick_guides_reference', models.TextField()),
                ('supervisor_runbook_reference', models.TextField()),
                ('support_channels_and_hours', models.TextField()),
                ('support_escalation_procedure', models.TextField()),
                ('local_acceptance_note', models.TextField()),
                ('learning_privacy_notice', models.TextField(default='Floating Internal How-To progress is private, optional learning-state data. It is not training acceptance, performance evidence, or an employee evaluation.', editable=False)),
                ('status', models.CharField(choices=[('draft', 'Draft readiness plan'), ('submitted', 'Awaiting independent approval'), ('approved', 'Approved for this cycle'), ('returned', 'Returned for correction')], default='draft', max_length=16)),
                ('evidence_checksum', models.CharField(blank=True, max_length=64)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_finance_cutover_readiness_plans', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_finance_cutover_readiness_plans', to=settings.AUTH_USER_MODEL)),
                ('cycle', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='cutover_readiness_plan', to='finance.financeshadowcycle')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submitted_finance_cutover_readiness_plans', to=settings.AUTH_USER_MODEL)),
                ('support_owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_finance_cutover_readiness_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='FinanceCutoverReadinessExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('role_training', 'Role curriculum and synthetic job exercise'), ('security_access', 'Security and access-control exercise'), ('privacy', 'Privacy and redaction exercise'), ('accessibility', 'Accessibility and assisted-use exercise'), ('performance', 'Performance and operating-volume exercise'), ('printing', 'Printing, paper, and physical-custody exercise'), ('backup_restore', 'Backup and restore exercise'), ('business_continuity', 'Business-continuity exercise'), ('incident_response', 'Incident and support-escalation exercise')], max_length=24)),
                ('code', models.SlugField(max_length=80)),
                ('title', models.CharField(max_length=200)),
                ('enabled_scope', models.TextField()),
                ('procedure', models.TextField()),
                ('expected_result', models.TextField()),
                ('support_route_snapshot', models.TextField()),
                ('scheduled_for', models.DateTimeField()),
                ('due_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('planned', 'Planned / evidence in progress'), ('submitted', 'Awaiting assigned witness'), ('passed', 'Independently witnessed as passed'), ('returned', 'Returned for correction or rerun')], default='planned', max_length=16)),
                ('actual_result', models.TextField(blank=True)),
                ('evidence_reference', models.TextField(blank=True)),
                ('evidence_checksum', models.CharField(blank=True, max_length=64)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_finance_cutover_readiness_exercises', to=settings.AUTH_USER_MODEL)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cutover_readiness_exercises', to='finance.financeshadowcycle')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_finance_cutover_readiness_exercises', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_finance_cutover_readiness_exercises', to=settings.AUTH_USER_MODEL)),
                ('stakeholder_acceptance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='training_exercises', to='finance.financestakeholderacceptance')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submitted_finance_cutover_readiness_exercises', to=settings.AUTH_USER_MODEL)),
                ('witness', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='witnessed_finance_cutover_readiness_exercises', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exercises', to='finance.financecutoverreadinessplan')),
            ],
            options={
                'ordering': ('kind', 'scheduled_for', 'code'),
                'constraints': [models.UniqueConstraint(fields=('cycle', 'code'), name='unique_cutover_readiness_exercise_code')],
            },
        ),
    ]
