# Generated by Django 5.2.17 on 2026-08-31 05:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0014_financecutoverreadinessplan_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='financecutoverdecision',
            name='signature_custody_reference',
            field=models.TextField(blank=True, default='', help_text='State the TracePoint, records folder, custodian, or other local location of the signed original/copy.'),
        ),
        migrations.AddField(
            model_name='financecutoverdecision',
            name='signed_authority_checksum',
            field=models.CharField(blank=True, default='', help_text='SHA-256 of the retained signed authority record copy.', max_length=64),
        ),
        migrations.AddField(
            model_name='financecutoverdecision',
            name='signed_authority_reference',
            field=models.TextField(blank=True, default='', help_text='Reference the retained signed authority record for this exact scope and planned cutover date.'),
        ),
        migrations.AddField(
            model_name='financestakeholderacceptance',
            name='signed_decision_checksum',
            field=models.CharField(blank=True, help_text='SHA-256 of the retained signed/attributed decision copy.', max_length=64),
        ),
        migrations.AddField(
            model_name='financestakeholderacceptance',
            name='signed_decision_reference',
            field=models.TextField(blank=True, help_text='Reference the retained wet-signed or otherwise locally accepted attributable decision record; do not upload signature images here.'),
        ),
        migrations.CreateModel(
            name='FinanceCutoverQualificationPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum_consecutive_cycles', models.PositiveSmallIntegerField(default=2, help_text='Editable local threshold. Count the candidate cycle and its explicit predecessors; use at least two.')),
                ('require_parallel_cycle', models.BooleanField(default=True, help_text='Keep selected when local acceptance requires at least one controlled parallel run in the qualifying chain.')),
                ('local_authority_reference', models.TextField(help_text='Reference the locally approved pilot/parallel-run direction. Do not treat the starter threshold as a COA or DBM rule.')),
                ('accepted_rules_forms_reference', models.TextField(help_text='Reference the locally accepted rules, forms, print layouts, and instructions used across the qualifying cycles.')),
                ('field_evidence_basis', models.TextField(help_text='State what counts as actual field execution and which retained records prove it.')),
                ('status', models.CharField(choices=[('draft', 'Draft qualification plan'), ('submitted', 'Awaiting independent review'), ('approved', 'Approved for field qualification'), ('returned', 'Returned for correction')], default='draft', max_length=16)),
                ('evidence_checksum', models.CharField(blank=True, max_length=64)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_finance_cutover_qualification_plans', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_finance_cutover_qualification_plans', to=settings.AUTH_USER_MODEL)),
                ('cycle', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='cutover_qualification_plan', to='finance.financeshadowcycle')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submitted_finance_cutover_qualification_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-cycle__fiscal_year', 'cycle__code'),
            },
        ),
        migrations.CreateModel(
            name='FinanceCutoverQualificationEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveSmallIntegerField(help_text='Oldest qualifying cycle is 1; the candidate cutover cycle is the final number.')),
                ('field_execution_reference', models.TextField(help_text='Reference retained records proving this was an actual limited shadow or controlled parallel field cycle.')),
                ('rules_forms_reference', models.TextField(help_text='Reference the accepted local rules, forms, reports, and print layouts actually used in this cycle.')),
                ('evidence_checksum', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('draft', 'Draft field evidence'), ('submitted', 'Awaiting independent review'), ('accepted', 'Accepted qualifying cycle'), ('returned', 'Returned for correction / rerun')], default='draft', max_length=16)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cutover_qualification_evidence', to='finance.financeshadowcycle')),
                ('prepared_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prepared_finance_cutover_qualification_evidence', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_finance_cutover_qualification_evidence', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submitted_finance_cutover_qualification_evidence', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cycle_evidence', to='finance.financecutoverqualificationplan')),
            ],
            options={
                'ordering': ('sequence', 'pk'),
                'constraints': [models.UniqueConstraint(fields=('plan', 'cycle'), name='unique_cutover_qualification_cycle'), models.UniqueConstraint(fields=('plan', 'sequence'), name='unique_cutover_qualification_sequence')],
            },
        ),
    ]
