# Generated by Django 5.2.17 on 2026-09-01 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0015_cutover_cycle_qualification'),
        ('reporting', '0011_financelocalformacceptance_financelocalformevent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financecutoverqualificationevidence',
            name='accepted_forms_checksum',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='financecutoverqualificationevidence',
            name='accepted_forms_snapshot',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='FinanceCutoverQualificationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(default=1)),
                ('use_instructions', models.TextField(help_text='Explain in familiar terms where and how staff use this exact accepted form during the qualifying cycles.')),
                ('form_snapshot', models.JSONField(blank=True, default=dict)),
                ('form_submission_checksum', models.CharField(blank=True, max_length=64)),
                ('form_reference_checksum', models.CharField(blank=True, max_length=64)),
                ('form_source_checksum', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('local_form', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cutover_qualification_uses', to='reporting.financelocalformacceptance')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accepted_forms', to='finance.financecutoverqualificationplan')),
            ],
            options={
                'ordering': ('position', 'pk'),
                'constraints': [models.UniqueConstraint(fields=('plan', 'local_form'), name='unique_cutover_qualification_form'), models.UniqueConstraint(fields=('plan', 'position'), name='unique_cutover_qualification_form_position')],
            },
        ),
    ]
