# Generated by Django 5.2.17 on 2026-09-01 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0016_financecutoverqualificationevidence_accepted_forms_checksum_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceRecoveryRehearsalEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backup_id', models.SlugField(help_text='Exact dated GRAND backup-set directory ID used for this rehearsal.', max_length=80)),
                ('manifest_sha256', models.CharField(max_length=64)),
                ('default_artifact_sha256', models.CharField(max_length=64)),
                ('finance_artifact_sha256', models.CharField(max_length=64)),
                ('off_host_copy_reference', models.TextField()),
                ('off_host_copy_verified', models.BooleanField(default=False)),
                ('preflight_receipt_reference', models.TextField()),
                ('preflight_receipt_checksum', models.CharField(max_length=64)),
                ('preflight_passed', models.BooleanField(default=False)),
                ('policy_reference', models.TextField(help_text='Reference the approved backup, retention, RPO, RTO, and rehearsal procedure.')),
                ('isolated_environment_reference', models.TextField()),
                ('release_reference', models.TextField()),
                ('database_versions', models.TextField()),
                ('restore_log_reference', models.TextField()),
                ('recovery_point_at', models.DateTimeField()),
                ('simulated_interruption_at', models.DateTimeField()),
                ('restored_at', models.DateTimeField()),
                ('approved_rpo_minutes', models.PositiveIntegerField()),
                ('approved_rto_minutes', models.PositiveIntegerField()),
                ('default_store_restored', models.BooleanField(default=False)),
                ('finance_store_restored', models.BooleanField(default=False)),
                ('default_migrations_current', models.BooleanField(default=False)),
                ('finance_migrations_current', models.BooleanField(default=False)),
                ('control_totals_reconciled', models.BooleanField(default=False)),
                ('control_reconciliation_reference', models.TextField()),
                ('control_reconciliation_checksum', models.CharField(max_length=64)),
                ('cross_store_case_verified', models.BooleanField(default=False)),
                ('cross_store_verification_reference', models.TextField()),
                ('cross_store_verification_checksum', models.CharField(max_length=64)),
                ('runtime_files_checked', models.BooleanField(default=False)),
                ('runtime_files_verification_reference', models.TextField()),
                ('secure_disposal_completed', models.BooleanField(default=False)),
                ('secure_disposal_reference', models.TextField()),
                ('unresolved_exceptions', models.BooleanField(default=True)),
                ('exceptions_and_resolution', models.TextField(help_text='Record every exception and resolution, or explicitly state that none occurred.')),
                ('evidence_snapshot', models.JSONField(blank=True, default=dict)),
                ('evidence_checksum', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exercise', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='recovery_rehearsal', to='finance.financecutoverreadinessexercise')),
                ('prepared_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prepared_finance_recovery_rehearsals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-restored_at', '-pk'),
            },
        ),
        migrations.AddField(
            model_name='financecutoverdecision',
            name='recovery_rehearsal',
            field=models.ForeignKey(blank=True, help_text='Choose the independently passed structured recovery rehearsal for this exact cycle.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cutover_decisions', to='finance.financerecoveryrehearsalevidence'),
        ),
    ]
