# Generated by Django 5.2.17 on 2026-09-03 04:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0005_internal_howtos'),
        ('finance', '0017_financerecoveryrehearsalevidence_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceDiscoveryDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.CharField(help_text='Use a stable local reference such as DEC-001.', max_length=40)),
                ('version', models.PositiveIntegerField(default=1)),
                ('phase', models.CharField(choices=[('F0', 'F0'), ('F1', 'F1'), ('F2', 'F2'), ('F3', 'F3'), ('F4', 'F4'), ('F5', 'F5'), ('F6', 'F6'), ('F7', 'F7'), ('F8', 'F8'), ('F9', 'F9'), ('F10', 'F10'), ('F11', 'F11')], default='F0', max_length=4)),
                ('question', models.CharField(max_length=240)),
                ('proposed_outcome', models.TextField(help_text='State the proposed answer or explain why the affected scope must remain unresolved.')),
                ('affected_scope', models.TextField(help_text='Name only the transaction type, office, year, form, output, or action affected by this decision.')),
                ('evidence_label', models.CharField(choices=[('observed_egaps', 'Observed in eGAPS'), ('official_reference', 'Official reference'), ('lgu_confirmed', 'LGU-confirmed'), ('grand_implemented', 'GRAND-implemented'), ('unresolved', 'Unresolved')], default='unresolved', max_length=24)),
                ('authority_evidence_reference', models.TextField(blank=True, help_text='Reference the reviewed issuance, approved local record, observation, or implementation evidence; do not paste confidential content.')),
                ('evidence_needed', models.TextField(help_text='Describe the exact evidence or accountable decision still needed, or state why the supplied evidence is sufficient.')),
                ('evidence_custody_reference', models.TextField(blank=True, help_text='State where the protected evidence is retained without entering credentials or a secret-bearing link.')),
                ('blocks_affected_scope', models.BooleanField(default=True, help_text='Keep selected while this decision prevents only the affected scope from proceeding.')),
                ('due_date', models.DateField(blank=True, null=True)),
                ('change_reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft finding / decision'), ('submitted', 'Awaiting named reviewer'), ('recorded', 'Independently recorded'), ('returned', 'Returned for correction'), ('superseded', 'Superseded by recorded successor')], default='draft', max_length=16)),
                ('evidence_snapshot', models.JSONField(blank=True, default=dict)),
                ('evidence_checksum', models.CharField(blank=True, max_length=64)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_finance_discovery_decisions', to=settings.AUTH_USER_MODEL)),
                ('cycle', models.ForeignKey(blank=True, help_text='Optional: link this decision to the exact shadow/cutover cycle it affects.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='discovery_decisions', to='finance.financeshadowcycle')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finance_discovery_decisions', to='departments.department')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_finance_discovery_decisions', to=settings.AUTH_USER_MODEL)),
                ('predecessor', models.OneToOneField(blank=True, help_text='Recorded decision replaced by this version.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='successor', to='finance.financediscoverydecision')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_finance_discovery_decisions', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_finance_discovery_reviews', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submitted_finance_discovery_decisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('phase', 'code', '-version'),
                'permissions': (('manage_finance_discovery', 'Can prepare Finance discovery findings and decisions'),),
                'constraints': [models.UniqueConstraint(fields=('department', 'code', 'version'), name='unique_finance_discovery_decision_version')],
            },
        ),
    ]
