# Generated by Django 5.2.17 on 2026-09-03 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0018_finance_discovery_decisions'),
    ]

    operations = [
        migrations.AddField(
            model_name='financediscoverydecision',
            name='acceptance_example_reference',
            field=models.TextField(blank=True, help_text='For a coverage row, reference the retained blank/redacted example, replay, control total, or accepted no-case explanation.'),
        ),
        migrations.AddField(
            model_name='financediscoverydecision',
            name='coverage_kind',
            field=models.CharField(choices=[('general', 'General finding / decision'), ('scope_acceptance', 'Whole enabled-scope acceptance'), ('step', 'Process step'), ('field', 'Required field / data'), ('balance', 'Balance / control total'), ('certification', 'Certification / approval'), ('signature', 'Signature / accountable actor'), ('number', 'Official number / identifier'), ('output', 'Form / report / other output'), ('exception', 'Exception / correction path')], default='general', help_text='Choose the part of discovery this row proves. Add as many rows as the local process needs.', max_length=24),
        ),
    ]
