# Generated by Django 5.2.17 on 2026-09-07 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0019_financediscoverydecision_acceptance_example_reference_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='financeauditevent',
            options={'ordering': ('-created_at', '-pk'), 'permissions': (('export_finance_work', 'Can export own currently accessible Finance work'),)},
        ),
    ]
