# Generated by Django 5.2.17 on 2026-09-10 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0021_cash_flow_line_classification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financepostingruleline',
            name='account_source',
            field=models.CharField(choices=[('prior_payable', 'Selected prior payable claim account'), ('allocation_accounts', 'Each voucher allocation account'), ('deduction_mappings', "Each deduction's configured payable account"), ('payable_mapping', "Transaction's configured payable account"), ('bank_mapping', "Payment account's configured bank/cash account"), ('fixed_account', 'One locally confirmed ledger account code')], max_length=28),
        ),
    ]
