# Generated by Django 5.2.17 on 2026-09-15 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0025_advance_applications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financepostingrule',
            name='event_kind',
            field=models.CharField(choices=[('collection', 'Record an actual Treasury collection'), ('deposit', 'Deposit previously recorded collections'), ('cheque_return', 'Record an incoming cheque bank debit'), ('recognition', 'Recognize expense, asset, or payable'), ('adjustment', 'Adjust an earlier recognition'), ('liquidation', 'Record liquidation'), ('payment', 'Settle payable / record payment'), ('remittance', 'Remit deductions or withholdings'), ('cancellation', 'Record cancellation effect'), ('reversal', 'Reverse an earlier entry'), ('replacement', 'Record replacement effect')], max_length=24),
        ),
        migrations.AlterField(
            model_name='financepostingrule',
            name='recognition_point',
            field=models.CharField(choices=[('collection_receipt', 'Actual Treasury receipt'), ('collection_deposit', 'Actual deposit of collections'), ('collection_return', 'Actual bank debit for an incoming cheque'), ('delivery_acceptance', 'Delivery / inspection acceptance'), ('billing_validation', 'Billing or claim validation'), ('dv_validation', 'DV Accounting validation'), ('payment_issuance', 'Check / payment-instrument issuance'), ('payment_release', 'Actual payment release'), ('payment_return', 'Bank-returned payment instrument'), ('payment_cancellation', 'Payment-instrument cancellation'), ('payment_replacement', 'Replacement payment-instrument issuance'), ('deduction_remittance', 'Deduction / withholding remittance'), ('liquidation_acceptance', 'Liquidation acceptance'), ('period_end', 'Period-end review'), ('other', 'Other locally confirmed point')], max_length=32),
        ),
    ]
