# Generated by Django 5.2.17 on 2026-09-15 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0026_alter_financepostingrule_event_kind_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financepostingruleline',
            name='account_source',
            field=models.CharField(choices=[('return_receivable', 'Selected incoming-cheque return receivable'), ('prior_advance', 'Selected original officer advance asset'), ('advance_account', 'Accountable officer advance asset'), ('prior_payable', 'Selected prior payable claim account'), ('allocation_accounts', 'Each voucher allocation account'), ('deduction_mappings', "Each deduction's configured payable account"), ('payable_mapping', "Transaction's configured payable account"), ('bank_mapping', "Payment account's configured bank/cash account"), ('fixed_account', 'One locally confirmed ledger account code')], max_length=28),
        ),
    ]
