# Generated by Django 5.2.17 on 2026-09-15 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0027_alter_financepostingruleline_account_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financepostingruleline',
            name='amount_source',
            field=models.CharField(choices=[('original_cash_component', 'Original cheque amount for this cash-flow purpose'), ('each_allocation', 'Each allocation amount'), ('each_deduction', 'Each deduction amount'), ('gross', 'Voucher gross amount'), ('net', 'Voucher net amount'), ('total_deductions', 'Total deductions'), ('event_amount', 'Current payment / cancellation / replacement / remittance amount')], max_length=24),
        ),
    ]
