# Generated by Django 5.2.17 on 2026-08-16 12:46

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0004_alter_department_dashboard_template_and_more'),
        ('records', '0001_department_records_workflows'),
        ('reporting', '0005_controlled_template_mappers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackedPacket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('tracking_number', models.CharField(db_index=True, max_length=40, unique=True)),
                ('title', models.CharField(max_length=220)),
                ('contents_manifest', models.TextField()),
                ('expected_document_count', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('expected_page_count', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('confidentiality', models.CharField(choices=[('internal', 'Internal'), ('restricted', 'Restricted'), ('confidential', 'Confidential / sensitive contents')], default='internal', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('delivered', 'Delivered'), ('completed', 'Completed'), ('on_hold', 'On hold'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=16)),
                ('state_version', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('current_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_tracepoint_packets', to='departments.department')),
                ('current_holder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='held_tracepoint_packets', to=settings.AUTH_USER_MODEL)),
                ('department_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tracepoint_packets', to='records.departmentrecord')),
                ('final_destination_department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='destination_tracepoint_packets', to='departments.department')),
                ('final_destination_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='destination_tracepoint_packets', to=settings.AUTH_USER_MODEL)),
                ('origin_department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='originated_tracepoint_packets', to='departments.department')),
                ('prepared_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prepared_tracepoint_packets', to=settings.AUTH_USER_MODEL)),
                ('report_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tracepoint_packets', to='reporting.reportrun')),
            ],
            options={
                'ordering': ('-updated_at', '-pk'),
                'permissions': (('view_tracepoint_workspace', 'Can access the TracePoint workspace'), ('prepare_tracked_packets', 'Can prepare tracked physical packets'), ('print_packet_labels', 'Can print TracePoint packet labels'), ('complete_tracked_packets', 'Can complete delivered TracePoint packets'), ('resolve_tracepoint_exceptions', 'Can resolve TracePoint discrepancies and corrections'), ('revoke_employee_credentials', 'Can revoke employee TracePoint credentials'), ('view_restricted_tracepoint', 'Can view restricted TracePoint packets')),
            },
        ),
        migrations.CreateModel(
            name='PacketEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('from_status', models.CharField(blank=True, max_length=16)),
                ('to_status', models.CharField(max_length=16)),
                ('note', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tracepoint_packet_events', to=settings.AUTH_USER_MODEL)),
                ('packet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='tracepoint.trackedpacket')),
            ],
            options={
                'ordering': ('-created_at', '-pk'),
            },
        ),
    ]
