# Generated by Django 5.2.17 on 2026-08-16 12:58

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0004_alter_department_dashboard_template_and_more'),
        ('tracepoint', '0002_dailyemployeecredential_employeecredentialevent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PacketScanSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Waiting for employee code'), ('ready', 'Ready for confirmation'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], db_index=True, default='pending', max_length=12)),
                ('packet_state_version', models.PositiveIntegerField()),
                ('idempotency_key', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('initiated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='initiated_tracepoint_scans', to=settings.AUTH_USER_MODEL)),
                ('packet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scan_sessions', to='tracepoint.trackedpacket')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tracepoint_receipt_scans', to=settings.AUTH_USER_MODEL)),
                ('recipient_credential', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scan_sessions', to='tracepoint.dailyemployeecredential')),
            ],
            options={
                'ordering': ('-created_at', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='PacketHandoff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('idempotency_key', models.CharField(max_length=64, unique=True)),
                ('transfer_type', models.CharField(choices=[('activation', 'Initial activation'), ('receipt', 'Custody receipt')], max_length=12)),
                ('from_employee_name', models.CharField(blank=True, max_length=255)),
                ('from_position_title', models.CharField(blank=True, max_length=100)),
                ('from_department_name', models.CharField(blank=True, max_length=100)),
                ('to_employee_name', models.CharField(max_length=255)),
                ('to_position_title', models.CharField(blank=True, max_length=100)),
                ('to_department_name', models.CharField(max_length=100)),
                ('status_before', models.CharField(max_length=16)),
                ('status_after', models.CharField(max_length=16)),
                ('receipt_note', models.TextField(blank=True)),
                ('confirmed_at', models.DateTimeField(db_index=True)),
                ('confirmed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='confirmed_tracepoint_handoffs', to=settings.AUTH_USER_MODEL)),
                ('from_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tracepoint_handoffs_sent', to='departments.department')),
                ('from_holder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tracepoint_handoffs_sent', to=settings.AUTH_USER_MODEL)),
                ('packet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='handoffs', to='tracepoint.trackedpacket')),
                ('to_department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tracepoint_handoffs_received', to='departments.department')),
                ('to_holder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tracepoint_handoffs_received', to=settings.AUTH_USER_MODEL)),
                ('scan_session', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='handoff', to='tracepoint.packetscansession')),
            ],
            options={
                'ordering': ('sequence', 'pk'),
            },
        ),
        migrations.AddConstraint(
            model_name='packetscansession',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('pending', 'ready'))), fields=('packet',), name='one_open_tracepoint_scan_per_packet'),
        ),
        migrations.AddConstraint(
            model_name='packethandoff',
            constraint=models.UniqueConstraint(fields=('packet', 'sequence'), name='unique_tracepoint_handoff_sequence'),
        ),
    ]
