# Generated by Django 5.2.17 on 2026-08-16 13:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracepoint', '0003_packetscansession_packethandoff_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trackedpacket',
            name='cancellation_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='trackedpacket',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trackedpacket',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='completed_tracepoint_packets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trackedpacket',
            name='held_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trackedpacket',
            name='hold_reason',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='PacketCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prior_holder_name', models.CharField(blank=True, max_length=255)),
                ('corrected_holder_name', models.CharField(max_length=255)),
                ('prior_department_name', models.CharField(blank=True, max_length=100)),
                ('corrected_department_name', models.CharField(max_length=100)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('corrected_holder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tracepoint_corrections_to', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tracepoint_corrections_created', to=settings.AUTH_USER_MODEL)),
                ('packet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='corrections', to='tracepoint.trackedpacket')),
                ('prior_holder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tracepoint_corrections_from', to=settings.AUTH_USER_MODEL)),
                ('related_handoff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='corrections', to='tracepoint.packethandoff')),
            ],
            options={
                'ordering': ('-created_at', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='PacketDiscrepancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('missing_contents', 'Missing contents'), ('wrong_recipient', 'Wrong recipient or route'), ('damaged', 'Damaged packet or contents'), ('other', 'Other discrepancy')], max_length=24)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved')], db_index=True, default='open', max_length=12)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('resolution', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('packet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='discrepancies', to='tracepoint.trackedpacket')),
                ('related_handoff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='discrepancies', to='tracepoint.packethandoff')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reported_tracepoint_discrepancies', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resolved_tracepoint_discrepancies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-reported_at', '-pk'),
            },
        ),
    ]
