# Generated by Django 5.2.17 on 2026-08-20 13:46

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def preserve_historical_terminal_receipts(apps, schema_editor):
    PacketHandoff = apps.get_model('tracepoint', 'PacketHandoff')
    PacketHandoff.objects.filter(status_after='delivered', transfer_type='receipt').update(is_terminal_receipt=True)


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0004_alter_department_dashboard_template_and_more'),
        ('tracepoint', '0004_trackedpacket_cancellation_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='packethandoff',
            name='is_terminal_receipt',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(preserve_historical_terminal_receipts, migrations.RunPython.noop),
        migrations.AddField(
            model_name='trackedpacket',
            name='parent_packet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='split_packets', to='tracepoint.trackedpacket'),
        ),
        migrations.CreateModel(
            name='PacketItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('reference_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('title', models.CharField(max_length=220)),
                ('description', models.TextField(blank=True)),
                ('expected_attachment_count', models.PositiveIntegerField(default=0)),
                ('expected_page_count', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_tracepoint_items', to=settings.AUTH_USER_MODEL)),
                ('current_packet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='voucher_items', to='tracepoint.trackedpacket')),
                ('origin_packet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='originated_items', to='tracepoint.trackedpacket')),
            ],
            options={
                'ordering': ('reference_number', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='PacketItemMove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('registered', 'Registered in bundle'), ('split', 'Split into child packet'), ('rebundled', 'Moved between packets')], max_length=12)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tracepoint_item_moves', to=settings.AUTH_USER_MODEL)),
                ('from_packet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='item_moves_out', to='tracepoint.trackedpacket')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='moves', to='tracepoint.packetitem')),
                ('to_packet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='item_moves_in', to='tracepoint.trackedpacket')),
            ],
            options={
                'ordering': ('created_at', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='PacketCheckpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('purpose', models.CharField(choices=[('review', 'Review'), ('signature', 'Signature'), ('approval', 'Approval'), ('certification', 'Certification'), ('release', 'Release / routing'), ('other', 'Other')], max_length=16)),
                ('label', models.CharField(max_length=160)),
                ('instructions', models.TextField(blank=True)),
                ('required', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('skipped', 'Skipped by exception resolver')], db_index=True, default='pending', max_length=12)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('skipped_at', models.DateTimeField(blank=True, null=True)),
                ('skip_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='completed_tracepoint_checkpoints', to=settings.AUTH_USER_MODEL)),
                ('completed_handoff', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='completed_checkpoint', to='tracepoint.packethandoff')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tracepoint_checkpoints', to='departments.department')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tracepoint_checkpoints', to=settings.AUTH_USER_MODEL)),
                ('packet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checkpoints', to='tracepoint.trackedpacket')),
                ('skipped_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='skipped_tracepoint_checkpoints', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('sequence', 'pk'),
                'constraints': [models.UniqueConstraint(fields=('packet', 'sequence'), name='unique_tracepoint_checkpoint_sequence')],
            },
        ),
    ]
