from django.urls import path

from . import views


app_name = "accounting"

urlpatterns = [
    path("", views.workspace, name="workspace"),
    path("setup/", views.setup_workspace, name="setup"),
    path("setup/export/", views.foundation_register_export, name="foundation_register_export"),
    path("setup/releases/<int:pk>/adopt/", views.configuration_release_adopt, name="release_adopt"),
    path("setup/fiscal-years/<int:pk>/<slug:action>/", views.fiscal_year_transition, name="fiscal_year_transition"),
    path("setup/readiness/<int:pk>/<slug:decision>/", views.readiness_decision, name="readiness_decision"),
    path("setup/<slug:kind>/new/", views.setup_item_create, name="setup_create"),
    path("setup/<slug:kind>/<int:pk>/edit/", views.setup_item_edit, name="setup_edit"),
    path("setup/<slug:kind>/<int:pk>/toggle/", views.setup_item_toggle, name="setup_toggle"),
    path("setup/periods/<int:pk>/close/", views.period_close, name="period_close"),
    path("period-close/", views.period_close_workspace, name="period_close_workspace"),
    path("period-close/new/", views.period_close_create, name="period_close_create"),
    path("period-close/<uuid:public_id>/", views.period_close_detail, name="period_close_detail"),
    path("period-close/<uuid:public_id>/edit/", views.period_close_edit, name="period_close_edit"),
    path("period-close/<uuid:public_id>/submit/", views.period_close_submit, name="period_close_submit"),
    path("period-close/<uuid:public_id>/decide/<slug:decision>/", views.period_close_decide, name="period_close_decide"),
    path("period-close/<uuid:public_id>/reopen/", views.period_close_reopen_request, name="period_close_reopen_request"),
    path("period-close/<uuid:public_id>/reopen/<slug:decision>/", views.period_close_reopen_decide, name="period_close_reopen_decide"),
    path("period-close/<uuid:public_id>/export/", views.period_close_export, name="period_close_export"),
    path("period-close/policies/new/", views.period_close_policy_create, name="period_close_policy_create"),
    path("period-close/policies/<uuid:public_id>/", views.period_close_policy_detail, name="period_close_policy_detail"),
    path("period-close/policies/<uuid:public_id>/edit/", views.period_close_policy_edit, name="period_close_policy_edit"),
    path("period-close/policies/<uuid:public_id>/submit/", views.period_close_policy_submit, name="period_close_policy_submit"),
    path("period-close/policies/<uuid:public_id>/decide/<slug:decision>/", views.period_close_policy_decide, name="period_close_policy_decide"),
    path("opening/", views.opening_workspace, name="opening_workspace"),
    path("opening/export/", views.opening_register_export, name="opening_register_export"),
    path("opening/starter.csv", views.opening_starter, name="opening_starter"),
    path("opening/new/", views.opening_create, name="opening_create"),
    path("opening/<uuid:public_id>/", views.opening_detail, name="opening_detail"),
    path("opening/<uuid:public_id>/export/", views.opening_export, name="opening_export"),
    path("opening/<uuid:public_id>/edit/", views.opening_edit, name="opening_edit"),
    path("opening/<uuid:public_id>/stage/", views.opening_stage, name="opening_stage"),
    path("opening/<uuid:public_id>/validate/", views.opening_validate, name="opening_validate"),
    path("opening/<uuid:public_id>/submit/", views.opening_submit, name="opening_submit"),
    path("opening/<uuid:public_id>/decide/<slug:decision>/", views.opening_decide, name="opening_decide"),
    path("opening/<uuid:public_id>/post/", views.opening_post, name="opening_post"),
    path("opening/<uuid:public_id>/reconcile/", views.opening_reconcile, name="opening_reconcile"),
    path("opening/<uuid:public_id>/rows/<int:pk>/edit/", views.opening_row_edit, name="opening_row_edit"),
    path("bank-reconciliation/", views.bank_reconciliation_workspace, name="bank_reconciliation_workspace"),
    path("bank-reconciliation/starter.csv", views.bank_reconciliation_starter, name="bank_reconciliation_starter"),
    path("bank-reconciliation/new/", views.bank_reconciliation_create, name="bank_reconciliation_create"),
    path("bank-reconciliation/<uuid:public_id>/", views.bank_reconciliation_detail, name="bank_reconciliation_detail"),
    path("bank-reconciliation/<uuid:public_id>/edit/", views.bank_reconciliation_edit, name="bank_reconciliation_edit"),
    path("bank-reconciliation/<uuid:public_id>/stage/", views.bank_reconciliation_stage, name="bank_reconciliation_stage"),
    path("bank-reconciliation/<uuid:public_id>/validate/", views.bank_reconciliation_validate, name="bank_reconciliation_validate"),
    path("bank-reconciliation/<uuid:public_id>/auto-match/", views.bank_reconciliation_auto_match, name="bank_reconciliation_auto_match"),
    path("bank-reconciliation/<uuid:public_id>/carry-forward/", views.bank_reconciliation_carry_forward, name="bank_reconciliation_carry_forward"),
    path("bank-reconciliation/<uuid:public_id>/rows/<int:row_id>/match/", views.bank_reconciliation_match, name="bank_reconciliation_match"),
    path("bank-reconciliation/<uuid:public_id>/rows/<int:row_id>/unmatch/", views.bank_reconciliation_unmatch, name="bank_reconciliation_unmatch"),
    path("bank-reconciliation/<uuid:public_id>/classify/", views.bank_reconciliation_classify, name="bank_reconciliation_classify"),
    path("bank-reconciliation/<uuid:public_id>/ledger/<int:line_id>/unclassify/", views.bank_reconciliation_unclassify, name="bank_reconciliation_unclassify"),
    path("bank-reconciliation/<uuid:public_id>/submit/", views.bank_reconciliation_submit, name="bank_reconciliation_submit"),
    path("bank-reconciliation/<uuid:public_id>/decide/<slug:decision>/", views.bank_reconciliation_decide, name="bank_reconciliation_decide"),
    path("bank-reconciliation/<uuid:public_id>/export/", views.bank_reconciliation_export, name="bank_reconciliation_export"),
    path("journals/new/", views.entry_create, name="entry_create"),
    path("journals/<uuid:public_id>/", views.entry_detail, name="entry_detail"),
    path("journals/<uuid:public_id>/edit/", views.entry_edit, name="entry_edit"),
    path("journals/<uuid:public_id>/lines/new/", views.line_create, name="line_create"),
    path("journals/<uuid:public_id>/lines/<int:pk>/edit/", views.line_edit, name="line_edit"),
    path("journals/<uuid:public_id>/lines/<int:pk>/delete/", views.line_delete, name="line_delete"),
    path("journals/<uuid:public_id>/submit/", views.entry_submit, name="entry_submit"),
    path("journals/<uuid:public_id>/post/", views.entry_post, name="entry_post"),
    path("journals/<uuid:public_id>/return/", views.entry_return, name="entry_return"),
    path("journals/<uuid:public_id>/discard/", views.entry_discard, name="entry_discard"),
    path("journals/<uuid:public_id>/reverse/", views.entry_reverse, name="entry_reverse"),
    path("sources/vouchers/<uuid:public_id>/materialize/", views.voucher_source_materialize, name="voucher_source_materialize"),
    path("sources/vouchers/<uuid:public_id>/reconcile/", views.voucher_source_reconcile, name="voucher_source_reconcile"),
    path("sources/remittances/<uuid:public_id>/materialize/", views.remittance_source_materialize, name="remittance_source_materialize"),
    path("sources/remittances/<uuid:public_id>/reconcile/", views.remittance_source_reconcile, name="remittance_source_reconcile"),
    path("ledger/", views.ledger, name="ledger"),
    path("ledger/export/", views.ledger_export, name="ledger_export"),
    path("trial-balance/", views.trial_balance, name="trial_balance"),
    path("trial-balance/export/", views.trial_balance_export, name="trial_balance_export"),
    path("subsidiary-controls/", views.subsidiary_controls, name="subsidiary_controls"),
    path("subsidiary-controls/reconcile/", views.subsidiary_reconcile, name="subsidiary_reconcile"),
    path("subsidiary-controls/<slug:category>/export/", views.subsidiary_export, name="subsidiary_export"),
    path(
        "subsidiary-controls/reconciliations/<uuid:public_id>/export/",
        views.subsidiary_reconciliation_export,
        name="subsidiary_reconciliation_export",
    ),
]
