# Generated by Django 5.2.2 on 2025-06-06 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JO_Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_title', models.CharField(blank=True, max_length=100, null=True)),
                ('daily_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'JO Salary',
                'verbose_name_plural': 'JO Salaries',
            },
        ),
        migrations.CreateModel(
            name='EmployeeSalaryDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rice_allowance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('hazard_pay', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('other_allowances', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('other_deductions', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='salary_details', to='profiles.employeeprofile')),
            ],
        ),
        migrations.CreateModel(
            name='RegOrCT_Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.PositiveIntegerField()),
                ('step', models.PositiveIntegerField(default=1)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('effective_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'RegOrCT Salary',
                'verbose_name_plural': 'RegOrCT Salaries',
                'unique_together': {('grade', 'step')},
            },
        ),
    ]
