from django.urls import path

from . import views

app_name = "finance"

urlpatterns = [
    path("", views.workspace, name="workspace"),
    path("discovery/", views.discovery_workspace, name="discovery_workspace"),
    path("discovery/new/", views.discovery_decision_create, name="discovery_decision_create"),
    path("discovery/coverage-starters/", views.discovery_coverage_starters, name="discovery_coverage_starters"),
    path("discovery/export/", views.discovery_register_export, name="discovery_register_export"),
    path("discovery/<uuid:public_id>/", views.discovery_decision_detail, name="discovery_decision_detail"),
    path("discovery/<uuid:public_id>/edit/", views.discovery_decision_edit, name="discovery_decision_edit"),
    path("discovery/<uuid:public_id>/successor/", views.discovery_decision_successor, name="discovery_decision_successor"),
    path("discovery/<uuid:public_id>/export/", views.discovery_decision_export, name="discovery_decision_export"),
    path("discovery/<uuid:public_id>/<slug:action>/", views.discovery_decision_action, name="discovery_decision_action"),
    path("releases/new/", views.release_create, name="release_create"),
    path("releases/<int:pk>/", views.release_detail, name="release_detail"),
    path("releases/<int:pk>/<slug:action>/", views.release_action, name="release_action"),
    path("items/new/", views.item_create, name="item_create"),
    path("tax-rules/new/", views.tax_rule_create, name="tax_rule_create"),
    path("variants/new/", views.variant_create, name="variant_create"),
    path("document-rules/new/", views.document_rule_create, name="document_rule_create"),
    path("posting-rules/new/", views.posting_rule_create, name="posting_rule_create"),
    path("posting-rule-lines/new/", views.posting_rule_line_create, name="posting_rule_line_create"),
    path("variants/<int:variant_pk>/posting-starter/", views.posting_rule_starter, name="posting_rule_starter"),
    path(
        "variants/<int:variant_pk>/payment-posting-starters/",
        views.payment_posting_starters,
        name="payment_posting_starters",
    ),
    path("signatories/new/", views.signatory_create, name="signatory_create"),
    path("parties/new/", views.party_create, name="party_create"),
    path("parties/<int:party_pk>/claimants/new/", views.claimant_create, name="claimant_create"),
    path("sequences/new/", views.sequence_create, name="sequence_create"),
    path("templates/new/", views.template_create, name="template_create"),
    path("templates/starter/", views.starter_template, name="starter_template"),
    path("templates/<int:pk>/preflight/", views.template_preflight, name="template_preflight"),
    path("templates/<int:pk>/download/", views.template_download, name="template_download"),
    path("templates/<int:pk>/synthetic-preview/", views.template_preview, name="template_preview"),
    path("shadow-cutover/", views.shadow_workspace, name="shadow_workspace"),
    path("field-acceptance/", views.field_acceptance_board, name="field_acceptance_board"),
    path("field-acceptance/export/", views.field_acceptance_board_export, name="field_acceptance_board_export"),
    path("shadow-cutover/cycles/new/", views.shadow_cycle_create, name="shadow_cycle_create"),
    path("shadow-cutover/cycles/<int:pk>/", views.shadow_cycle_detail, name="shadow_cycle_detail"),
    path("shadow-cutover/cycles/<int:pk>/export/", views.shadow_cycle_export, name="shadow_cycle_export"),
    path("shadow-cutover/cycles/<int:cycle_pk>/sources/upload/", views.shadow_source_upload, name="shadow_source_upload"),
    path("shadow-cutover/cycles/<int:cycle_pk>/sources/external-lock/", views.shadow_external_lock, name="shadow_external_lock"),
    path("shadow-cutover/sources/<int:pk>/drift-review/", views.shadow_source_drift_review, name="shadow_source_drift_review"),
    path("shadow-cutover/cycles/<int:cycle_pk>/reconciliation-plan/", views.shadow_reconciliation_plan, name="shadow_reconciliation_plan"),
    path("shadow-cutover/reconciliation-plans/<int:pk>/<slug:action>/", views.shadow_reconciliation_plan_action, name="shadow_reconciliation_plan_action"),
    path("shadow-cutover/cycles/<int:cycle_pk>/readiness-plan/", views.cutover_readiness_plan, name="cutover_readiness_plan"),
    path("shadow-cutover/readiness-plans/<int:pk>/<slug:action>/", views.cutover_readiness_plan_action, name="cutover_readiness_plan_action"),
    path("shadow-cutover/cycles/<int:cycle_pk>/readiness-exercises/new/", views.cutover_readiness_exercise_create, name="cutover_readiness_exercise_create"),
    path("shadow-cutover/readiness-exercises/<int:pk>/result/", views.cutover_readiness_exercise_result, name="cutover_readiness_exercise_result"),
    path("shadow-cutover/readiness-exercises/<int:pk>/<slug:action>/", views.cutover_readiness_exercise_action, name="cutover_readiness_exercise_action"),
    path("shadow-cutover/cycles/<int:cycle_pk>/qualification-plan/", views.cutover_qualification_plan, name="cutover_qualification_plan"),
    path("shadow-cutover/qualification-plans/<int:pk>/forms/new/", views.cutover_qualification_form_create, name="cutover_qualification_form_create"),
    path("shadow-cutover/qualification-plans/<int:pk>/forms/<int:row_pk>/delete/", views.cutover_qualification_form_delete, name="cutover_qualification_form_delete"),
    path("shadow-cutover/qualification-plans/<int:pk>/<slug:action>/", views.cutover_qualification_plan_action, name="cutover_qualification_plan_action"),
    path("shadow-cutover/cycles/<int:cycle_pk>/qualification-evidence/new/", views.cutover_qualification_evidence_create, name="cutover_qualification_evidence_create"),
    path("shadow-cutover/qualification-evidence/<int:pk>/<slug:action>/", views.cutover_qualification_evidence_action, name="cutover_qualification_evidence_action"),
    path("shadow-cutover/cycles/<int:cycle_pk>/reconciliation-runs/open/", views.shadow_reconciliation_run_open, name="shadow_reconciliation_run_open"),
    path("shadow-cutover/reconciliation-runs/<int:pk>/<slug:action>/", views.shadow_reconciliation_run_action, name="shadow_reconciliation_run_action"),
    path("shadow-cutover/cycles/<int:cycle_pk>/defects/new/", views.shadow_defect_create, name="shadow_defect_create"),
    path("shadow-cutover/defects/<int:pk>/resolution/", views.shadow_defect_resolution, name="shadow_defect_resolution"),
    path("shadow-cutover/defects/<int:pk>/<slug:action>/", views.shadow_defect_action, name="shadow_defect_action"),
    path("shadow-cutover/cycles/<int:cycle_pk>/comparisons/new/", views.shadow_comparison_create, name="shadow_comparison_create"),
    path("shadow-cutover/cycles/<int:cycle_pk>/stakeholders/new/", views.stakeholder_acceptance_create, name="stakeholder_acceptance_create"),
    path("shadow-cutover/stakeholders/<int:pk>/decision/", views.stakeholder_acceptance_decide, name="stakeholder_acceptance_decide"),
    path("shadow-cutover/cycles/<int:cycle_pk>/decision/new/", views.cutover_decision_create, name="cutover_decision_create"),
    path("shadow-cutover/decisions/<int:pk>/<slug:action>/", views.cutover_decision_action, name="cutover_decision_action"),
    path("shadow-cutover/cycles/<int:pk>/<slug:action>/", views.shadow_cycle_action, name="shadow_cycle_action"),
]
