# Generated by Django 5.2.17 on 2026-08-14 12:20

import django.core.validators
import django.db.models.deletion
import reporting.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0004_alter_department_dashboard_template_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('slug', models.SlugField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('dataset_key', models.CharField(max_length=80)),
                ('selected_fields', models.JSONField(default=list)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('group_by', models.JSONField(blank=True, default=list)),
                ('totals', models.JSONField(blank=True, default=list)),
                ('sort_by', models.JSONField(blank=True, default=list)),
                ('default_format', models.CharField(choices=[('pdf', 'PDF'), ('xlsx', 'Excel workbook'), ('csv', 'CSV')], default='pdf', max_length=8)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_report_definitions', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report_definitions', to='departments.department')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updated_report_definitions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
                'permissions': (('view_reporting_workspace', 'Can access the department reporting workspace'), ('manage_report_definitions', 'Can configure report definitions'), ('manage_report_templates', 'Can manage official report templates'), ('schedule_reports', 'Can schedule recurring reports'), ('generate_reports', 'Can generate department reports'), ('review_reports', 'Can review generated reports'), ('approve_reports', 'Can approve official reports'), ('download_reports', 'Can download generated reports'), ('view_department_reports', 'Can view all reports in the assigned department')),
            },
        ),
        migrations.CreateModel(
            name='ReportRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('idempotency_key', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('generated', 'Generated'), ('reviewed', 'Reviewed'), ('approved', 'Approved'), ('failed', 'Failed'), ('superseded', 'Superseded')], db_index=True, default='draft', max_length=12)),
                ('output_format', models.CharField(choices=[('pdf', 'PDF'), ('xlsx', 'Excel workbook'), ('csv', 'CSV')], max_length=8)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('parameters', models.JSONField(default=dict)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('output_file', models.FileField(blank=True, upload_to=reporting.models.report_output_path)),
                ('checksum', models.CharField(blank=True, max_length=64)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='official_report_runs', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_report_runs', to=settings.AUTH_USER_MODEL)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='reporting.reportdefinition')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_report_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ReportRunEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=40)),
                ('from_status', models.CharField(blank=True, max_length=12)),
                ('to_status', models.CharField(max_length=12)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report_run_events', to=settings.AUTH_USER_MODEL)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='reporting.reportrun')),
            ],
            options={
                'ordering': ('-created_at', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='ReportSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annual', 'Annual')], max_length=12)),
                ('output_format', models.CharField(choices=[('pdf', 'PDF'), ('xlsx', 'Excel workbook'), ('csv', 'CSV')], max_length=8)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('next_run_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_report_schedules', to=settings.AUTH_USER_MODEL)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='reporting.reportdefinition')),
            ],
            options={
                'ordering': ('next_run_at', 'name'),
            },
        ),
        migrations.AddField(
            model_name='reportrun',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='reporting.reportschedule'),
        ),
        migrations.CreateModel(
            name='ReportTemplateVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=180)),
                ('header_text', models.CharField(blank=True, max_length=255)),
                ('certification_text', models.TextField(blank=True)),
                ('footer_text', models.CharField(blank=True, max_length=255)),
                ('document_control_prefix', models.CharField(blank=True, max_length=30)),
                ('signatories', models.JSONField(blank=True, default=list)),
                ('layout_config', models.JSONField(blank=True, default=dict)),
                ('reference_kind', models.CharField(choices=[('none', 'No uploaded reference'), ('pdf', 'PDF form or layout'), ('xlsx', 'Spreadsheet layout'), ('docx', 'Word document layout'), ('image', 'Scanned or image reference')], default='none', max_length=12)),
                ('reference_file', models.FileField(blank=True, help_text='Stored as a non-executable reference. Mapping and approval are required before official use.', upload_to=reporting.models.report_reference_path, validators=[django.core.validators.FileExtensionValidator(('pdf', 'xlsx', 'xls', 'docx', 'png', 'jpg', 'jpeg'))])),
                ('mapping_notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_report_templates', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_report_templates', to=settings.AUTH_USER_MODEL)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_versions', to='reporting.reportdefinition')),
            ],
            options={
                'ordering': ('definition', '-version'),
            },
        ),
        migrations.AddField(
            model_name='reportschedule',
            name='template_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to='reporting.reporttemplateversion'),
        ),
        migrations.AddField(
            model_name='reportrun',
            name='template_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='reporting.reporttemplateversion'),
        ),
        migrations.AddConstraint(
            model_name='reportdefinition',
            constraint=models.UniqueConstraint(fields=('department', 'slug'), name='unique_report_slug_per_department'),
        ),
        migrations.AddConstraint(
            model_name='reporttemplateversion',
            constraint=models.UniqueConstraint(fields=('definition', 'version'), name='unique_report_template_version'),
        ),
    ]
