# Generated by Django 5.2.17 on 2026-08-14 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportrun',
            name='parameters',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
