# Generated by Django 5.2.17 on 2026-08-14 12:28

import django.core.validators
import reporting.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0002_alter_reportrun_parameters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportrun',
            name='output_file',
            field=models.FileField(blank=True, max_length=500, upload_to=reporting.models.report_output_path),
        ),
        migrations.AlterField(
            model_name='reporttemplateversion',
            name='reference_file',
            field=models.FileField(blank=True, help_text='Stored as a non-executable reference. Mapping and approval are required before official use.', max_length=500, upload_to=reporting.models.report_reference_path, validators=[django.core.validators.FileExtensionValidator(('pdf', 'xlsx', 'xls', 'docx', 'png', 'jpg', 'jpeg'))]),
        ),
    ]
