# Generated by Django 5.2.17 on 2026-08-15 06:34

import django.core.validators
import django.db.models.deletion
import reporting.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0003_alter_reportrun_output_file_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reporttemplateversion',
            name='fidelity_notes',
            field=models.TextField(blank=True, help_text='Record the department comparison, governing form, and sign-off basis.'),
        ),
        migrations.AddField(
            model_name='reporttemplateversion',
            name='fidelity_status',
            field=models.CharField(choices=[('pilot', 'Pilot - internal comparison only'), ('official', 'Department-validated official layout')], default='pilot', max_length=12),
        ),
        migrations.AddField(
            model_name='reporttemplateversion',
            name='fidelity_validated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reporttemplateversion',
            name='fidelity_validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='validated_report_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reporttemplateversion',
            name='margin_mm',
            field=models.PositiveSmallIntegerField(default=14, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(30)]),
        ),
        migrations.AddField(
            model_name='reporttemplateversion',
            name='orientation',
            field=models.CharField(choices=[('portrait', 'Portrait'), ('landscape', 'Landscape')], default='landscape', max_length=10),
        ),
        migrations.AddField(
            model_name='reporttemplateversion',
            name='page_border',
            field=models.CharField(choices=[('none', 'No page border'), ('single', 'Single page border')], default='single', max_length=10),
        ),
        migrations.AddField(
            model_name='reporttemplateversion',
            name='page_size',
            field=models.CharField(choices=[('a4', 'A4'), ('letter', 'Letter'), ('legal', 'Legal')], default='a4', max_length=10),
        ),
        migrations.AddField(
            model_name='reporttemplateversion',
            name='primary_logo',
            field=models.ImageField(blank=True, max_length=500, upload_to=reporting.models.report_identity_path, validators=[django.core.validators.FileExtensionValidator(('png', 'jpg', 'jpeg'))]),
        ),
        migrations.AddField(
            model_name='reporttemplateversion',
            name='repeat_header',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='reporttemplateversion',
            name='secondary_logo',
            field=models.ImageField(blank=True, max_length=500, upload_to=reporting.models.report_identity_path, validators=[django.core.validators.FileExtensionValidator(('png', 'jpg', 'jpeg'))]),
        ),
        migrations.AddField(
            model_name='reporttemplateversion',
            name='show_document_control',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='reporttemplateversion',
            name='show_footer',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='reporttemplateversion',
            name='show_page_numbers',
            field=models.BooleanField(default=True),
        ),
    ]
