# Generated by Django 5.2.17 on 2026-08-15 09:57

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0004_template_fidelity_controls'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reporttemplateversion',
            name='mapping_checksum',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='reporttemplateversion',
            name='mapping_summary',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='reporttemplateversion',
            name='mapping_validated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reporttemplateversion',
            name='mapping_validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='preflighted_report_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reporttemplateversion',
            name='render_mode',
            field=models.CharField(choices=[('native', 'Native GRAND layout'), ('xlsx_template', 'Mapped Excel workbook'), ('pdf_overlay', 'Exact PDF overlay')], default='native', max_length=20),
        ),
        migrations.CreateModel(
            name='ReportTemplateMappingField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_key', models.CharField(max_length=100)),
                ('page_number', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('x_mm', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(500)])),
                ('y_mm', models.DecimalField(decimal_places=2, help_text='Distance from the top edge of the page.', max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(500)])),
                ('width_mm', models.DecimalField(decimal_places=2, default=60, max_digits=6, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(500)])),
                ('font_size', models.DecimalField(decimal_places=1, default=9, max_digits=4, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(24)])),
                ('alignment', models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='left', max_length=8)),
                ('repeat_for_rows', models.BooleanField(default=False)),
                ('row_height_mm', models.DecimalField(decimal_places=2, default=5, max_digits=5, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(30)])),
                ('max_rows', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(500)])),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('template_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overlay_fields', to='reporting.reporttemplateversion')),
            ],
            options={
                'ordering': ('page_number', 'display_order', 'pk'),
            },
        ),
    ]
