# Generated by Django 5.2.17 on 2026-08-31 01:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0005_internal_howtos'),
        ('reporting', '0006_finance_accountability_evidence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceStatementMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('statement_type', models.CharField(choices=[('position', 'Management statement of financial position'), ('performance', 'Management statement of financial performance')], max_length=16)),
                ('version', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Editable draft'), ('submitted', 'For independent review'), ('returned', 'Returned for correction'), ('starter', 'Controlled management starter'), ('active', 'Locally accepted active mapping'), ('superseded', 'Superseded mapping')], default='draft', max_length=16)),
                ('authority_reference', models.TextField(blank=True)),
                ('local_acceptance_note', models.TextField(blank=True)),
                ('snapshot_checksum', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_finance_statement_mappings', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finance_statement_mappings', to='departments.department')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_finance_statement_mappings', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submitted_finance_statement_mappings', to=settings.AUTH_USER_MODEL)),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='successors', to='reporting.financestatementmapping')),
            ],
            options={
                'ordering': ('statement_type', '-version'),
            },
        ),
        migrations.CreateModel(
            name='FinanceStatementLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField()),
                ('section_code', models.SlugField(max_length=60)),
                ('section_title', models.CharField(max_length=160)),
                ('line_code', models.SlugField(max_length=60)),
                ('line_title', models.CharField(max_length=180)),
                ('selector_type', models.CharField(choices=[('account_type', 'All accounts of one type'), ('account_codes', 'Selected account codes')], max_length=20)),
                ('account_type', models.CharField(blank=True, choices=[('', 'Choose when using account type'), ('asset', 'Asset'), ('liability', 'Liability'), ('equity', 'Equity'), ('revenue', 'Revenue'), ('expense', 'Expense')], max_length=16)),
                ('account_codes', models.JSONField(blank=True, default=list)),
                ('mapping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='reporting.financestatementmapping')),
            ],
            options={
                'ordering': ('position', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='FinanceStatementMappingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=60)),
                ('reason', models.TextField(blank=True)),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finance_statement_mapping_events', to=settings.AUTH_USER_MODEL)),
                ('mapping', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='reporting.financestatementmapping')),
            ],
            options={
                'ordering': ('-created_at', '-pk'),
            },
        ),
        migrations.AddConstraint(
            model_name='financestatementmapping',
            constraint=models.UniqueConstraint(fields=('department', 'statement_type', 'version'), name='unique_finance_statement_mapping_version'),
        ),
        migrations.AddConstraint(
            model_name='financestatementmapping',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('department', 'statement_type'), name='one_active_finance_statement_mapping'),
        ),
        migrations.AddConstraint(
            model_name='financestatementline',
            constraint=models.UniqueConstraint(fields=('mapping', 'position'), name='unique_statement_line_position'),
        ),
        migrations.AddConstraint(
            model_name='financestatementline',
            constraint=models.UniqueConstraint(fields=('mapping', 'line_code'), name='unique_statement_line_code'),
        ),
    ]
