# Generated by Django 5.2.17 on 2026-08-31 03:00

import django.core.validators
import django.db.models.deletion
import reporting.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0005_internal_howtos'),
        ('reporting', '0007_financestatementmapping_financestatementline_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceStatementNoteSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(default='Notes to the financial statements', max_length=200)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('version', models.PositiveIntegerField()),
                ('applicability_status', models.CharField(choices=[('candidate', 'Controlled candidate — local acceptance pending'), ('confirmed', 'Locally confirmed statement-note package')], default='candidate', max_length=12)),
                ('status', models.CharField(choices=[('draft', 'Editable draft'), ('submitted', 'For independent review'), ('returned', 'Returned for correction'), ('reviewed', 'Controlled working notes'), ('approved', 'Locally accepted notes'), ('superseded', 'Superseded notes')], default='draft', max_length=16)),
                ('preparation_note', models.TextField(blank=True)),
                ('authority_reference', models.TextField(blank=True)),
                ('local_acceptance_note', models.TextField(blank=True)),
                ('source_snapshot', models.JSONField(blank=True, default=dict)),
                ('snapshot_checksum', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_finance_statement_note_sets', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finance_statement_note_sets', to='departments.department')),
                ('performance_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='performance_note_sets', to='reporting.reportrun')),
                ('position_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='position_note_sets', to='reporting.reportrun')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_finance_statement_note_sets', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submitted_finance_statement_note_sets', to=settings.AUTH_USER_MODEL)),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='successors', to='reporting.financestatementnoteset')),
            ],
            options={
                'ordering': ('-period_end', '-version'),
                'permissions': (('prepare_statement_notes', 'Can prepare financial statement notes'), ('review_statement_notes', 'Can independently review financial statement notes'), ('export_statement_packages', 'Can export statement notes and comparison evidence')),
            },
        ),
        migrations.CreateModel(
            name='FinanceStatementNoteEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=60)),
                ('reason', models.TextField(blank=True)),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finance_statement_note_events', to=settings.AUTH_USER_MODEL)),
                ('note_set', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='reporting.financestatementnoteset')),
            ],
            options={
                'ordering': ('-created_at', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='FinanceStatementNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField()),
                ('topic_code', models.SlugField(max_length=80)),
                ('title', models.CharField(max_length=200)),
                ('related_statement', models.CharField(choices=[('general', 'General disclosure'), ('position', 'Statement of financial position'), ('performance', 'Statement of financial performance'), ('both', 'Both statements')], default='general', max_length=16)),
                ('related_line_codes', models.JSONField(blank=True, default=list)),
                ('disclosure_text', models.TextField(blank=True)),
                ('source_reference', models.TextField(blank=True)),
                ('authority_basis', models.TextField(blank=True)),
                ('is_not_applicable', models.BooleanField(default=False)),
                ('not_applicable_reason', models.TextField(blank=True)),
                ('note_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='reporting.financestatementnoteset')),
            ],
            options={
                'ordering': ('position', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='ReportReferenceComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('version', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('draft', 'Editable comparison'), ('submitted', 'For independent review'), ('returned', 'Returned for correction'), ('reconciled', 'Exact controls independently reconciled'), ('superseded', 'Superseded comparison')], default='draft', max_length=16)),
                ('reference_label', models.CharField(max_length=200)),
                ('reference_kind', models.CharField(choices=[('pdf', 'PDF reference'), ('xlsx', 'Excel reference'), ('image', 'Scanned or image reference')], max_length=12)),
                ('reference_file', models.FileField(help_text='Upload only the approved redacted comparison copy; GRAND never executes its contents.', max_length=500, upload_to=reporting.models.statement_reference_path, validators=[django.core.validators.FileExtensionValidator(('pdf', 'xlsx', 'png', 'jpg', 'jpeg'))])),
                ('signed_copy', models.BooleanField(default=False)),
                ('redaction_confirmed', models.BooleanField(default=False)),
                ('authority_reference', models.TextField(blank=True)),
                ('local_acceptance_note', models.TextField(blank=True)),
                ('reference_values', models.JSONField(blank=True, default=dict)),
                ('generated_values_snapshot', models.JSONField(blank=True, default=dict)),
                ('differences', models.JSONField(blank=True, default=dict)),
                ('comparison_result', models.CharField(choices=[('pending', 'Not calculated'), ('reconciled', 'Exact agreement'), ('exception', 'Difference requires resolution')], default='pending', max_length=16)),
                ('run_evidence_snapshot', models.JSONField(blank=True, default=dict)),
                ('reference_file_checksum', models.CharField(blank=True, max_length=64)),
                ('snapshot_checksum', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_report_reference_comparisons', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_report_reference_comparisons', to=settings.AUTH_USER_MODEL)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reference_comparisons', to='reporting.reportrun')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submitted_report_reference_comparisons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'permissions': (('prepare_reference_comparisons', 'Can prepare signed report reference comparisons'), ('review_reference_comparisons', 'Can independently review signed report reference comparisons')),
            },
        ),
        migrations.CreateModel(
            name='ReportReferenceComparisonEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=60)),
                ('reason', models.TextField(blank=True)),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report_reference_comparison_events', to=settings.AUTH_USER_MODEL)),
                ('comparison', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='reporting.reportreferencecomparison')),
            ],
            options={
                'ordering': ('-created_at', '-pk'),
            },
        ),
        migrations.AddConstraint(
            model_name='financestatementnoteset',
            constraint=models.UniqueConstraint(fields=('department', 'period_start', 'period_end', 'version'), name='unique_statement_note_set_version'),
        ),
        migrations.AddConstraint(
            model_name='financestatementnoteset',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'approved')), fields=('department', 'period_start', 'period_end'), name='one_approved_statement_note_set'),
        ),
        migrations.AddConstraint(
            model_name='financestatementnote',
            constraint=models.UniqueConstraint(fields=('note_set', 'position'), name='unique_statement_note_position'),
        ),
        migrations.AddConstraint(
            model_name='financestatementnote',
            constraint=models.UniqueConstraint(fields=('note_set', 'topic_code'), name='unique_statement_note_topic'),
        ),
        migrations.AddConstraint(
            model_name='reportreferencecomparison',
            constraint=models.UniqueConstraint(fields=('run', 'version'), name='unique_report_reference_comparison_version'),
        ),
    ]
