# Generated by Django 5.2.17 on 2026-08-31 03:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0008_financestatementnoteset_financestatementnoteevent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportdefinition',
            options={'ordering': ('name',), 'permissions': (('view_reporting_workspace', 'Can access the department reporting workspace'), ('manage_report_definitions', 'Can configure report definitions'), ('manage_report_templates', 'Can manage official report templates'), ('schedule_reports', 'Can schedule recurring reports'), ('generate_reports', 'Can generate department reports'), ('review_reports', 'Can review generated reports'), ('approve_reports', 'Can approve official reports'), ('download_reports', 'Can download generated reports'), ('view_department_reports', 'Can view all reports in the assigned department'), ('prepare_template_promotions', 'Can prepare report template promotion requests'), ('approve_template_promotions', 'Can independently approve report template promotions'), ('activate_template_promotions', 'Can activate or roll back approved report templates'))},
        ),
        migrations.CreateModel(
            name='ReportTemplatePromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Editable promotion request'), ('submitted', 'For independent approval'), ('returned', 'Returned for correction'), ('approved', 'Approved, awaiting activation'), ('activated', 'Active official template'), ('rolled_back', 'Rolled back to prior template')], default='draft', max_length=16)),
                ('change_reason', models.TextField()),
                ('comparison_note', models.TextField(help_text='Plain-language side-by-side check, retained form, signatory, printer, and overflow evidence.')),
                ('update_compatible_schedules', models.BooleanField(default=False)),
                ('template_snapshot', models.JSONField(default=dict)),
                ('template_checksum', models.CharField(max_length=64)),
                ('mapping_diff', models.JSONField(default=list)),
                ('impact_snapshot', models.JSONField(default=dict)),
                ('golden_result', models.CharField(choices=[('pending', 'Preview not compared'), ('matched', 'Golden run data and controls match'), ('reference_review', 'First-layout reference review required'), ('exception', 'Preview comparison has differences')], default='pending', max_length=20)),
                ('golden_snapshot', models.JSONField(default=dict)),
                ('submission_checksum', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('rolled_back_at', models.DateTimeField(blank=True, null=True)),
                ('rollback_reason', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activated_report_template_promotions', to=settings.AUTH_USER_MODEL)),
                ('baseline_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='template_promotion_baselines', to='reporting.reportrun')),
                ('baseline_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='successor_promotion_requests', to='reporting.reporttemplateversion')),
                ('candidate_template', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='promotion_request', to='reporting.reporttemplateversion')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_report_template_promotions', to=settings.AUTH_USER_MODEL)),
                ('preview_run', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='template_promotion_preview', to='reporting.reportrun')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_report_template_promotions', to=settings.AUTH_USER_MODEL)),
                ('rolled_back_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rolled_back_report_template_promotions', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submitted_report_template_promotions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ReportTemplatePromotionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=60)),
                ('reason', models.TextField(blank=True)),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report_template_promotion_events', to=settings.AUTH_USER_MODEL)),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='reporting.reporttemplatepromotion')),
            ],
            options={
                'ordering': ('-created_at', '-pk'),
            },
        ),
    ]
