# Generated by Django 5.2.17 on 2026-08-31 07:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0005_internal_howtos'),
        ('reporting', '0009_alter_reportdefinition_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceAccountabilityPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Editable draft'), ('submitted', 'For independent review'), ('returned', 'Returned for correction'), ('approved', 'Approved accountability package'), ('superseded', 'Superseded package')], default='draft', max_length=16)),
                ('preparation_note', models.TextField(blank=True)),
                ('profile_snapshot', models.JSONField(default=dict)),
                ('profile_checksum', models.CharField(max_length=64)),
                ('package_snapshot', models.JSONField(blank=True, default=dict)),
                ('package_checksum', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_finance_accountability_packages', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finance_accountability_packages', to='departments.department')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_finance_accountability_packages', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submitted_finance_accountability_packages', to=settings.AUTH_USER_MODEL)),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='successor_packages', to='reporting.financeaccountabilitypackage')),
            ],
            options={
                'ordering': ('-period_end', 'profile__code', '-version'),
            },
        ),
        migrations.CreateModel(
            name='FinanceAccountabilityPackageEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=60)),
                ('reason', models.TextField(blank=True)),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finance_accountability_package_events', to=settings.AUTH_USER_MODEL)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='reporting.financeaccountabilitypackage')),
            ],
            options={
                'ordering': ('-created_at', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='FinanceAccountabilityPackageProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.SlugField(max_length=80)),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('name', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Editable draft'), ('submitted', 'For independent review'), ('returned', 'Returned for correction'), ('active', 'Active package profile'), ('superseded', 'Superseded profile')], default='draft', max_length=16)),
                ('authority_reference', models.TextField(blank=True, help_text='Plain-language COA, DBM, BIR, ordinance, memorandum, or accepted local-procedure basis.')),
                ('local_acceptance_note', models.TextField(blank=True, help_text='Record the office and person who accepted this package recipe and where its evidence is retained.')),
                ('snapshot_checksum', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_finance_accountability_package_profiles', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finance_accountability_package_profiles', to='departments.department')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_finance_accountability_package_profiles', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submitted_finance_accountability_package_profiles', to=settings.AUTH_USER_MODEL)),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='successor_profiles', to='reporting.financeaccountabilitypackageprofile')),
            ],
            options={
                'ordering': ('code', '-version'),
                'permissions': (('manage_accountability_package_profiles', 'Can prepare Finance accountability package profiles'), ('approve_accountability_package_profiles', 'Can independently approve Finance accountability package profiles'), ('prepare_accountability_packages', 'Can prepare Finance accountability packages'), ('review_accountability_packages', 'Can independently review Finance accountability packages'), ('export_accountability_packages', 'Can export approved Finance accountability packages')),
            },
        ),
        migrations.AddField(
            model_name='financeaccountabilitypackage',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packages', to='reporting.financeaccountabilitypackageprofile'),
        ),
        migrations.CreateModel(
            name='FinanceAccountabilityPackageProfileEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=60)),
                ('reason', models.TextField(blank=True)),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finance_accountability_package_profile_events', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='reporting.financeaccountabilitypackageprofile')),
            ],
            options={
                'ordering': ('-created_at', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='FinanceAccountabilityPackageRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField()),
                ('code', models.SlugField(max_length=80)),
                ('label', models.CharField(max_length=180)),
                ('evidence_kind', models.CharField(choices=[('report_run', 'Approved GRAND report'), ('statement_notes', 'Approved financial-statement notes'), ('signed_reference', 'Reconciled signed-reference comparison'), ('tax_filing', 'Verified tax-filing evidence')], max_length=24)),
                ('tax_form_code', models.CharField(blank=True, max_length=40)),
                ('required', models.BooleanField(default=True)),
                ('instructions', models.TextField(blank=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requirements', to='reporting.financeaccountabilitypackageprofile')),
                ('report_definition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_accountability_requirements', to='reporting.reportdefinition')),
                ('source_department', models.ForeignKey(help_text='Office responsible for the approved source output.', on_delete=django.db.models.deletion.PROTECT, related_name='finance_accountability_source_requirements', to='departments.department')),
            ],
            options={
                'ordering': ('position', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='FinanceAccountabilityPackageSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField()),
                ('code', models.SlugField(max_length=80)),
                ('label', models.CharField(max_length=180)),
                ('evidence_kind', models.CharField(choices=[('report_run', 'Approved GRAND report'), ('statement_notes', 'Approved financial-statement notes'), ('signed_reference', 'Reconciled signed-reference comparison'), ('tax_filing', 'Verified tax-filing evidence')], max_length=24)),
                ('source_department_label', models.CharField(max_length=160)),
                ('report_definition_label', models.CharField(blank=True, max_length=180)),
                ('tax_form_code', models.CharField(blank=True, max_length=40)),
                ('required', models.BooleanField(default=True)),
                ('instructions', models.TextField(blank=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='slots', to='reporting.financeaccountabilitypackage')),
                ('report_definition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_accountability_package_slots', to='reporting.reportdefinition')),
                ('source_department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finance_accountability_package_slots', to='departments.department')),
            ],
            options={
                'ordering': ('position', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='FinanceAccountabilityPackageSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('current', 'Current selection'), ('superseded', 'Superseded selection')], default='current', max_length=12)),
                ('source_public_id', models.UUIDField()),
                ('source_label', models.CharField(max_length=240)),
                ('source_snapshot', models.JSONField(default=dict)),
                ('source_checksum', models.CharField(max_length=64)),
                ('change_reason', models.TextField(blank=True)),
                ('selected_at', models.DateTimeField(auto_now_add=True)),
                ('selected_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finance_accountability_package_selections', to=settings.AUTH_USER_MODEL)),
                ('supersedes', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='successor', to='reporting.financeaccountabilitypackageselection')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='selections', to='reporting.financeaccountabilitypackageslot')),
            ],
            options={
                'ordering': ('slot', '-version'),
            },
        ),
        migrations.AddConstraint(
            model_name='financeaccountabilitypackageprofile',
            constraint=models.UniqueConstraint(fields=('department', 'code', 'version'), name='unique_accountability_profile_version'),
        ),
        migrations.AddConstraint(
            model_name='financeaccountabilitypackageprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('department', 'code'), name='one_active_accountability_profile'),
        ),
        migrations.AddConstraint(
            model_name='financeaccountabilitypackage',
            constraint=models.UniqueConstraint(fields=('department', 'profile', 'period_start', 'period_end', 'version'), name='unique_accountability_package_version'),
        ),
        migrations.AddConstraint(
            model_name='financeaccountabilitypackage',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'approved')), fields=('department', 'profile', 'period_start', 'period_end'), name='one_approved_accountability_package'),
        ),
        migrations.AddConstraint(
            model_name='financeaccountabilitypackagerequirement',
            constraint=models.UniqueConstraint(fields=('profile', 'position'), name='unique_accountability_requirement_position'),
        ),
        migrations.AddConstraint(
            model_name='financeaccountabilitypackagerequirement',
            constraint=models.UniqueConstraint(fields=('profile', 'code'), name='unique_accountability_requirement_code'),
        ),
        migrations.AddConstraint(
            model_name='financeaccountabilitypackageslot',
            constraint=models.UniqueConstraint(fields=('package', 'position'), name='unique_accountability_slot_position'),
        ),
        migrations.AddConstraint(
            model_name='financeaccountabilitypackageslot',
            constraint=models.UniqueConstraint(fields=('package', 'code'), name='unique_accountability_slot_code'),
        ),
        migrations.AddConstraint(
            model_name='financeaccountabilitypackageselection',
            constraint=models.UniqueConstraint(fields=('slot', 'version'), name='unique_accountability_selection_version'),
        ),
        migrations.AddConstraint(
            model_name='financeaccountabilitypackageselection',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'current')), fields=('slot',), name='one_current_accountability_selection'),
        ),
    ]
