# Generated by Django 5.2.17 on 2026-08-31 14:03

import django.core.validators
import django.db.models.deletion
import reporting.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0005_internal_howtos'),
        ('finance', '0015_cutover_cycle_qualification'),
        ('reporting', '0010_financeaccountabilitypackage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceLocalFormAcceptance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.SlugField(max_length=80)),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('name', models.CharField(max_length=180)),
                ('form_number', models.CharField(blank=True, help_text='Use the familiar official or local form number only when the office has verified it.', max_length=120)),
                ('purpose', models.TextField()),
                ('source_type', models.CharField(choices=[('unmapped', 'Inventory only — GRAND mapping still required'), ('report_template', 'Governed report template'), ('finance_workbook', 'Governed Finance workbook')], default='unmapped', max_length=24)),
                ('status', models.CharField(choices=[('draft', 'Editable local-form record'), ('submitted', 'For independent acceptance review'), ('returned', 'Returned for correction'), ('accepted', 'Locally accepted form'), ('superseded', 'Superseded local form')], default='draft', max_length=16)),
                ('authority_reference', models.TextField(blank=True, help_text='Current COA, DBM, BIR, bank, ordinance, memorandum, or accepted local-procedure basis.')),
                ('local_acceptance_note', models.TextField(blank=True, help_text='Name the accepting office/person and the retained decision or comparison record.')),
                ('reference_kind', models.CharField(choices=[('pdf', 'PDF blank or redacted sample'), ('xlsx', 'Macro-free Excel blank or redacted sample'), ('docx', 'Word blank or redacted sample'), ('image', 'Scanned/image reference')], default='pdf', max_length=12)),
                ('reference_file', models.FileField(help_text='Upload only a blank or safely redacted reference up to 10 MB.', max_length=500, upload_to=reporting.models.local_form_reference_path, validators=[django.core.validators.FileExtensionValidator(('pdf', 'xlsx', 'xls', 'docx', 'png', 'jpg', 'jpeg'))])),
                ('reference_checksum', models.CharField(blank=True, max_length=64)),
                ('delivery_mode', models.CharField(choices=[('digital', 'Digital file only'), ('print', 'Printed or pre-printed form'), ('both', 'Digital file and printed copy')], default='both', max_length=12)),
                ('signatory_instructions', models.TextField(help_text='List the required signatory roles, order, acting/delegation rule, and wet/digital signature treatment.')),
                ('default_copy_count', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)])),
                ('recipient_instructions', models.TextField(help_text='State who receives each copy or digital file and how acknowledgement is retained.')),
                ('deadline_instructions', models.TextField(help_text='State the locally confirmed preparation, submission, filing, or distribution deadline basis.')),
                ('retention_instructions', models.TextField(help_text='State the records folder, custodian, retention rule, and confidential-copy handling.')),
                ('paper_size', models.CharField(blank=True, help_text='For example A4, Letter, Legal, or the exact pre-printed stock description.', max_length=20)),
                ('orientation', models.CharField(blank=True, help_text='For example Portrait or Landscape.', max_length=20)),
                ('form_stock', models.TextField(blank=True)),
                ('printer_instructions', models.TextField(blank=True)),
                ('pagination_instructions', models.TextField(help_text='Describe page numbering, repeating headings, annexes, and continuation-page treatment.')),
                ('overflow_instructions', models.TextField(help_text='Describe what happens when rows, particulars, notes, or signatures do not fit.')),
                ('accessibility_instructions', models.TextField(help_text='Describe readable labels/order, download format, scaling, and any accessibility accommodation.')),
                ('source_snapshot', models.JSONField(blank=True, default=dict)),
                ('source_checksum', models.CharField(blank=True, max_length=64)),
                ('submission_snapshot', models.JSONField(blank=True, default=dict)),
                ('submission_checksum', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_finance_local_form_acceptances', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finance_local_form_acceptances', to='departments.department')),
                ('finance_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='local_form_acceptance_records', to='finance.financetemplateversion')),
                ('report_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='local_form_acceptance_records', to='reporting.reporttemplateversion')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_finance_local_form_acceptances', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submitted_finance_local_form_acceptances', to=settings.AUTH_USER_MODEL)),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='successor_forms', to='reporting.financelocalformacceptance')),
            ],
            options={
                'ordering': ('code', '-version'),
                'permissions': (('manage_local_form_acceptance', 'Can prepare local Finance form acceptance records'), ('witness_local_form_tests', 'Can independently witness local Finance form tests'), ('review_local_form_acceptance', 'Can independently accept local Finance forms'), ('export_local_form_acceptance', 'Can export accepted local Finance form evidence')),
            },
        ),
        migrations.CreateModel(
            name='FinanceLocalFormEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=60)),
                ('reason', models.TextField(blank=True)),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finance_local_form_events', to=settings.AUTH_USER_MODEL)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='reporting.financelocalformacceptance')),
            ],
            options={
                'ordering': ('-created_at', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='FinanceLocalFormSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField()),
                ('code', models.SlugField(max_length=80)),
                ('label', models.CharField(max_length=180)),
                ('requirement_type', models.CharField(choices=[('required', 'Required section'), ('optional', 'Optional section'), ('conditional', 'Conditional section'), ('repeating', 'Repeating rows or continuation section')], default='required', max_length=16)),
                ('applicability_instructions', models.TextField(blank=True, help_text='For optional or conditional sections, state who decides and what retained fact makes the section apply.')),
                ('row_instructions', models.TextField(blank=True, help_text='For repeating content, state the minimum/maximum rows and continuation-page behavior.')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sections', to='reporting.financelocalformacceptance')),
            ],
            options={
                'ordering': ('position', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='FinanceLocalFormTestAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('data_control', 'Data and control totals'), ('layout_fields', 'Labels, fields, and visual comparison'), ('signatory_route', 'Signatories, copies, recipients, and custody route'), ('overflow_pagination', 'Overflow, pagination, and continuation pages'), ('access_download', 'Accessibility, download, and readable output'), ('printer_stock', 'Physical printer and form-stock trial'), ('rollback_recovery', 'Rollback and recoverable prior-version drill')], max_length=24)),
                ('attempt', models.PositiveSmallIntegerField(default=1)),
                ('change_reason', models.TextField(blank=True)),
                ('test_steps', models.TextField()),
                ('expected_result', models.TextField()),
                ('observed_result', models.TextField()),
                ('environment', models.TextField(help_text='Name the browser/device, output format, printer/paper when applicable, and useful settings.')),
                ('evidence_reference', models.TextField(help_text='Reference the retained redacted output, comparison sheet, print sample, screenshot, or drill record.')),
                ('evidence_checksum', models.CharField(max_length=64)),
                ('basis_snapshot', models.JSONField(default=dict)),
                ('basis_checksum', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('submitted', 'Awaiting independent witness'), ('passed', 'Witnessed pass'), ('failed', 'Witnessed failure — new attempt required'), ('not_applicable', 'Witnessed not applicable')], default='submitted', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_finance_local_form_tests', to=settings.AUTH_USER_MODEL)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='test_attempts', to='reporting.financelocalformacceptance')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_finance_local_form_tests', to=settings.AUTH_USER_MODEL)),
                ('supersedes', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='successor_attempt', to='reporting.financelocalformtestattempt')),
            ],
            options={
                'ordering': ('category', '-attempt'),
            },
        ),
        migrations.AddConstraint(
            model_name='financelocalformacceptance',
            constraint=models.UniqueConstraint(fields=('department', 'code', 'version'), name='unique_local_form_acceptance_version'),
        ),
        migrations.AddConstraint(
            model_name='financelocalformacceptance',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'accepted')), fields=('department', 'code'), name='one_accepted_local_form_version'),
        ),
        migrations.AddConstraint(
            model_name='financelocalformsection',
            constraint=models.UniqueConstraint(fields=('form', 'position'), name='unique_local_form_section_position'),
        ),
        migrations.AddConstraint(
            model_name='financelocalformsection',
            constraint=models.UniqueConstraint(fields=('form', 'code'), name='unique_local_form_section_code'),
        ),
        migrations.AddConstraint(
            model_name='financelocalformtestattempt',
            constraint=models.UniqueConstraint(fields=('form', 'category', 'attempt'), name='unique_local_form_test_attempt'),
        ),
    ]
