# Generated by Django 5.2.17 on 2026-09-10 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0012_local_form_candidate_starters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financestatementmapping',
            name='statement_type',
            field=models.CharField(choices=[('position', 'Management statement of financial position'), ('performance', 'Management statement of financial performance'), ('cash_flow', 'Cash flow - reviewed cash and cash-equivalent accounts')], max_length=16),
        ),
    ]
