# Generated by Django 5.2.17 on 2026-09-10 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0013_cash_flow_account_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='financestatementnoteset',
            name='cash_flow_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cash_flow_note_sets', to='reporting.reportrun'),
        ),
        migrations.AddField(
            model_name='financestatementnoteset',
            name='net_assets_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='net_assets_note_sets', to='reporting.reportrun'),
        ),
        migrations.AlterField(
            model_name='financestatementnote',
            name='related_statement',
            field=models.CharField(choices=[('general', 'General disclosure'), ('position', 'Statement of financial position'), ('performance', 'Statement of financial performance'), ('both', 'Both statements'), ('net_assets', 'Statement of changes in net assets / equity'), ('cash_flow', 'Statement of cash flows')], default='general', max_length=16),
        ),
    ]
