# Generated by Django 5.2.17 on 2026-09-10 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0014_complete_statement_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='financestatementnoteset',
            name='bundle_checksum',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='financestatementnoteset',
            name='bundle_file',
            field=models.FileField(blank=True, upload_to='reports/statement-packages/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='financestatementnoteset',
            name='bundled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
