# Generated by Django 5.2.2 on 2025-06-09 10:48

import assistance.models
import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistanceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Description')),
                ('requirements', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Requirements')),
                ('sample_image', models.ImageField(blank=True, null=True, upload_to=assistance.models.sample_upload_path)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssistanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_code', models.CharField(max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('review', 'Under Review'), ('approved', 'Approved'), ('denied', 'Denied')], default='pending', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('assistance_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assistance.assistancetype')),
            ],
        ),
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status_before', models.CharField(max_length=20)),
                ('status_after', models.CharField(max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='assistance.assistancerequest')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
