# Generated by Django 5.2 on 2025-06-13 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistance', '0002_assistancerequest_edit_code_requestdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestdocument',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='requestdocument',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('clearer_copy', 'Needs a Clearer Copy'), ('wrong_file', 'Wrong File Attached'), ('incomplete', 'Incomplete Document'), ('missing_stamp', 'Requires Official Stamp/Signature'), ('expired', 'Obsolete/Expired Document')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='requestdocument',
            name='file',
            field=models.FileField(upload_to='assistance_docs/'),
        ),
    ]
