# Generated by Django 5.2 on 2025-06-13 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistance', '0003_requestdocument_remarks_requestdocument_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistancerequest',
            name='period',
            field=models.CharField(blank=True, help_text='e.g., 2024–2025', max_length=9),
        ),
    ]
