# Generated by Django 5.2 on 2025-06-13 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistance', '0004_assistancerequest_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistancerequest',
            name='phone',
            field=models.CharField(help_text='Pure #s only. e.g., 09123456789', max_length=20),
        ),
    ]
