# Generated by Django 5.2 on 2025-06-16 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistance', '0005_alter_assistancerequest_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistancerequest',
            name='period',
            field=models.CharField(blank=True, help_text='e.g., 2024–2025', max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='assistancerequest',
            name='phone',
            field=models.CharField(help_text='#s only: 09123456789', max_length=20),
        ),
    ]
