# Generated by Django 5.2 on 2025-06-17 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistance', '0006_alter_assistancerequest_period_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistancerequest',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assistancerequest',
            name='claimed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assistancerequest',
            name='semester',
            field=models.CharField(blank=True, choices=[('1st', '1st Semester'), ('2nd', '2nd Semester'), ('summer', 'Midyear / Summer')], help_text='Optional: for educational assistance', max_length=10, null=True),
        ),
    ]
