# Generated by Django 5.2 on 2025-06-26 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistance', '0008_requestlog_action_type_alter_requestlog_remarks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistancerequest',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
