# Generated by Django 5.2 on 2026-08-09.

from django.conf import settings
from django.db import migrations, models
from django.db.models import Max, Count
import django.db.models.deletion


def _normalize_email(value):
    return (value or "").strip().lower()


def _normalize_phone(value):
    return (value or "").strip()


def create_profiles_and_link_requests(apps, schema_editor):
    AssistanceRequest = apps.get_model("assistance", "AssistanceRequest")
    CitizenProfile = apps.get_model("assistance", "CitizenProfile")

    for request in AssistanceRequest.objects.iterator():
        phone = _normalize_phone(request.phone)
        email = _normalize_email(request.email)

        profile = None
        if phone:
            profile = CitizenProfile.objects.filter(phone=phone).first()
        if not profile and email:
            profile = CitizenProfile.objects.filter(email=email).first()
        if not profile:
            profile = CitizenProfile.objects.create(
                full_name=request.full_name,
                email=email,
                phone=phone,
                total_requests=0,
                last_request_at=request.submitted_at,
            )
        else:
            if not profile.full_name:
                profile.full_name = request.full_name
            if not profile.email and email:
                profile.email = email
            if not profile.phone and phone:
                profile.phone = phone
            profile.save(update_fields=["full_name", "email", "phone", "updated_at"])

        request.citizen_id = profile.pk
        request.save(update_fields=["citizen_id"])

    aggregated = (
        AssistanceRequest.objects.values("citizen_id")
        .annotate(total=Count("id"), last_request=Max("submitted_at"))
    )
    for row in aggregated:
        CitizenProfile.objects.filter(pk=row["citizen_id"]).update(
            total_requests=row["total"],
            last_request_at=row["last_request"],
        )


def remove_profiles_links(apps, schema_editor):
    AssistanceRequest = apps.get_model("assistance", "AssistanceRequest")
    AssistanceRequest.objects.update(citizen_id=None)


class Migration(migrations.Migration):

    dependencies = [
        ("assistance", "0010_requestdocument_document_type_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CitizenProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("full_name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, db_index=True)),
                ("phone", models.CharField(max_length=20, db_index=True)),
                ("total_requests", models.PositiveIntegerField(default=0)),
                ("last_request_at", models.DateTimeField(blank=True, null=True)),
                ("risk_level", models.CharField(
                    choices=[
                        ("normal", "Normal"),
                        ("frequent", "Frequent Requester"),
                        ("priority", "Priority Assistance"),
                        ("flagged", "Flagged for Review"),
                    ],
                    default="normal",
                    help_text="Future classification: normal, frequent, priority, flagged",
                    max_length=20,
                )),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name="assistancetype",
            name="slug",
            field=models.SlugField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="assistancetype",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True, blank=True),
        ),
        migrations.AddField(
            model_name="requestdocument",
            name="is_removed",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="requestdocument",
            name="removed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="requestdocument",
            name="replacement_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="assistancerequest",
            name="citizen",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="assistance.citizenprofile",
                related_name="requests",
            ),
        ),
        migrations.CreateModel(
            name="RequestTimeline",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("event_type", models.CharField(max_length=50)),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
                ),
                (
                    "request",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="timeline", to="assistance.assistancerequest"),
                ),
            ],
        ),
        migrations.RunPython(
            create_profiles_and_link_requests,
            reverse_code=remove_profiles_links,
        ),
    ]
