# Generated by Django 5.2 on 2026-08-09 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistance', '0011_assistance_tracepoint_compat'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistanceProgram',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('assistance.assistancetype',),
        ),
        migrations.CreateModel(
            name='CitizenRequest',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('assistance.assistancerequest',),
        ),
        migrations.AlterField(
            model_name='assistancerequest',
            name='period',
            field=models.CharField(blank=True, help_text='e.g., 2024-2025', max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='assistancerequest',
            name='reference_code',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='assistancerequest',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('pending', 'Pending'), ('review', 'Under Review'), ('approved', 'Approved'), ('denied', 'Denied')], default='submitted', max_length=20),
        ),
    ]
