# Generated by Django 5.2.17 on 2026-08-14 11:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def normalize_existing_citizen_profiles(apps, schema_editor):
    CitizenProfile = apps.get_model("assistance", "CitizenProfile")
    AssistanceRequest = apps.get_model("assistance", "AssistanceRequest")
    for profile in CitizenProfile.objects.iterator():
        linked_requests = AssistanceRequest.objects.filter(citizen_id=profile.pk)
        latest = linked_requests.order_by("-submitted_at").values_list("submitted_at", flat=True).first()
        CitizenProfile.objects.filter(pk=profile.pk).update(
            public_id=profile.public_id or uuid.uuid4(),
            normalized_email=(profile.email or "").strip().casefold(),
            normalized_phone="".join(
                character for character in (profile.phone or "") if character.isdigit()
            ),
            total_requests=linked_requests.count(),
            last_request_at=latest,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('assistance', '0012_assistanceprogram_citizenrequest_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='citizenprofile',
            options={'permissions': (('view_citizen_review_workspace', 'Can access the citizen review workspace'), ('review_citizen_profiles', 'Can review citizen profiles'), ('view_citizen_profile_pii', 'Can view citizen profile personal information'), ('export_citizen_profiles', 'Can export citizen profile information'))},
        ),
        migrations.RenameField(
            model_name='citizenprofile',
            old_name='notes',
            new_name='review_notes',
        ),
        migrations.RemoveField(
            model_name='citizenprofile',
            name='risk_level',
        ),
        migrations.AddField(
            model_name='citizenprofile',
            name='assigned_reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_citizen_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='citizenprofile',
            name='normalized_email',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=254),
        ),
        migrations.AddField(
            model_name='citizenprofile',
            name='normalized_phone',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=20),
        ),
        migrations.AddField(
            model_name='citizenprofile',
            name='review_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='citizenprofile',
            name='review_status',
            field=models.CharField(choices=[('unreviewed', 'Not yet reviewed'), ('in_review', 'In review'), ('verified', 'Reviewed and verified'), ('needs_update', 'Needs information update')], db_index=True, default='unreviewed', max_length=20),
        ),
        migrations.AddField(
            model_name='citizenprofile',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='citizenprofile',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_citizen_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='citizenprofile',
            name='public_id',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.RunPython(normalize_existing_citizen_profiles, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='citizenprofile',
            name='public_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.CreateModel(
            name='CitizenReviewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(blank=True, max_length=20)),
                ('new_status', models.CharField(blank=True, max_length=20)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citizen_review_actions', to=settings.AUTH_USER_MODEL)),
                ('new_reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citizen_review_reassignments_to', to=settings.AUTH_USER_MODEL)),
                ('previous_reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citizen_review_reassignments_from', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_logs', to='assistance.citizenprofile')),
            ],
            options={
                'ordering': ('-created_at', '-pk'),
            },
        ),
    ]
