# Generated by Django 5.2.2 on 2025-06-06 12:28

import django_ckeditor_5.fields
import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('announcement_type', models.CharField(blank=True, choices=[('Public', 'Public - for the general masses'), ('Internal', 'Internal - for employees only')], default='Public', help_text='Select the type of announcement. Public is for everyone, Internal is for employees only', max_length=20, verbose_name='Type: ')),
                ('is_pinned', models.BooleanField(default=False, help_text='Indicates if the announcement is pinned.', verbose_name='Pinned')),
                ('published', models.BooleanField(default=True)),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Content')),
                ('slug', models.SlugField(blank=True, default='', unique=True)),
                ('cover_image', models.ImageField(blank=True, default='defaults/jjv.png', upload_to=home.models.Announcement.upload_directory_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('motto', django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='Text')),
                ('landline', models.CharField(blank=True, help_text='Landline number of the department. Ex: 044-123-4567', max_length=255, null=True)),
                ('mobile', models.CharField(blank=True, help_text='Mobile number of the department. Ex: 0912-345-6789', max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, unique=True)),
                ('messenger_chat_link', models.CharField(help_text="Your Page's username or profile url here. Ex: tepong32 ", max_length=255, null=True)),
                ('image', models.ImageField(blank=True, default='defaults/jjvbocaue-otimized.png', upload_to=home.models.DepartmentContact.upload_directory_path)),
            ],
        ),
        migrations.CreateModel(
            name='DownloadableForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ('file', models.FileField(upload_to='forms/')),
                ('uploaded_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrgPersonnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(default=' ', help_text='Either Titles or add OIC, your call.', max_length=255)),
                ('image', models.ImageField(blank=True, default='defaults/jjvbocaue-otimized.png', upload_to=home.models.OrgPersonnel.upload_directory_path)),
                ('display_order', models.PositiveIntegerField(blank=True, help_text='Mayor as 1, VM as 2, etc.', null=True)),
            ],
        ),
    ]
