# Generated by Django 5.1 on 2024-12-26 08:19

from django_ckeditor_5.fields import CKEditor5Field
import django.db.models.deletion
import home.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('annnouncement_type', models.CharField(blank=True, choices=[('Public', 'Public - for the general masses'), ('Internal', 'Internal - for employees only'), ('Pinned', 'Pinned - will be set to the Pinned section, apart from other announcements')], default='Public', help_text='Select the type of announcement. Public is for everyone, Internal is for employees only, and Pinned will be highlighted separately.', max_length=20, verbose_name='Type: ')),
                ('content', CKEditor5Field('Text', config_name='extends')),
                ('slug', models.SlugField(blank=True, default='')),
                ('cover_image', models.ImageField(blank=True, default='defaults/jjv.png', upload_to=home.models.Announcement.upload_directory_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
