# Generated by Django 5.2.17 on 2026-08-14 10:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceShortcut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=240)),
                ('icon_class', models.CharField(default='fas fa-arrow-right', help_text='Font Awesome icon class, for example: fas fa-bullhorn', max_length=50, validators=[django.core.validators.RegexValidator(message="Use a Font Awesome class such as 'fas fa-hands-helping'.", regex='^fa[srb]? fa-[a-z0-9-]+$')])),
                ('link_url', models.CharField(help_text='A local path such as /assistance/ or an approved https:// address.', max_length=255)),
                ('link_label', models.CharField(default='Open service', max_length=60)),
                ('audience', models.CharField(choices=[('public', 'Public'), ('employee', 'Employees')], default='public', max_length=12)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('display_order', 'title'),
            },
        ),
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(default='GRAND', max_length=60)),
                ('institution_name', models.CharField(default='Municipality of Bocaue', max_length=160)),
                ('portal_label', models.CharField(default='Official Digital Services Portal', max_length=160)),
                ('tagline', models.CharField(default='Clear, accessible, and accountable local public service.', max_length=200)),
                ('hero_heading', models.CharField(default='How can we help you today?', max_length=180)),
                ('hero_text', models.CharField(default='Find municipal services, submit a request, or contact the right office.', max_length=280)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site_identity/')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='site_identity/')),
                ('primary_color', models.CharField(default='#123B66', max_length=7, validators=[django.core.validators.RegexValidator(message='Use a six-digit hexadecimal color such as #123B66.', regex='^#[0-9A-Fa-f]{6}$')])),
                ('accent_color', models.CharField(default='#D59B2D', max_length=7, validators=[django.core.validators.RegexValidator(message='Use a six-digit hexadecimal color such as #123B66.', regex='^#[0-9A-Fa-f]{6}$')])),
                ('featured_media_url', models.URLField(blank=True, help_text='Optional official video or public-information embed URL. Leave blank to hide the media panel.')),
                ('featured_media_title', models.CharField(blank=True, max_length=180)),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254)),
                ('footer_note', models.CharField(default='Institutional information remains available across changes in administration.', max_length=180)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site identity and appearance',
                'verbose_name_plural': 'Site identity and appearance',
            },
        ),
    ]
