# Generated by Django 5.1 on 2025-03-11 06:48

import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_announcement_is_pinned_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, default='defaults/jjv.png', upload_to=home.models.DepartmentContact.upload_directory_path)),
            ],
        ),
        migrations.CreateModel(
            name='OrgPersonnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, default='defaults/jjv.png', upload_to=home.models.OrgPersonnel.upload_directory_path)),
            ],
        ),
    ]
