# Generated by Django 5.1 on 2024-10-04 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_leave_status_changed_alter_leave_status'),
        ('users', '0011_merge_20240927_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Employee', to='users.profile', verbose_name='Employee'),
        ),
        migrations.AlterField(
            model_name='leavecounter',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.profile', verbose_name='Employee'),
        ),
    ]
