# Generated by Django 5.1 on 2025-03-11 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_departmentcontact_orgpersonnel'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentcontact',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
    ]
