# Generated by Django 5.1 on 2025-03-12 07:05

import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_orgpersonnel_display_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentcontact',
            name='image',
            field=models.ImageField(blank=True, upload_to=home.models.DepartmentContact.upload_directory_path),
        ),
        migrations.AlterField(
            model_name='orgpersonnel',
            name='image',
            field=models.ImageField(blank=True, upload_to=home.models.OrgPersonnel.upload_directory_path),
        ),
    ]
