# Generated by Django 5.1 on 2025-03-12 08:20

import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_departmentcontact_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentcontact',
            name='image',
            field=models.ImageField(blank=True, default='defaults/jjvbocaue-otimized.png', upload_to=home.models.DepartmentContact.upload_directory_path),
        ),
        migrations.AlterField(
            model_name='orgpersonnel',
            name='image',
            field=models.ImageField(blank=True, default='defaults/jjvbocaue-otimized.png', upload_to=home.models.OrgPersonnel.upload_directory_path),
        ),
    ]
