# Generated by Django 5.1 on 2025-03-13 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_departmentcontact_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentcontact',
            name='messenger_chat_link',
            field=models.CharField(help_text="Your Page's username or profile url here. Ex: tepong32 ", max_length=255, null=True),
        ),
    ]
