# Generated by Django 5.1 on 2025-03-15 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_departmentcontact_messenger_chat_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentcontact',
            name='motto',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
