# Generated by Django 5.1 on 2025-03-15 13:21

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_departmentcontact_motto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentcontact',
            name='motto',
            field=django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='Text'),
        ),
    ]
