# Generated by Django 5.1 on 2025-03-16 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_downloadableform_alter_announcement_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgpersonnel',
            name='title',
            field=models.CharField(default='Department Head - ', help_text="The words 'Department Head' need to be included so they can be displayed on the org chart page properly", max_length=255),
        ),
    ]
