# Generated by Django 5.1 on 2025-06-03 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_orgpersonnel_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departmentcontact',
            name='contact_number',
        ),
        migrations.AddField(
            model_name='departmentcontact',
            name='landline',
            field=models.CharField(blank=True, help_text='Landline number of the department. Ex: 044-123-4567', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='departmentcontact',
            name='mobile',
            field=models.CharField(blank=True, help_text='Mobile number of the department. Ex: 0912-345-6789', max_length=255, null=True),
        ),
    ]
