# Generated by Django 5.2.17 on 2026-08-14 10:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0004_alter_department_dashboard_template_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialWelfareProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('code', models.CharField(max_length=40)),
                ('program_type', models.CharField(choices=[('feeding', 'Feeding program'), ('seminar', 'Seminar'), ('orientation', 'Orientation'), ('outreach', 'Outreach'), ('distribution', 'Distribution'), ('intervention', 'Social intervention'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('completed', 'Completed'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coordinator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordinated_social_welfare_programs', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_social_welfare_programs', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='social_welfare_programs', to='departments.department')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updated_social_welfare_programs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
                'permissions': (('manage_social_welfare_programs', 'Can manage social welfare programs and activities'),),
            },
        ),
        migrations.CreateModel(
            name='ProgramActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('activity_type', models.CharField(choices=[('feeding', 'Feeding session'), ('seminar', 'Seminar'), ('orientation', 'Orientation'), ('outreach', 'Outreach activity'), ('distribution', 'Distribution activity'), ('field_operation', 'Field operation'), ('other', 'Other')], max_length=24)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('venue', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned', max_length=20)),
                ('expected_attendance', models.PositiveIntegerField(default=0)),
                ('actual_attendance', models.PositiveIntegerField(blank=True, null=True)),
                ('outcome_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_program_activities', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updated_program_activities', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='social_welfare.socialwelfareprogram')),
            ],
            options={
                'verbose_name_plural': 'program activities',
                'ordering': ('starts_at', 'title'),
            },
        ),
        migrations.AddConstraint(
            model_name='socialwelfareprogram',
            constraint=models.UniqueConstraint(fields=('department', 'code'), name='unique_social_welfare_program_code_per_department'),
        ),
    ]
