# Generated by Django 5.2.17 on 2026-08-15 14:15

import django.core.validators
import django.db.models.deletion
import records.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('departments', '0004_alter_department_dashboard_template_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('record_number', models.CharField(max_length=80)),
                ('title', models.CharField(max_length=220)),
                ('description', models.TextField(blank=True)),
                ('classification', models.CharField(choices=[('general', 'General office record'), ('assistance', 'Assistance case record'), ('program', 'Program record'), ('activity', 'Activity record'), ('citizen', 'Citizen service record'), ('report', 'Official report')], default='general', max_length=24)),
                ('confidentiality', models.CharField(choices=[('internal', 'Department internal'), ('restricted', 'Restricted'), ('confidential', 'Confidential / contains sensitive information')], default='internal', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('under_review', 'Under review'), ('approved', 'Approved'), ('superseded', 'Superseded'), ('archived', 'Archived'), ('disposed', 'Disposed')], db_index=True, default='draft', max_length=20)),
                ('retention_years', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('retention_notes', models.TextField(blank=True)),
                ('retention_start_date', models.DateField(blank=True, null=True)),
                ('disposition_due_date', models.DateField(blank=True, db_index=True, null=True)),
                ('legal_hold', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('disposed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_department_records', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_department_records', to=settings.AUTH_USER_MODEL)),
                ('custodian', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custodied_department_records', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='official_records', to='departments.department')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_department_records', to=settings.AUTH_USER_MODEL)),
                ('superseded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supersedes', to='records.departmentrecord')),
            ],
            options={
                'ordering': ('-updated_at', '-pk'),
                'permissions': (('view_records_workspace', 'Can access the department records workspace'), ('manage_department_records', 'Can create and update department records'), ('review_department_records', 'Can review department records'), ('approve_department_records', 'Can approve and supersede department records'), ('download_department_records', 'Can download department record files'), ('manage_record_retention', 'Can manage retention, archival, and disposal'), ('view_restricted_records', 'Can view restricted and confidential department records')),
            },
        ),
        migrations.CreateModel(
            name='RecordAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveBigIntegerField()),
                ('role', models.CharField(default='context', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_record_associations', to=settings.AUTH_USER_MODEL)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associations', to='records.departmentrecord')),
            ],
            options={
                'ordering': ('created_at', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='RecordEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('from_status', models.CharField(blank=True, max_length=20)),
                ('to_status', models.CharField(max_length=20)),
                ('note', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='department_record_events', to=settings.AUTH_USER_MODEL)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='records.departmentrecord')),
            ],
            options={
                'ordering': ('-created_at', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='RecordFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=500, upload_to=records.models.record_file_path)),
                ('display_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('content_type', models.CharField(blank=True, max_length=120)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('checksum', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='files', to='records.departmentrecord')),
                ('superseded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supersedes', to='records.recordfile')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_record_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-pk'),
            },
        ),
        migrations.AddConstraint(
            model_name='departmentrecord',
            constraint=models.UniqueConstraint(fields=('department', 'record_number'), name='unique_record_number_per_department'),
        ),
        migrations.AddConstraint(
            model_name='recordassociation',
            constraint=models.UniqueConstraint(fields=('record', 'content_type', 'object_id', 'role'), name='unique_record_association'),
        ),
    ]
