# Generated by Django 5.2.17 on 2026-08-25 15:31

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0004_alter_department_dashboard_template_and_more'),
        ('finance', '0002_financeparty_financepartyclaimant_and_more'),
        ('tracepoint', '0005_packethandoff_is_terminal_receipt_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAdviceBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('advice_number', models.CharField(max_length=60, unique=True)),
                ('advice_date', models.DateField()),
                ('bank_account_code', models.CharField(max_length=80)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('finalized', 'Finalized')], default='draft', max_length=16)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_bank_advice_batches', to=settings.AUTH_USER_MODEL)),
                ('finalized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finalized_bank_advice_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-advice_date', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='BudgetObligation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obr_number', models.CharField(max_length=60, unique=True)),
                ('obligation_date', models.DateField()),
                ('budget_source_reference', models.CharField(max_length=160)),
                ('certified_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('certified_at', models.DateTimeField()),
                ('certified_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certified_budget_obligations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BudgetAllocationLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fund_code', models.CharField(max_length=80)),
                ('responsibility_center_code', models.CharField(max_length=80)),
                ('account_code', models.CharField(blank=True, max_length=80)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('obligation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocation_lines', to='vouchers.budgetobligation')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='PaymentInstrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('bank_account_code', models.CharField(max_length=80)),
                ('check_number', models.CharField(max_length=60)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('advised', 'Included in finalized advice'), ('released', 'Released'), ('cancelled', 'Cancelled / spoiled')], default='draft', max_length=16)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('released_to', models.CharField(blank=True, max_length=220)),
                ('receipt_reference', models.CharField(blank=True, max_length=120)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cancelled_payment_instruments', to=settings.AUTH_USER_MODEL)),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='issued_payment_instruments', to=settings.AUTH_USER_MODEL)),
                ('released_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='released_payment_instruments', to=settings.AUTH_USER_MODEL)),
                ('released_to_claimant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='released_payment_instruments', to='finance.financepartyclaimant')),
                ('replaces', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replacement', to='vouchers.paymentinstrument')),
            ],
            options={
                'ordering': ('check_number', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='BankAdviceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='vouchers.bankadvicebatch')),
                ('instrument', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='advice_item', to='vouchers.paymentinstrument')),
            ],
        ),
        migrations.CreateModel(
            name='VoucherCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('reference_code', models.CharField(db_index=True, max_length=40, unique=True)),
                ('transaction_type', models.SlugField(default='ordinary-supplier-claim', max_length=80)),
                ('payee_name', models.CharField(max_length=220)),
                ('particulars', models.TextField()),
                ('current_stage', models.CharField(choices=[('budget_draft', 'Budget allocation draft'), ('accounting_preparation', 'Accounting DV preparation'), ('awaiting_signatures', 'Awaiting wet signatures'), ('accounting_validation', 'Accounting validation'), ('treasury_check_preparation', 'Treasury check preparation'), ('accounting_bank_advice', 'Accounting bank advice'), ('treasury_release', 'Treasury check release'), ('completed', 'Released / completed'), ('cancelled', 'Cancelled')], db_index=True, default='budget_draft', max_length=40)),
                ('state_version', models.PositiveIntegerField(default=0)),
                ('shadow_mode', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('configuration_release', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='voucher_cases', to='finance.financeconfigurationrelease')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_voucher_cases', to=settings.AUTH_USER_MODEL)),
                ('current_department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='current_voucher_cases', to='departments.department')),
                ('payee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='voucher_cases', to='finance.financeparty')),
                ('requesting_department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_voucher_cases', to='departments.department')),
                ('tracepoint_item', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='voucher_case', to='tracepoint.packetitem')),
                ('voucher_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='voucher_cases', to='finance.financetemplateversion')),
            ],
            options={
                'ordering': ('-updated_at', '-pk'),
                'permissions': (('view_voucher_workbench', 'Can access the voucher workbench'), ('initiate_budget_case', 'Can initiate budget voucher cases'), ('certify_budget_obligation', 'Can certify budget obligations'), ('prepare_disbursement_voucher', 'Can prepare disbursement vouchers'), ('track_wet_signatures', 'Can track wet signature circulation'), ('validate_accounting_voucher', 'Can validate accounting vouchers and JEV references'), ('issue_payment_instruments', 'Can issue checks and payment instruments'), ('finalize_bank_advice', 'Can finalize accountant bank advice'), ('release_payment_instruments', 'Can release checks and payment instruments'), ('manage_payment_exceptions', 'Can cancel and replace payment instruments'), ('return_voucher_case', 'Can return a voucher case for correction'), ('view_voucher_audit', 'Can view voucher audit history'), ('approve_control_overrides', 'Can approve voucher control overrides')),
            },
        ),
        migrations.AddField(
            model_name='paymentinstrument',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_instruments', to='vouchers.vouchercase'),
        ),
        migrations.CreateModel(
            name='DisbursementVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dv_number', models.CharField(max_length=60, unique=True)),
                ('voucher_date', models.DateField()),
                ('gross_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('total_deductions', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('net_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('prepared_at', models.DateTimeField()),
                ('prepared_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prepared_disbursement_vouchers', to=settings.AUTH_USER_MODEL)),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='disbursement_voucher', to='vouchers.vouchercase')),
            ],
        ),
        migrations.CreateModel(
            name='ControlOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_code', models.SlugField(max_length=80)),
                ('reason', models.TextField()),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('used', 'Used'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_voucher_overrides', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_voucher_overrides', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='control_overrides', to='vouchers.vouchercase')),
            ],
        ),
        migrations.AddField(
            model_name='budgetobligation',
            name='case',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='obligation', to='vouchers.vouchercase'),
        ),
        migrations.CreateModel(
            name='AccountingValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('accepted', 'Accepted'), ('returned', 'Returned for correction')], max_length=16)),
                ('jev_number', models.CharField(blank=True, max_length=60)),
                ('jev_date', models.DateField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('validated_at', models.DateTimeField()),
                ('validated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounting_validations', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounting_validations', to='vouchers.vouchercase')),
            ],
        ),
        migrations.CreateModel(
            name='VoucherDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=180)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deductions', to='vouchers.disbursementvoucher')),
            ],
        ),
        migrations.CreateModel(
            name='VoucherDocumentCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement_code', models.CharField(max_length=80)),
                ('label', models.CharField(max_length=180)),
                ('present', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='verified_voucher_documents', to=settings.AUTH_USER_MODEL)),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_checks', to='vouchers.disbursementvoucher')),
            ],
        ),
        migrations.CreateModel(
            name='VoucherEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=80)),
                ('from_stage', models.CharField(blank=True, max_length=40)),
                ('to_stage', models.CharField(blank=True, max_length=40)),
                ('reason', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('state_version', models.PositiveIntegerField()),
                ('idempotency_key', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='voucher_events', to=settings.AUTH_USER_MODEL)),
                ('actor_department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='voucher_events', to='departments.department')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='vouchers.vouchercase')),
            ],
            options={
                'ordering': ('-created_at', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='VoucherLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=240)),
                ('account_code', models.CharField(blank=True, max_length=80)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='line_items', to='vouchers.disbursementvoucher')),
            ],
        ),
        migrations.CreateModel(
            name='VoucherNumberIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.SlugField(max_length=80)),
                ('numeric_value', models.PositiveBigIntegerField()),
                ('formatted_value', models.CharField(max_length=60)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='number_issues', to='vouchers.vouchercase')),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='voucher_number_issues', to=settings.AUTH_USER_MODEL)),
                ('sequence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='voucher_number_issues', to='finance.financenumberingsequence')),
            ],
        ),
        migrations.CreateModel(
            name='VoucherTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('budget_draft', 'Budget allocation draft'), ('accounting_preparation', 'Accounting DV preparation'), ('awaiting_signatures', 'Awaiting wet signatures'), ('accounting_validation', 'Accounting validation'), ('treasury_check_preparation', 'Treasury check preparation'), ('accounting_bank_advice', 'Accounting bank advice'), ('treasury_release', 'Treasury check release'), ('completed', 'Released / completed'), ('cancelled', 'Cancelled')], max_length=40)),
                ('status', models.CharField(choices=[('open', 'Open'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='open', max_length=16)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='voucher_tasks', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='vouchers.vouchercase')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='voucher_tasks', to='departments.department')),
            ],
        ),
        migrations.CreateModel(
            name='WetSignatureTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveSmallIntegerField()),
                ('role_code', models.SlugField(max_length=80)),
                ('signatory_name_snapshot', models.CharField(max_length=180)),
                ('position_snapshot', models.CharField(blank=True, max_length=180)),
                ('status', models.CharField(choices=[('pending', 'Awaiting wet signature'), ('signed_returned', 'Signed and returned'), ('declined', 'Declined / returned')], default='pending', max_length=24)),
                ('recorded_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='signature_tasks', to='vouchers.vouchercase')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recorded_wet_signatures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('sequence', 'pk'),
            },
        ),
        migrations.AddConstraint(
            model_name='paymentinstrument',
            constraint=models.UniqueConstraint(fields=('bank_account_code', 'check_number'), name='unique_check_per_bank_account'),
        ),
        migrations.AddConstraint(
            model_name='voucherdocumentcheck',
            constraint=models.UniqueConstraint(fields=('voucher', 'requirement_code'), name='unique_voucher_document_requirement'),
        ),
        migrations.AddConstraint(
            model_name='voucherevent',
            constraint=models.UniqueConstraint(fields=('case', 'idempotency_key'), name='unique_voucher_action_idempotency'),
        ),
        migrations.AddConstraint(
            model_name='vouchernumberissue',
            constraint=models.UniqueConstraint(fields=('sequence', 'numeric_value'), name='unique_issued_finance_number'),
        ),
        migrations.AddConstraint(
            model_name='vouchernumberissue',
            constraint=models.UniqueConstraint(fields=('case', 'document_type'), name='unique_case_document_number'),
        ),
        migrations.AddConstraint(
            model_name='wetsignaturetask',
            constraint=models.UniqueConstraint(fields=('case', 'sequence'), name='unique_voucher_signature_sequence'),
        ),
    ]
