# Generated by Django 5.2.17 on 2026-08-25 15:34

import django.db.models.deletion
import vouchers.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_financeparty_financepartyclaimant_and_more'),
        ('vouchers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VoucherOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output_type', models.SlugField(max_length=80)),
                ('version', models.PositiveIntegerField(default=1)),
                ('file', models.FileField(max_length=500, upload_to=vouchers.models.voucher_output_path)),
                ('checksum', models.CharField(max_length=64)),
                ('input_snapshot', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('shadow', 'Shadow comparison'), ('official', 'Official'), ('superseded', 'Superseded')], default='shadow', max_length=16)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outputs', to='vouchers.vouchercase')),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generated_voucher_outputs', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='voucher_outputs', to='finance.financetemplateversion')),
            ],
            options={
                'ordering': ('output_type', '-version'),
                'constraints': [models.UniqueConstraint(fields=('case', 'output_type', 'version'), name='unique_voucher_output_version')],
            },
        ),
    ]
