# Generated by Django 5.2.17 on 2026-08-25 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0002_voucheroutput'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vouchercase',
            options={'ordering': ('-updated_at', '-pk'), 'permissions': (('view_voucher_workbench', 'Can access the voucher workbench'), ('initiate_budget_case', 'Can initiate budget voucher cases'), ('certify_budget_obligation', 'Can certify budget obligations'), ('prepare_disbursement_voucher', 'Can prepare disbursement vouchers'), ('track_wet_signatures', 'Can track wet signature circulation'), ('link_tracepoint_custody', 'Can link voucher cases to TracePoint custody items'), ('validate_accounting_voucher', 'Can validate accounting vouchers and JEV references'), ('issue_payment_instruments', 'Can issue checks and payment instruments'), ('finalize_bank_advice', 'Can finalize accountant bank advice'), ('release_payment_instruments', 'Can release checks and payment instruments'), ('manage_payment_exceptions', 'Can cancel and replace payment instruments'), ('return_voucher_case', 'Can return a voucher case for correction'), ('view_voucher_audit', 'Can view voucher audit history'), ('approve_control_overrides', 'Can approve voucher control overrides'))},
        ),
    ]
