# Generated by Django 5.2.17 on 2026-08-25 15:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0003_alter_vouchercase_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wetsignaturetask',
            options={'ordering': ('round_number', 'sequence', 'pk')},
        ),
        migrations.RemoveConstraint(
            model_name='wetsignaturetask',
            name='unique_voucher_signature_sequence',
        ),
        migrations.AddField(
            model_name='wetsignaturetask',
            name='round_number',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddConstraint(
            model_name='wetsignaturetask',
            constraint=models.UniqueConstraint(fields=('case', 'round_number', 'sequence'), name='unique_voucher_signature_sequence'),
        ),
    ]
