# Generated by Django 5.2.17 on 2026-08-28 01:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0004_alter_wetsignaturetask_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='vouchercase',
            name='current_stage',
            field=models.CharField(choices=[('budget_draft', 'Budget allocation draft'), ('accounting_preparation', 'Accounting DV preparation'), ('awaiting_signatures', 'Awaiting wet signatures'), ('accounting_validation', 'Accounting validation'), ('accounting_posting', 'Accounting JEV posting'), ('treasury_check_preparation', 'Treasury check preparation'), ('accounting_bank_advice', 'Accounting bank advice'), ('treasury_release', 'Treasury check release'), ('completed', 'Released / completed'), ('cancelled', 'Cancelled')], db_index=True, default='budget_draft', max_length=40),
        ),
        migrations.AlterField(
            model_name='vouchertask',
            name='stage',
            field=models.CharField(choices=[('budget_draft', 'Budget allocation draft'), ('accounting_preparation', 'Accounting DV preparation'), ('awaiting_signatures', 'Awaiting wet signatures'), ('accounting_validation', 'Accounting validation'), ('accounting_posting', 'Accounting JEV posting'), ('treasury_check_preparation', 'Treasury check preparation'), ('accounting_bank_advice', 'Accounting bank advice'), ('treasury_release', 'Treasury check release'), ('completed', 'Released / completed'), ('cancelled', 'Cancelled')], max_length=40),
        ),
        migrations.CreateModel(
            name='VoucherPostingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('kind', models.CharField(choices=[('recognition', 'Voucher recognition JEV')], default='recognition', max_length=20)),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('jev_number', models.CharField(max_length=60)),
                ('jev_date', models.DateField()),
                ('finance_department_id', models.PositiveBigIntegerField()),
                ('finance_department_label', models.CharField(max_length=160)),
                ('payload', models.JSONField(default=dict)),
                ('payload_checksum', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Waiting for JEV creation'), ('materialized', 'Draft JEV created'), ('posted', 'JEV posted'), ('failed', 'Needs intervention'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('accounting_entry_public_id', models.UUIDField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('materialized_at', models.DateTimeField(blank=True, null=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posting_requests', to='vouchers.vouchercase')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='voucher_posting_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-requested_at', '-pk'),
                'constraints': [models.UniqueConstraint(fields=('case', 'kind', 'version'), name='unique_voucher_posting_version'), models.UniqueConstraint(fields=('finance_department_id', 'jev_number'), name='unique_voucher_jev_number')],
            },
        ),
    ]
