# Generated by Django 5.2.17 on 2026-08-28 02:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0005_alter_vouchercase_current_stage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vouchercase',
            options={'ordering': ('-updated_at', '-pk'), 'permissions': (('view_voucher_workbench', 'Can access the voucher workbench'), ('initiate_budget_case', 'Can initiate budget voucher cases'), ('certify_budget_obligation', 'Can certify budget obligations'), ('prepare_disbursement_voucher', 'Can prepare disbursement vouchers'), ('track_wet_signatures', 'Can track wet signature circulation'), ('link_tracepoint_custody', 'Can link voucher cases to TracePoint custody items'), ('validate_accounting_voucher', 'Can validate accounting vouchers and JEV references'), ('issue_payment_instruments', 'Can issue checks and payment instruments'), ('finalize_bank_advice', 'Can finalize accountant bank advice'), ('release_payment_instruments', 'Can release checks and payment instruments'), ('manage_payment_exceptions', 'Can cancel and replace payment instruments'), ('return_voucher_case', 'Can return a voucher case for correction'), ('amend_nonfinancial_voucher', 'Can amend voucher dates and signatories before check issuance'), ('view_voucher_audit', 'Can view voucher audit history'), ('approve_control_overrides', 'Can approve voucher control overrides'))},
        ),
        migrations.CreateModel(
            name='VoucherNonFinancialAmendment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('awaiting_signatures', 'Awaiting replacement signatures'), ('completed', 'Completed')], default='awaiting_signatures', max_length=24)),
                ('prior_stage', models.CharField(choices=[('budget_draft', 'Budget allocation draft'), ('accounting_preparation', 'Accounting DV preparation'), ('awaiting_signatures', 'Awaiting wet signatures'), ('accounting_validation', 'Accounting validation'), ('accounting_posting', 'Accounting JEV posting'), ('treasury_check_preparation', 'Treasury check preparation'), ('accounting_bank_advice', 'Accounting bank advice'), ('treasury_release', 'Treasury check release'), ('completed', 'Released / completed'), ('cancelled', 'Cancelled')], max_length=40)),
                ('resume_stage', models.CharField(choices=[('budget_draft', 'Budget allocation draft'), ('accounting_preparation', 'Accounting DV preparation'), ('awaiting_signatures', 'Awaiting wet signatures'), ('accounting_validation', 'Accounting validation'), ('accounting_posting', 'Accounting JEV posting'), ('treasury_check_preparation', 'Treasury check preparation'), ('accounting_bank_advice', 'Accounting bank advice'), ('treasury_release', 'Treasury check release'), ('completed', 'Released / completed'), ('cancelled', 'Cancelled')], max_length=40)),
                ('signature_round_number', models.PositiveSmallIntegerField()),
                ('old_voucher_date', models.DateField()),
                ('new_voucher_date', models.DateField()),
                ('old_signatories', models.JSONField(default=list)),
                ('new_signatories', models.JSONField(default=list)),
                ('financial_snapshot', models.JSONField(default=dict)),
                ('reason', models.TextField()),
                ('amended_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('amended_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='voucher_nonfinancial_amendments', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nonfinancial_amendments', to='vouchers.vouchercase')),
            ],
            options={
                'ordering': ('-version', '-pk'),
                'constraints': [models.UniqueConstraint(fields=('case', 'version'), name='unique_voucher_nonfinancial_amendment_version')],
            },
        ),
    ]
