# Generated by Django 5.2.17 on 2026-08-28 12:52

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0006_alter_vouchercase_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vouchercase',
            options={'ordering': ('-updated_at', '-pk'), 'permissions': (('view_voucher_workbench', 'Can access the voucher workbench'), ('initiate_budget_case', 'Can initiate budget voucher cases'), ('initiate_payable_case', 'Can initiate payable cases from certified obligations'), ('certify_budget_obligation', 'Can certify budget obligations'), ('prepare_disbursement_voucher', 'Can prepare disbursement vouchers'), ('track_wet_signatures', 'Can track wet signature circulation'), ('link_tracepoint_custody', 'Can link voucher cases to TracePoint custody items'), ('validate_accounting_voucher', 'Can validate accounting vouchers and JEV references'), ('issue_payment_instruments', 'Can issue checks and payment instruments'), ('finalize_bank_advice', 'Can finalize accountant bank advice'), ('release_payment_instruments', 'Can release checks and payment instruments'), ('manage_payment_exceptions', 'Can cancel and replace payment instruments'), ('return_voucher_case', 'Can return a voucher case for correction'), ('amend_nonfinancial_voucher', 'Can amend voucher dates and signatories before check issuance'), ('view_voucher_audit', 'Can view voucher audit history'), ('approve_control_overrides', 'Can approve voucher control overrides'))},
        ),
        migrations.AddField(
            model_name='budgetobligation',
            name='source_kind',
            field=models.CharField(default='legacy_shadow', max_length=24),
        ),
        migrations.AddField(
            model_name='vouchercase',
            name='authoritative_obligation_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18),
        ),
        migrations.AddField(
            model_name='vouchercase',
            name='authoritative_obligation_checksum',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='vouchercase',
            name='authoritative_obligation_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='vouchercase',
            name='authoritative_obligation_public_id',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='vouchercase',
            name='obligation_binding_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vouchercase',
            name='obligation_binding_status',
            field=models.CharField(choices=[('not_applicable', 'Legacy / not linked'), ('pending', 'Authoritative obligation link pending'), ('linked', 'Authoritative obligation linked'), ('failed', 'Authoritative obligation link needs reconciliation')], default='not_applicable', max_length=20),
        ),
        migrations.CreateModel(
            name='PayableIntake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_reference', models.CharField(max_length=120)),
                ('invoice_number', models.CharField(blank=True, max_length=120)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('claim_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('procurement_reference', models.CharField(blank=True, max_length=180)),
                ('delivery_reference', models.CharField(blank=True, max_length=180)),
                ('inspection_acceptance_reference', models.CharField(blank=True, max_length=180)),
                ('evidence_reference', models.TextField()),
                ('duplicate_warning', models.TextField(blank=True)),
                ('duplicate_review_note', models.TextField(blank=True)),
                ('prepared_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payable_intake', to='vouchers.vouchercase')),
                ('prepared_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prepared_payable_intakes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-prepared_at', '-pk'),
                'constraints': [models.UniqueConstraint(fields=('case', 'claim_reference'), name='unique_case_payable_claim_reference')],
            },
        ),
    ]
