# Generated by Django 5.2.17 on 2026-08-28 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_financetransactionvariant_financedocumentrule_and_more'),
        ('vouchers', '0007_alter_vouchercase_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vouchercase',
            options={'ordering': ('-updated_at', '-pk'), 'permissions': (('view_voucher_workbench', 'Can access the voucher workbench'), ('initiate_budget_case', 'Can initiate budget voucher cases'), ('initiate_payable_case', 'Can initiate payable cases from certified obligations'), ('review_payable_intake', 'Can review payable readiness independently'), ('certify_budget_obligation', 'Can certify budget obligations'), ('prepare_disbursement_voucher', 'Can prepare disbursement vouchers'), ('track_wet_signatures', 'Can track wet signature circulation'), ('link_tracepoint_custody', 'Can link voucher cases to TracePoint custody items'), ('validate_accounting_voucher', 'Can validate accounting vouchers and JEV references'), ('issue_payment_instruments', 'Can issue checks and payment instruments'), ('finalize_bank_advice', 'Can finalize accountant bank advice'), ('release_payment_instruments', 'Can release checks and payment instruments'), ('manage_payment_exceptions', 'Can cancel and replace payment instruments'), ('return_voucher_case', 'Can return a voucher case for correction'), ('amend_nonfinancial_voucher', 'Can amend voucher dates and signatories before check issuance'), ('view_voucher_audit', 'Can view voucher audit history'), ('approve_control_overrides', 'Can approve voucher control overrides'))},
        ),
        migrations.AddField(
            model_name='payableintake',
            name='decision_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='payableintake',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payableintake',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_payable_intakes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payableintake',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft evidence intake'), ('for_review', 'For Accounting review'), ('returned', 'Returned for correction'), ('ready', 'Payment-ready for DV preparation')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='payableintake',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payableintake',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submitted_payable_intakes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vouchercase',
            name='current_stage',
            field=models.CharField(choices=[('budget_draft', 'Budget allocation draft'), ('payable_preparation', 'Requesting-office payable preparation'), ('payable_review', 'Accounting payable-readiness review'), ('accounting_preparation', 'Accounting DV preparation'), ('awaiting_signatures', 'Awaiting wet signatures'), ('accounting_validation', 'Accounting validation'), ('accounting_posting', 'Accounting JEV posting'), ('treasury_check_preparation', 'Treasury check preparation'), ('accounting_bank_advice', 'Accounting bank advice'), ('treasury_release', 'Treasury check release'), ('completed', 'Released / completed'), ('cancelled', 'Cancelled')], db_index=True, default='budget_draft', max_length=40),
        ),
        migrations.AlterField(
            model_name='vouchernonfinancialamendment',
            name='prior_stage',
            field=models.CharField(choices=[('budget_draft', 'Budget allocation draft'), ('payable_preparation', 'Requesting-office payable preparation'), ('payable_review', 'Accounting payable-readiness review'), ('accounting_preparation', 'Accounting DV preparation'), ('awaiting_signatures', 'Awaiting wet signatures'), ('accounting_validation', 'Accounting validation'), ('accounting_posting', 'Accounting JEV posting'), ('treasury_check_preparation', 'Treasury check preparation'), ('accounting_bank_advice', 'Accounting bank advice'), ('treasury_release', 'Treasury check release'), ('completed', 'Released / completed'), ('cancelled', 'Cancelled')], max_length=40),
        ),
        migrations.AlterField(
            model_name='vouchernonfinancialamendment',
            name='resume_stage',
            field=models.CharField(choices=[('budget_draft', 'Budget allocation draft'), ('payable_preparation', 'Requesting-office payable preparation'), ('payable_review', 'Accounting payable-readiness review'), ('accounting_preparation', 'Accounting DV preparation'), ('awaiting_signatures', 'Awaiting wet signatures'), ('accounting_validation', 'Accounting validation'), ('accounting_posting', 'Accounting JEV posting'), ('treasury_check_preparation', 'Treasury check preparation'), ('accounting_bank_advice', 'Accounting bank advice'), ('treasury_release', 'Treasury check release'), ('completed', 'Released / completed'), ('cancelled', 'Cancelled')], max_length=40),
        ),
        migrations.AlterField(
            model_name='vouchertask',
            name='stage',
            field=models.CharField(choices=[('budget_draft', 'Budget allocation draft'), ('payable_preparation', 'Requesting-office payable preparation'), ('payable_review', 'Accounting payable-readiness review'), ('accounting_preparation', 'Accounting DV preparation'), ('awaiting_signatures', 'Awaiting wet signatures'), ('accounting_validation', 'Accounting validation'), ('accounting_posting', 'Accounting JEV posting'), ('treasury_check_preparation', 'Treasury check preparation'), ('accounting_bank_advice', 'Accounting bank advice'), ('treasury_release', 'Treasury check release'), ('completed', 'Released / completed'), ('cancelled', 'Cancelled')], max_length=40),
        ),
        migrations.CreateModel(
            name='PayableDocumentEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_public_id_snapshot', models.UUIDField()),
                ('requirement_code', models.SlugField(max_length=80)),
                ('requirement_label', models.CharField(max_length=180)),
                ('evidence_kind', models.CharField(max_length=32)),
                ('required', models.BooleanField()),
                ('waiver_allowed', models.BooleanField()),
                ('condition_description', models.TextField(blank=True)),
                ('authority_reference', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('present', 'Present and referenced'), ('not_applicable', 'Condition not applicable'), ('waived', 'Waived by reviewed authority')], default='pending', max_length=20)),
                ('evidence_reference', models.TextField(blank=True)),
                ('decision_note', models.TextField(blank=True)),
                ('recorded_at', models.DateTimeField(blank=True, null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payable_document_evidence', to='vouchers.vouchercase')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recorded_payable_document_evidence', to=settings.AUTH_USER_MODEL)),
                ('source_rule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payable_evidence', to='finance.financedocumentrule')),
            ],
            options={
                'ordering': ('source_rule__display_order', 'requirement_code'),
                'constraints': [models.UniqueConstraint(fields=('case', 'requirement_code'), name='unique_payable_requirement_per_case')],
            },
        ),
    ]
