# Generated by Django 5.2.17 on 2026-08-29 00:55

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


def copy_existing_claim_controls(apps, schema_editor):
    PayableIntake = apps.get_model('vouchers', 'PayableIntake')
    PayableIntake.objects.using(schema_editor.connection.alias).update(
        initial_allocation_amount=models.F('claim_amount'),
    )


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0008_alter_vouchercase_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payableintake',
            name='initial_allocation_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.RunPython(copy_existing_claim_controls, migrations.RunPython.noop),
        migrations.AddField(
            model_name='payableintake',
            name='initial_relationship_type',
            field=models.CharField(choices=[('full', 'One-time / full claim'), ('partial', 'Partial claim; balance remains'), ('progress', 'Progress billing; balance remains'), ('final', 'Final claim; consume remaining balance')], default='full', max_length=16),
        ),
        migrations.AddField(
            model_name='payableintake',
            name='obligation_adjustment_basis',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='payableintake',
            name='obligation_adjustment_decision',
            field=models.CharField(blank=True, choices=[('no_adjustment', 'No obligation adjustment required'), ('adjustment_reflected', 'Governed pre-DV obligation adjustment reflected'), ('balance_retained', 'Partial/progress balance intentionally retained')], max_length=32),
        ),
        migrations.AddField(
            model_name='payableintake',
            name='recognition_basis',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='payableintake',
            name='recognition_decision',
            field=models.CharField(blank=True, choices=[('recognize_with_dv', 'Recognize through the governed DV/JEV route'), ('accrue_before_settlement', 'Accrue payable before settlement'), ('settle_existing_payable', 'Settle a previously recognized payable'), ('liquidation_decision', 'Liquidation / non-payment recognition decision')], max_length=32),
        ),
        migrations.AddField(
            model_name='payableintake',
            name='relationship_policy_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='budgetobligation',
            name='obr_number',
            field=models.CharField(db_index=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='vouchercase',
            name='authoritative_obligation_public_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
