# Generated by Django 5.2.17 on 2026-08-30 14:37

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0005_internal_howtos'),
        ('tracepoint', '0005_packethandoff_is_terminal_receipt_and_more'),
        ('vouchers', '0009_payableintake_initial_allocation_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vouchercase',
            options={'ordering': ('-updated_at', '-pk'), 'permissions': (('view_voucher_workbench', 'Can access the voucher workbench'), ('initiate_budget_case', 'Can initiate budget voucher cases'), ('initiate_payable_case', 'Can initiate payable cases from certified obligations'), ('review_payable_intake', 'Can review payable readiness independently'), ('certify_budget_obligation', 'Can certify budget obligations'), ('prepare_disbursement_voucher', 'Can prepare disbursement vouchers'), ('control_dv_printing', 'Can prepare and record controlled DV signing copies'), ('track_wet_signatures', 'Can track wet signature circulation'), ('link_tracepoint_custody', 'Can link voucher cases to TracePoint custody items'), ('validate_accounting_voucher', 'Can validate accounting vouchers and JEV references'), ('issue_payment_instruments', 'Can issue checks and payment instruments'), ('finalize_bank_advice', 'Can finalize accountant bank advice'), ('release_payment_instruments', 'Can release checks and payment instruments'), ('manage_payment_exceptions', 'Can cancel and replace payment instruments'), ('return_voucher_case', 'Can return a voucher case for correction'), ('amend_nonfinancial_voucher', 'Can amend voucher dates and signatories before check issuance'), ('view_voucher_audit', 'Can view voucher audit history'), ('approve_control_overrides', 'Can approve voucher control overrides'))},
        ),
        migrations.AddField(
            model_name='wetsignaturetask',
            name='custody_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='voucher_signature_custody_tasks', to='departments.department'),
        ),
        migrations.AddField(
            model_name='wetsignaturetask',
            name='custody_instructions',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='VoucherPrintJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('output_checksum', models.CharField(max_length=64)),
                ('signature_round', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('ready_to_print', 'Ready to print'), ('printed', 'Printed copies recorded'), ('awaiting_signatures', 'Awaiting wet signatures'), ('signed_packet_returned', 'Signed packet returned'), ('superseded', 'Superseded — do not sign')], db_index=True, default='ready_to_print', max_length=28)),
                ('copy_count', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('printer_or_form_stock', models.CharField(blank=True, max_length=180)),
                ('print_note', models.TextField(blank=True)),
                ('prepared_at', models.DateTimeField(auto_now_add=True)),
                ('printed_at', models.DateTimeField(blank=True, null=True)),
                ('packet_reference', models.CharField(blank=True, max_length=80)),
                ('archive_manifest', models.JSONField(blank=True, default=dict)),
                ('custody_manifest', models.JSONField(blank=True, default=dict)),
                ('custody_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('signed_returned_at', models.DateTimeField(blank=True, null=True)),
                ('supersession_reason', models.TextField(blank=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='print_jobs', to='vouchers.vouchercase')),
                ('custody_confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assembled_voucher_print_jobs', to=settings.AUTH_USER_MODEL)),
                ('output', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='print_job', to='vouchers.voucheroutput')),
                ('prepared_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prepared_voucher_print_jobs', to=settings.AUTH_USER_MODEL)),
                ('printed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='printed_voucher_print_jobs', to=settings.AUTH_USER_MODEL)),
                ('signed_returned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='returned_voucher_print_jobs', to=settings.AUTH_USER_MODEL)),
                ('supersedes', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='successor_print_job', to='vouchers.voucherprintjob')),
                ('tracepoint_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='voucher_print_jobs', to='tracepoint.packetitem')),
            ],
            options={
                'ordering': ('-version', '-pk'),
                'constraints': [models.UniqueConstraint(fields=('case', 'version'), name='unique_voucher_print_job_version'), models.UniqueConstraint(condition=models.Q(('status__in', ('ready_to_print', 'printed', 'awaiting_signatures'))), fields=('case',), name='unique_active_voucher_print_job')],
            },
        ),
    ]
