# Generated by Django 5.2.17 on 2026-08-30 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_financepostingrule_financepostingruleline_and_more'),
        ('vouchers', '0010_alter_vouchercase_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucherpostingrequest',
            name='posting_rule',
            field=models.ForeignKey(blank=True, help_text='Nullable only for posting requests created before governed F7 posting rules.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='voucher_posting_requests', to='finance.financepostingrule'),
        ),
        migrations.AddField(
            model_name='voucherpostingrequest',
            name='posting_rule_checksum',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='voucherpostingrequest',
            name='posting_rule_public_id_snapshot',
            field=models.CharField(blank=True, max_length=36),
        ),
        migrations.AddField(
            model_name='voucherpostingrequest',
            name='posting_rule_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='voucherpostingrequest',
            name='kind',
            field=models.CharField(choices=[('recognition', 'Recognize expense, asset, or payable'), ('adjustment', 'Adjust an earlier recognition'), ('liquidation', 'Record liquidation'), ('payment', 'Settle payable / record payment'), ('remittance', 'Remit deductions or withholdings'), ('cancellation', 'Record cancellation effect'), ('reversal', 'Reverse an earlier entry'), ('replacement', 'Record replacement effect')], default='recognition', max_length=20),
        ),
    ]
