# Generated by Django 5.2.17 on 2026-08-30 15:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_financepostingrule_accounting_effect_and_more'),
        ('vouchers', '0011_voucherpostingrequest_posting_rule_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='voucherpostingrequest',
            name='origin_stage',
            field=models.CharField(blank=True, choices=[('budget_draft', 'Budget allocation draft'), ('payable_preparation', 'Requesting-office payable preparation'), ('payable_review', 'Accounting payable-readiness review'), ('accounting_preparation', 'Accounting DV preparation'), ('awaiting_signatures', 'Awaiting wet signatures'), ('accounting_validation', 'Accounting validation'), ('accounting_posting', 'Accounting JEV posting'), ('accounting_event_posting', 'Accounting payment-event JEV posting'), ('treasury_check_preparation', 'Treasury check preparation'), ('accounting_bank_advice', 'Accounting bank advice'), ('treasury_release', 'Treasury check release'), ('completed', 'Released / completed'), ('cancelled', 'Cancelled')], max_length=40),
        ),
        migrations.AddField(
            model_name='voucherpostingrequest',
            name='resume_stage',
            field=models.CharField(blank=True, choices=[('budget_draft', 'Budget allocation draft'), ('payable_preparation', 'Requesting-office payable preparation'), ('payable_review', 'Accounting payable-readiness review'), ('accounting_preparation', 'Accounting DV preparation'), ('awaiting_signatures', 'Awaiting wet signatures'), ('accounting_validation', 'Accounting validation'), ('accounting_posting', 'Accounting JEV posting'), ('accounting_event_posting', 'Accounting payment-event JEV posting'), ('treasury_check_preparation', 'Treasury check preparation'), ('accounting_bank_advice', 'Accounting bank advice'), ('treasury_release', 'Treasury check release'), ('completed', 'Released / completed'), ('cancelled', 'Cancelled')], max_length=40),
        ),
        migrations.AddField(
            model_name='voucherpostingrequest',
            name='trigger_key',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AlterField(
            model_name='vouchercase',
            name='current_stage',
            field=models.CharField(choices=[('budget_draft', 'Budget allocation draft'), ('payable_preparation', 'Requesting-office payable preparation'), ('payable_review', 'Accounting payable-readiness review'), ('accounting_preparation', 'Accounting DV preparation'), ('awaiting_signatures', 'Awaiting wet signatures'), ('accounting_validation', 'Accounting validation'), ('accounting_posting', 'Accounting JEV posting'), ('accounting_event_posting', 'Accounting payment-event JEV posting'), ('treasury_check_preparation', 'Treasury check preparation'), ('accounting_bank_advice', 'Accounting bank advice'), ('treasury_release', 'Treasury check release'), ('completed', 'Released / completed'), ('cancelled', 'Cancelled')], db_index=True, default='budget_draft', max_length=40),
        ),
        migrations.AlterField(
            model_name='vouchernonfinancialamendment',
            name='prior_stage',
            field=models.CharField(choices=[('budget_draft', 'Budget allocation draft'), ('payable_preparation', 'Requesting-office payable preparation'), ('payable_review', 'Accounting payable-readiness review'), ('accounting_preparation', 'Accounting DV preparation'), ('awaiting_signatures', 'Awaiting wet signatures'), ('accounting_validation', 'Accounting validation'), ('accounting_posting', 'Accounting JEV posting'), ('accounting_event_posting', 'Accounting payment-event JEV posting'), ('treasury_check_preparation', 'Treasury check preparation'), ('accounting_bank_advice', 'Accounting bank advice'), ('treasury_release', 'Treasury check release'), ('completed', 'Released / completed'), ('cancelled', 'Cancelled')], max_length=40),
        ),
        migrations.AlterField(
            model_name='vouchernonfinancialamendment',
            name='resume_stage',
            field=models.CharField(choices=[('budget_draft', 'Budget allocation draft'), ('payable_preparation', 'Requesting-office payable preparation'), ('payable_review', 'Accounting payable-readiness review'), ('accounting_preparation', 'Accounting DV preparation'), ('awaiting_signatures', 'Awaiting wet signatures'), ('accounting_validation', 'Accounting validation'), ('accounting_posting', 'Accounting JEV posting'), ('accounting_event_posting', 'Accounting payment-event JEV posting'), ('treasury_check_preparation', 'Treasury check preparation'), ('accounting_bank_advice', 'Accounting bank advice'), ('treasury_release', 'Treasury check release'), ('completed', 'Released / completed'), ('cancelled', 'Cancelled')], max_length=40),
        ),
        migrations.AlterField(
            model_name='voucherpostingrequest',
            name='jev_number',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='voucherpostingrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Waiting for JEV creation'), ('materialized', 'Draft JEV created'), ('posted', 'JEV posted'), ('failed', 'Needs intervention'), ('cancelled', 'Cancelled'), ('not_required', 'No journal entry required')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='vouchertask',
            name='stage',
            field=models.CharField(choices=[('budget_draft', 'Budget allocation draft'), ('payable_preparation', 'Requesting-office payable preparation'), ('payable_review', 'Accounting payable-readiness review'), ('accounting_preparation', 'Accounting DV preparation'), ('awaiting_signatures', 'Awaiting wet signatures'), ('accounting_validation', 'Accounting validation'), ('accounting_posting', 'Accounting JEV posting'), ('accounting_event_posting', 'Accounting payment-event JEV posting'), ('treasury_check_preparation', 'Treasury check preparation'), ('accounting_bank_advice', 'Accounting bank advice'), ('treasury_release', 'Treasury check release'), ('completed', 'Released / completed'), ('cancelled', 'Cancelled')], max_length=40),
        ),
        migrations.AddConstraint(
            model_name='voucherpostingrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('trigger_key', ''), _negated=True), fields=('case', 'kind', 'trigger_key'), name='unique_voucher_posting_trigger'),
        ),
    ]
