# Generated by Django 5.2.17 on 2026-08-30 16:06

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0005_internal_howtos'),
        ('finance', '0009_financepostingrule_accounting_effect_and_more'),
        ('vouchers', '0012_voucherpostingrequest_origin_stage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TreasuryRemittanceBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('reference_code', models.CharField(max_length=60, unique=True)),
                ('finance_department_id', models.PositiveBigIntegerField()),
                ('finance_department_label', models.CharField(max_length=160)),
                ('fund_code', models.CharField(max_length=80)),
                ('bank_account_code', models.CharField(max_length=80)),
                ('remittance_date', models.DateField()),
                ('payment_method', models.CharField(max_length=80)),
                ('authority_reference', models.TextField()),
                ('evidence_reference', models.TextField()),
                ('release_reference', models.CharField(blank=True, max_length=160)),
                ('acknowledgement_reference', models.CharField(blank=True, max_length=160)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('returned', 'Returned for correction'), ('for_review', 'For Accounting review'), ('approved', 'Approved for remittance'), ('accounting_posting', 'Released; Accounting posting'), ('completed', 'Remitted and posted'), ('cancelled', 'Cancelled before release')], db_index=True, default='draft', max_length=24)),
                ('state_version', models.PositiveIntegerField(default=0)),
                ('posting_rule_snapshot', models.JSONField(blank=True, default=dict)),
                ('posting_rule_checksum', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_reason', models.TextField(blank=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cancelled_remittance_batches', to=settings.AUTH_USER_MODEL)),
                ('configuration_release', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='treasury_remittance_batches', to='finance.financeconfigurationrelease')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_remittance_batches', to=settings.AUTH_USER_MODEL)),
                ('posting_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='treasury_remittance_batches', to='finance.financepostingrule')),
                ('recipient_party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='treasury_remittance_batches', to='finance.financeparty')),
                ('released_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='released_remittance_batches', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_remittance_batches', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submitted_remittance_batches', to=settings.AUTH_USER_MODEL)),
                ('transaction_variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='treasury_remittance_batches', to='finance.financetransactionvariant')),
                ('treasury_department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='treasury_remittance_batches', to='departments.department')),
            ],
            options={
                'ordering': ('-remittance_date', '-pk'),
                'permissions': (('view_remittance_workbench', 'Can view the Treasury remittance workbench'), ('prepare_remittances', 'Can prepare deduction and withholding remittances'), ('approve_remittances', 'Can independently review remittances'), ('release_remittances', 'Can record actual remittance release'), ('view_remittance_audit', 'Can view remittance audit history')),
            },
        ),
        migrations.CreateModel(
            name='RemittanceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=80)),
                ('from_status', models.CharField(blank=True, max_length=24)),
                ('to_status', models.CharField(blank=True, max_length=24)),
                ('reason', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('state_version', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='remittance_events', to=settings.AUTH_USER_MODEL)),
                ('actor_department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='remittance_events', to='departments.department')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='vouchers.treasuryremittancebatch')),
            ],
            options={
                'ordering': ('-created_at', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='RemittancePostingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('jev_number', models.CharField(max_length=60)),
                ('jev_date', models.DateField()),
                ('finance_department_id', models.PositiveBigIntegerField()),
                ('finance_department_label', models.CharField(max_length=160)),
                ('posting_rule_snapshot', models.JSONField(default=dict)),
                ('posting_rule_checksum', models.CharField(max_length=64)),
                ('payload', models.JSONField(default=dict)),
                ('payload_checksum', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Waiting for JEV creation'), ('materialized', 'Draft JEV created'), ('posted', 'JEV posted'), ('failed', 'Needs intervention'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('accounting_entry_public_id', models.UUIDField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('materialized_at', models.DateTimeField(blank=True, null=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('posting_rule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='remittance_posting_requests', to='finance.financepostingrule')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='remittance_posting_requests', to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posting_requests', to='vouchers.treasuryremittancebatch')),
            ],
            options={
                'ordering': ('-requested_at', '-pk'),
                'constraints': [models.UniqueConstraint(fields=('batch', 'version'), name='unique_remittance_posting_version'), models.UniqueConstraint(fields=('finance_department_id', 'jev_number'), name='unique_remittance_jev_number')],
            },
        ),
        migrations.CreateModel(
            name='RemittanceNumberIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.SlugField(max_length=80)),
                ('numeric_value', models.PositiveBigIntegerField()),
                ('formatted_value', models.CharField(max_length=60)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='remittance_number_issues', to=settings.AUTH_USER_MODEL)),
                ('sequence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='remittance_number_issues', to='finance.financenumberingsequence')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='number_issues', to='vouchers.treasuryremittancebatch')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('sequence', 'numeric_value'), name='unique_issued_remittance_number'), models.UniqueConstraint(fields=('batch', 'document_type'), name='unique_remittance_document_number')],
            },
        ),
        migrations.CreateModel(
            name='TreasuryRemittanceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lineage_key', models.UUIDField(default=uuid.uuid4)),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('active', 'Active'), ('superseded', 'Superseded'), ('removed', 'Removed')], default='active', max_length=16)),
                ('fund_code', models.CharField(max_length=80)),
                ('account_code', models.CharField(max_length=80)),
                ('account_title', models.CharField(max_length=180)),
                ('reference_key', models.CharField(max_length=100)),
                ('reference_label', models.CharField(max_length=220)),
                ('deduction_code', models.CharField(max_length=80)),
                ('source_as_of_date', models.DateField()),
                ('available_balance_snapshot', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('source_checksum', models.CharField(max_length=64)),
                ('change_reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='vouchers.treasuryremittancebatch')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_remittance_lines', to=settings.AUTH_USER_MODEL)),
                ('supersedes', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='successor', to='vouchers.treasuryremittanceline')),
            ],
            options={
                'ordering': ('lineage_key', 'version'),
                'constraints': [models.UniqueConstraint(fields=('batch', 'lineage_key', 'version'), name='unique_remittance_line_version'), models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('batch', 'lineage_key'), name='unique_active_remittance_line')],
            },
        ),
    ]
