# Generated by Django 5.2.17 on 2026-08-30 16:46

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0005_internal_howtos'),
        ('finance', '0009_financepostingrule_accounting_effect_and_more'),
        ('vouchers', '0013_treasuryremittancebatch_remittanceevent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vouchercase',
            options={'ordering': ('-updated_at', '-pk'), 'permissions': (('view_voucher_workbench', 'Can access the voucher workbench'), ('initiate_budget_case', 'Can initiate budget voucher cases'), ('initiate_payable_case', 'Can initiate payable cases from certified obligations'), ('review_payable_intake', 'Can review payable readiness independently'), ('certify_budget_obligation', 'Can certify budget obligations'), ('prepare_disbursement_voucher', 'Can prepare disbursement vouchers'), ('control_dv_printing', 'Can prepare and record controlled DV signing copies'), ('track_wet_signatures', 'Can track wet signature circulation'), ('link_tracepoint_custody', 'Can link voucher cases to TracePoint custody items'), ('validate_accounting_voucher', 'Can validate accounting vouchers and JEV references'), ('issue_payment_instruments', 'Can issue checks and payment instruments'), ('finalize_bank_advice', 'Can finalize accountant bank advice'), ('release_payment_instruments', 'Can release checks and payment instruments'), ('manage_payment_exceptions', 'Can cancel and replace payment instruments'), ('view_cash_position', 'Can view Treasury cash positions and instrument ageing'), ('prepare_cash_position', 'Can prepare Treasury cash policies and positions'), ('approve_cash_position', 'Can independently approve Treasury cash policies and positions'), ('export_cash_position', 'Can export Treasury cash-position evidence'), ('return_voucher_case', 'Can return a voucher case for correction'), ('amend_nonfinancial_voucher', 'Can amend voucher dates and signatories before check issuance'), ('view_voucher_audit', 'Can view voucher audit history'), ('approve_control_overrides', 'Can approve voucher control overrides'))},
        ),
        migrations.AddField(
            model_name='paymentinstrument',
            name='fund_code',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='paymentinstrument',
            name='operational_status',
            field=models.CharField(choices=[('normal', 'No open exception'), ('unclaimed', 'Unclaimed / awaiting claimant action'), ('stale', 'Stale / release blocked'), ('returned', 'Returned by bank / resolution required')], default='normal', max_length=16),
        ),
        migrations.CreateModel(
            name='TreasuryCashPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('bank_account_code', models.CharField(max_length=80)),
                ('fund_code', models.CharField(max_length=80)),
                ('mode', models.CharField(choices=[('observe', 'Observe and report only'), ('enforce', 'Enforce cash availability at instrument issue')], default='observe', max_length=12)),
                ('minimum_reserve', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('position_max_age_days', models.PositiveSmallIntegerField(default=35)),
                ('unclaimed_after_days', models.PositiveSmallIntegerField(default=30)),
                ('stale_after_days', models.PositiveSmallIntegerField(default=180)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('authority_reference', models.TextField()),
                ('local_applicability_note', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('for_review', 'For independent review'), ('active', 'Active'), ('returned', 'Returned for correction'), ('superseded', 'Superseded')], default='draft', max_length=16)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('state_version', models.PositiveIntegerField(default=1)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_treasury_cash_policies', to=settings.AUTH_USER_MODEL)),
                ('configuration_release', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='treasury_cash_policies', to='finance.financeconfigurationrelease')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_treasury_cash_policies', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submitted_treasury_cash_policies', to=settings.AUTH_USER_MODEL)),
                ('supersedes', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='successor', to='vouchers.treasurycashpolicy')),
                ('treasury_department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='treasury_cash_policies', to='departments.department')),
            ],
            options={
                'ordering': ('-effective_from', 'bank_account_code', 'fund_code', '-version'),
            },
        ),
        migrations.CreateModel(
            name='PaymentInstrumentException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('kind', models.CharField(choices=[('unclaimed', 'Unclaimed instrument'), ('stale', 'Stale instrument'), ('returned', 'Returned by bank')], max_length=16)),
                ('observed_on', models.DateField()),
                ('reason', models.TextField()),
                ('evidence_reference', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved')], default='open', max_length=12)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution', models.TextField(blank=True)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exceptions', to='vouchers.paymentinstrument')),
                ('opened_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opened_payment_instrument_exceptions', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resolved_payment_instrument_exceptions', to=settings.AUTH_USER_MODEL)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instrument_exceptions', to='vouchers.treasurycashpolicy')),
            ],
            options={
                'ordering': ('-observed_on', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='TreasuryCashPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('as_of_date', models.DateField()),
                ('reconciliation_public_id', models.UUIDField()),
                ('reconciliation_checksum', models.CharField(max_length=64)),
                ('reconciliation_period_end', models.DateField()),
                ('reconciled_book_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('confirmed_inflows', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('confirmed_outflows', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('other_holds', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('evidence_reference', models.TextField()),
                ('preparation_note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('for_review', 'For independent review'), ('approved', 'Approved'), ('returned', 'Returned for correction'), ('superseded', 'Superseded')], default='draft', max_length=16)),
                ('version', models.PositiveIntegerField(default=1)),
                ('snapshot_checksum', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('state_version', models.PositiveIntegerField(default=1)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_treasury_cash_positions', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_treasury_cash_positions', to=settings.AUTH_USER_MODEL)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='positions', to='vouchers.treasurycashpolicy')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submitted_treasury_cash_positions', to=settings.AUTH_USER_MODEL)),
                ('supersedes', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='successor', to='vouchers.treasurycashposition')),
            ],
            options={
                'ordering': ('-as_of_date', '-version', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='TreasuryCashEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=80)),
                ('reason', models.TextField(blank=True)),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='treasury_cash_events', to=settings.AUTH_USER_MODEL)),
                ('actor_department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='treasury_cash_events', to='departments.department')),
                ('instrument', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cash_events', to='vouchers.paymentinstrument')),
                ('policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='vouchers.treasurycashpolicy')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='vouchers.treasurycashposition')),
            ],
            options={
                'ordering': ('-created_at', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='TreasuryCashReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('status', models.CharField(choices=[('reserved', 'Reserved at issue'), ('consumed', 'Consumed by release'), ('released', 'Released after cancellation')], default='reserved', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('close_reason', models.TextField(blank=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='closed_treasury_cash_reservations', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_treasury_cash_reservations', to=settings.AUTH_USER_MODEL)),
                ('instrument', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='cash_reservation', to='vouchers.paymentinstrument')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='vouchers.treasurycashposition')),
            ],
        ),
        migrations.AddConstraint(
            model_name='treasurycashpolicy',
            constraint=models.UniqueConstraint(fields=('configuration_release', 'bank_account_code', 'fund_code', 'version'), name='unique_treasury_cash_policy_version'),
        ),
        migrations.AddConstraint(
            model_name='paymentinstrumentexception',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'open')), fields=('instrument', 'kind'), name='unique_open_instrument_exception_kind'),
        ),
        migrations.AddConstraint(
            model_name='treasurycashposition',
            constraint=models.UniqueConstraint(fields=('policy', 'as_of_date', 'version'), name='unique_treasury_cash_position_version'),
        ),
    ]
