# Generated by Django 5.2.17 on 2026-08-30 17:17

import django.db.models.deletion
import hashlib
import json
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def carry_forward_legacy_advice(apps, schema_editor):
    Batch = apps.get_model('vouchers', 'BankAdviceBatch')
    Item = apps.get_model('vouchers', 'BankAdviceItem')
    Instrument = apps.get_model('vouchers', 'PaymentInstrument')
    for batch in Batch.objects.all().iterator():
        items = list(
            Item.objects.filter(batch=batch).select_related(
                'instrument__case__configuration_release',
            ).order_by('instrument__check_number', 'pk')
        )
        if not items:
            continue
        first = items[0].instrument
        release = first.case.configuration_release
        department_id = release.department_id if release else first.case.current_department_id
        total = Decimal('0.00')
        snapshot_items = []
        for item in items:
            instrument = item.instrument
            Item.objects.filter(pk=item.pk).update(
                instrument_public_id_snapshot=instrument.public_id,
                check_number_snapshot=instrument.check_number,
                fund_code_snapshot=instrument.fund_code,
                amount_snapshot=instrument.amount,
                issued_at_snapshot=instrument.issued_at,
            )
            Instrument.objects.filter(pk=instrument.pk).update(current_advice_batch_id=batch.pk)
            total += instrument.amount
            snapshot_items.append({
                'instrument_public_id': str(instrument.public_id),
                'case_public_id': str(instrument.case.public_id),
                'case_reference': instrument.case.reference_code,
                'check_number': instrument.check_number,
                'bank_account_code': instrument.bank_account_code,
                'fund_code': instrument.fund_code,
                'amount': str(instrument.amount),
                'issued_at': instrument.issued_at.isoformat() if instrument.issued_at else '',
            })
        status = 'acknowledged' if batch.status == 'finalized' else batch.status
        preparation_note = 'Legacy advice carried forward from the pre-F8.4 one-step workflow.'
        authority_reference = 'Legacy pre-F8.4 evidence; confirm the locally accepted authority in a successor before reuse.'
        local_note = 'Separate review, submission, and bank acknowledgement references were not captured by the earlier workflow.'
        snapshot = {
            'schema_version': 1,
            'batch_public_id': str(batch.public_id),
            'advice_number': batch.advice_number,
            'advice_date': batch.advice_date.isoformat(),
            'bank_account_code': batch.bank_account_code,
            'configuration_release_id': release.pk if release else None,
            'accounting_department_id': department_id,
            'version': batch.version,
            'supersedes_public_id': '',
            'preparation_note': preparation_note,
            'authority_reference': authority_reference,
            'local_applicability_note': local_note,
            'items': snapshot_items,
        }
        checksum = hashlib.sha256(
            json.dumps(snapshot, sort_keys=True, separators=(',', ':')).encode('utf-8')
        ).hexdigest()
        Batch.objects.filter(pk=batch.pk).update(
            status=status,
            configuration_release_id=release.pk if release else None,
            accounting_department_id=department_id,
            preparation_note=preparation_note,
            authority_reference=authority_reference,
            local_applicability_note=local_note,
            item_count=len(items),
            total_amount=total,
            snapshot_checksum=checksum,
            approved_by_id=batch.finalized_by_id,
            approved_at=batch.finalized_at,
            bank_submitted_by_id=batch.finalized_by_id,
            bank_submitted_at=batch.finalized_at,
            acknowledged_by_id=batch.finalized_by_id,
            acknowledged_at=batch.finalized_at,
            acknowledgement_reference='LEGACY-PRE-F8.4',
            acknowledgement_evidence_reference=local_note,
        )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0005_internal_howtos'),
        ('finance', '0010_alter_financepostingrule_recognition_point'),
        ('vouchers', '0014_alter_vouchercase_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAdviceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=80)),
                ('reason', models.TextField(blank=True)),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='ReturnedInstrumentReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('awaiting_review', 'Awaiting independent Accounting review'), ('returned', 'Returned to Treasury for clarification'), ('awaiting_posting', 'Awaiting returned-item JEV posting'), ('ready_for_treasury', 'Accounting complete; replacement authorized'), ('closed', 'Accounting complete; no replacement'), ('superseded', 'Superseded by clarified version')], default='awaiting_review', max_length=28)),
                ('outcome', models.CharField(blank=True, choices=[('reissue', 'Authorize a controlled replacement instrument'), ('close', 'Close without a replacement instrument')], max_length=16)),
                ('treasury_evidence_reference', models.TextField()),
                ('treasury_note', models.TextField()),
                ('accounting_decision_reason', models.TextField(blank=True)),
                ('accounting_evidence_reference', models.TextField(blank=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('prepared_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('state_version', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ('-prepared_at', '-version', '-pk'),
            },
        ),
        migrations.AlterModelOptions(
            name='bankadviceitem',
            options={'ordering': ('check_number_snapshot', 'pk')},
        ),
        migrations.AlterModelOptions(
            name='vouchercase',
            options={'ordering': ('-updated_at', '-pk'), 'permissions': (('view_voucher_workbench', 'Can access the voucher workbench'), ('initiate_budget_case', 'Can initiate budget voucher cases'), ('initiate_payable_case', 'Can initiate payable cases from certified obligations'), ('review_payable_intake', 'Can review payable readiness independently'), ('certify_budget_obligation', 'Can certify budget obligations'), ('prepare_disbursement_voucher', 'Can prepare disbursement vouchers'), ('control_dv_printing', 'Can prepare and record controlled DV signing copies'), ('track_wet_signatures', 'Can track wet signature circulation'), ('link_tracepoint_custody', 'Can link voucher cases to TracePoint custody items'), ('validate_accounting_voucher', 'Can validate accounting vouchers and JEV references'), ('issue_payment_instruments', 'Can issue checks and payment instruments'), ('finalize_bank_advice', 'Can finalize accountant bank advice'), ('view_bank_advice', 'Can view bank-advice and returned-instrument evidence'), ('prepare_bank_advice', 'Can prepare versioned bank-advice batches'), ('approve_bank_advice', 'Can independently review bank-advice batches'), ('submit_bank_advice', 'Can record bank-advice submission evidence'), ('acknowledge_bank_advice', 'Can record bank acknowledgement or return evidence'), ('review_returned_instruments', 'Can decide the Accounting treatment of returned instruments'), ('export_bank_advice', 'Can export bank-advice and returned-item evidence'), ('release_payment_instruments', 'Can release checks and payment instruments'), ('manage_payment_exceptions', 'Can cancel and replace payment instruments'), ('view_cash_position', 'Can view Treasury cash positions and instrument ageing'), ('prepare_cash_position', 'Can prepare Treasury cash policies and positions'), ('approve_cash_position', 'Can independently approve Treasury cash policies and positions'), ('export_cash_position', 'Can export Treasury cash-position evidence'), ('return_voucher_case', 'Can return a voucher case for correction'), ('amend_nonfinancial_voucher', 'Can amend voucher dates and signatories before check issuance'), ('view_voucher_audit', 'Can view voucher audit history'), ('approve_control_overrides', 'Can approve voucher control overrides'))},
        ),
        migrations.AddField(
            model_name='bankadvicebatch',
            name='accounting_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bank_advice_batches', to='departments.department'),
        ),
        migrations.AddField(
            model_name='bankadvicebatch',
            name='acknowledged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bankadvicebatch',
            name='acknowledged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='acknowledged_bank_advice_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bankadvicebatch',
            name='acknowledgement_evidence_reference',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bankadvicebatch',
            name='acknowledgement_reference',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='bankadvicebatch',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bankadvicebatch',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_bank_advice_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bankadvicebatch',
            name='authority_reference',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bankadvicebatch',
            name='bank_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bankadvicebatch',
            name='bank_submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bank_submitted_advice_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bankadvicebatch',
            name='configuration_release',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bank_advice_batches', to='finance.financeconfigurationrelease'),
        ),
        migrations.AddField(
            model_name='bankadvicebatch',
            name='item_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bankadvicebatch',
            name='local_applicability_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bankadvicebatch',
            name='preparation_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bankadvicebatch',
            name='return_evidence_reference',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bankadvicebatch',
            name='return_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bankadvicebatch',
            name='returned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bankadvicebatch',
            name='returned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='returned_bank_advice_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bankadvicebatch',
            name='review_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bankadvicebatch',
            name='review_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bankadvicebatch',
            name='review_submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='review_submitted_bank_advice_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bankadvicebatch',
            name='snapshot_checksum',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='bankadvicebatch',
            name='state_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='bankadvicebatch',
            name='submission_evidence_reference',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bankadvicebatch',
            name='submission_reference',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='bankadvicebatch',
            name='supersedes',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='successor', to='vouchers.bankadvicebatch'),
        ),
        migrations.AddField(
            model_name='bankadvicebatch',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18),
        ),
        migrations.AddField(
            model_name='bankadviceitem',
            name='amount_snapshot',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18),
        ),
        migrations.AddField(
            model_name='bankadviceitem',
            name='check_number_snapshot',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='bankadviceitem',
            name='fund_code_snapshot',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='bankadviceitem',
            name='instrument_public_id_snapshot',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bankadviceitem',
            name='issued_at_snapshot',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentinstrument',
            name='current_advice_batch',
            field=models.ForeignKey(blank=True, help_text='Latest governed advice version carrying this instrument.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_instruments', to='vouchers.bankadvicebatch'),
        ),
        migrations.AlterField(
            model_name='bankadvicebatch',
            name='advice_number',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='bankadvicebatch',
            name='status',
            field=models.CharField(choices=[('draft', 'Prepared draft'), ('for_review', 'For independent Accounting review'), ('review_returned', 'Returned by Accounting reviewer'), ('approved', 'Approved for bank submission'), ('submitted', 'Submitted to bank'), ('acknowledged', 'Acknowledged by bank'), ('returned', 'Returned by bank for correction'), ('superseded', 'Superseded by corrected version')], default='draft', max_length=16),
        ),
        migrations.AlterField(
            model_name='bankadviceitem',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='advice_items', to='vouchers.paymentinstrument'),
        ),
        migrations.RunPython(carry_forward_legacy_advice, noop_reverse),
        migrations.AlterField(
            model_name='paymentinstrument',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('advised', 'Included in an approved advice'), ('released', 'Released'), ('bank_returned', 'Returned by bank after release'), ('cancelled', 'Cancelled / spoiled')], default='draft', max_length=16),
        ),
        migrations.AlterField(
            model_name='vouchercase',
            name='current_stage',
            field=models.CharField(choices=[('budget_draft', 'Budget allocation draft'), ('payable_preparation', 'Requesting-office payable preparation'), ('payable_review', 'Accounting payable-readiness review'), ('accounting_preparation', 'Accounting DV preparation'), ('awaiting_signatures', 'Awaiting wet signatures'), ('accounting_validation', 'Accounting validation'), ('accounting_posting', 'Accounting JEV posting'), ('accounting_event_posting', 'Accounting payment-event JEV posting'), ('accounting_returned_item', 'Accounting returned-instrument review'), ('treasury_check_preparation', 'Treasury check preparation'), ('accounting_bank_advice', 'Accounting bank advice'), ('treasury_release', 'Treasury check release'), ('completed', 'Released / completed'), ('cancelled', 'Cancelled')], db_index=True, default='budget_draft', max_length=40),
        ),
        migrations.AlterField(
            model_name='vouchernonfinancialamendment',
            name='prior_stage',
            field=models.CharField(choices=[('budget_draft', 'Budget allocation draft'), ('payable_preparation', 'Requesting-office payable preparation'), ('payable_review', 'Accounting payable-readiness review'), ('accounting_preparation', 'Accounting DV preparation'), ('awaiting_signatures', 'Awaiting wet signatures'), ('accounting_validation', 'Accounting validation'), ('accounting_posting', 'Accounting JEV posting'), ('accounting_event_posting', 'Accounting payment-event JEV posting'), ('accounting_returned_item', 'Accounting returned-instrument review'), ('treasury_check_preparation', 'Treasury check preparation'), ('accounting_bank_advice', 'Accounting bank advice'), ('treasury_release', 'Treasury check release'), ('completed', 'Released / completed'), ('cancelled', 'Cancelled')], max_length=40),
        ),
        migrations.AlterField(
            model_name='vouchernonfinancialamendment',
            name='resume_stage',
            field=models.CharField(choices=[('budget_draft', 'Budget allocation draft'), ('payable_preparation', 'Requesting-office payable preparation'), ('payable_review', 'Accounting payable-readiness review'), ('accounting_preparation', 'Accounting DV preparation'), ('awaiting_signatures', 'Awaiting wet signatures'), ('accounting_validation', 'Accounting validation'), ('accounting_posting', 'Accounting JEV posting'), ('accounting_event_posting', 'Accounting payment-event JEV posting'), ('accounting_returned_item', 'Accounting returned-instrument review'), ('treasury_check_preparation', 'Treasury check preparation'), ('accounting_bank_advice', 'Accounting bank advice'), ('treasury_release', 'Treasury check release'), ('completed', 'Released / completed'), ('cancelled', 'Cancelled')], max_length=40),
        ),
        migrations.AlterField(
            model_name='voucherpostingrequest',
            name='origin_stage',
            field=models.CharField(blank=True, choices=[('budget_draft', 'Budget allocation draft'), ('payable_preparation', 'Requesting-office payable preparation'), ('payable_review', 'Accounting payable-readiness review'), ('accounting_preparation', 'Accounting DV preparation'), ('awaiting_signatures', 'Awaiting wet signatures'), ('accounting_validation', 'Accounting validation'), ('accounting_posting', 'Accounting JEV posting'), ('accounting_event_posting', 'Accounting payment-event JEV posting'), ('accounting_returned_item', 'Accounting returned-instrument review'), ('treasury_check_preparation', 'Treasury check preparation'), ('accounting_bank_advice', 'Accounting bank advice'), ('treasury_release', 'Treasury check release'), ('completed', 'Released / completed'), ('cancelled', 'Cancelled')], max_length=40),
        ),
        migrations.AlterField(
            model_name='voucherpostingrequest',
            name='resume_stage',
            field=models.CharField(blank=True, choices=[('budget_draft', 'Budget allocation draft'), ('payable_preparation', 'Requesting-office payable preparation'), ('payable_review', 'Accounting payable-readiness review'), ('accounting_preparation', 'Accounting DV preparation'), ('awaiting_signatures', 'Awaiting wet signatures'), ('accounting_validation', 'Accounting validation'), ('accounting_posting', 'Accounting JEV posting'), ('accounting_event_posting', 'Accounting payment-event JEV posting'), ('accounting_returned_item', 'Accounting returned-instrument review'), ('treasury_check_preparation', 'Treasury check preparation'), ('accounting_bank_advice', 'Accounting bank advice'), ('treasury_release', 'Treasury check release'), ('completed', 'Released / completed'), ('cancelled', 'Cancelled')], max_length=40),
        ),
        migrations.AlterField(
            model_name='vouchertask',
            name='stage',
            field=models.CharField(choices=[('budget_draft', 'Budget allocation draft'), ('payable_preparation', 'Requesting-office payable preparation'), ('payable_review', 'Accounting payable-readiness review'), ('accounting_preparation', 'Accounting DV preparation'), ('awaiting_signatures', 'Awaiting wet signatures'), ('accounting_validation', 'Accounting validation'), ('accounting_posting', 'Accounting JEV posting'), ('accounting_event_posting', 'Accounting payment-event JEV posting'), ('accounting_returned_item', 'Accounting returned-instrument review'), ('treasury_check_preparation', 'Treasury check preparation'), ('accounting_bank_advice', 'Accounting bank advice'), ('treasury_release', 'Treasury check release'), ('completed', 'Released / completed'), ('cancelled', 'Cancelled')], max_length=40),
        ),
        migrations.AddConstraint(
            model_name='bankadvicebatch',
            constraint=models.UniqueConstraint(fields=('advice_number', 'version'), name='unique_bank_advice_number_version'),
        ),
        migrations.AddConstraint(
            model_name='bankadviceitem',
            constraint=models.UniqueConstraint(fields=('batch', 'instrument'), name='unique_instrument_per_advice_version'),
        ),
        migrations.AddField(
            model_name='bankadviceevent',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bank_advice_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bankadviceevent',
            name='actor_department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bank_advice_events', to='departments.department'),
        ),
        migrations.AddField(
            model_name='bankadviceevent',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='vouchers.bankadvicebatch'),
        ),
        migrations.AddField(
            model_name='bankadviceevent',
            name='instrument',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bank_advice_events', to='vouchers.paymentinstrument'),
        ),
        migrations.AddField(
            model_name='returnedinstrumentreview',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returned_instrument_reviews', to='vouchers.vouchercase'),
        ),
        migrations.AddField(
            model_name='returnedinstrumentreview',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='closed_returned_instrument_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='returnedinstrumentreview',
            name='exception',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounting_reviews', to='vouchers.paymentinstrumentexception'),
        ),
        migrations.AddField(
            model_name='returnedinstrumentreview',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returned_accounting_reviews', to='vouchers.paymentinstrument'),
        ),
        migrations.AddField(
            model_name='returnedinstrumentreview',
            name='original_payment_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='returned_instrument_source_reviews', to='vouchers.voucherpostingrequest'),
        ),
        migrations.AddField(
            model_name='returnedinstrumentreview',
            name='posting_request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='returned_instrument_review', to='vouchers.voucherpostingrequest'),
        ),
        migrations.AddField(
            model_name='returnedinstrumentreview',
            name='prepared_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prepared_returned_instrument_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='returnedinstrumentreview',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_returned_instrument_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='returnedinstrumentreview',
            name='supersedes',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='successor', to='vouchers.returnedinstrumentreview'),
        ),
        migrations.AddConstraint(
            model_name='returnedinstrumentreview',
            constraint=models.UniqueConstraint(fields=('exception', 'version'), name='unique_returned_instrument_review_version'),
        ),
    ]
