# Generated by Django 5.2.17 on 2026-08-31 05:43

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0015_cutover_cycle_qualification'),
        ('vouchers', '0015_bankadviceevent_returnedinstrumentreview_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucherdeduction',
            name='payee_name_snapshot',
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.AddField(
            model_name='voucherdeduction',
            name='payee_tax_identifier_snapshot',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='voucherdeduction',
            name='tax_base',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AddField(
            model_name='voucherdeduction',
            name='tax_evidence_checksum',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='voucherdeduction',
            name='tax_rule_checksum',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='voucherdeduction',
            name='tax_rule_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='voucher_deduction_snapshots', to='finance.financeconfigurationitem'),
        ),
        migrations.AddField(
            model_name='voucherdeduction',
            name='tax_rule_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddConstraint(
            model_name='voucherdeduction',
            constraint=models.UniqueConstraint(condition=models.Q(('tax_rule_item__isnull', False)), fields=('voucher', 'tax_rule_item'), name='unique_voucher_tax_rule'),
        ),
    ]
