# Generated by Django 5.2.17 on 2026-08-31 06:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0016_voucher_tax_reporting_evidence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='treasuryremittanceline',
            name='tax_rule_checksum',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='treasuryremittanceline',
            name='tax_rule_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='TaxFilingEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('filing_type', models.CharField(choices=[('original', 'Original filing'), ('amended', 'Amended filing')], default='original', max_length=12)),
                ('return_form_code', models.CharField(max_length=40)),
                ('tax_period_start', models.DateField()),
                ('tax_period_end', models.DateField()),
                ('filing_date', models.DateField()),
                ('submission_channel', models.CharField(max_length=120)),
                ('filing_reference', models.CharField(max_length=160)),
                ('payment_confirmation_reference', models.CharField(max_length=160)),
                ('source_schedule_reference', models.CharField(max_length=220)),
                ('source_schedule_checksum', models.CharField(max_length=64)),
                ('evidence_reference', models.TextField()),
                ('tax_scope_snapshot', models.JSONField(default=dict)),
                ('evidence_checksum', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('draft', 'Draft evidence'), ('returned', 'Returned for correction'), ('for_review', 'For independent review'), ('verified', 'Evidence verified'), ('superseded', 'Superseded by amendment')], db_index=True, default='draft', max_length=16)),
                ('state_version', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_reason', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tax_filing_evidence', to='vouchers.treasuryremittancebatch')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_tax_filing_evidence', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_tax_filing_evidence', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submitted_tax_filing_evidence', to=settings.AUTH_USER_MODEL)),
                ('supersedes', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='successor', to='vouchers.taxfilingevidence')),
            ],
            options={
                'ordering': ('-filing_date', '-pk'),
                'constraints': [models.UniqueConstraint(fields=('batch', 'version'), name='unique_tax_filing_evidence_version'), models.UniqueConstraint(condition=models.Q(('status__in', ('draft', 'returned', 'for_review', 'verified'))), fields=('batch',), name='unique_current_tax_filing_evidence')],
            },
        ),
    ]
