# Generated by Django 5.2.17 on 2026-08-31 06:33

from django.db import migrations, models


def classify_legacy_manual_sources(apps, schema_editor):
    TaxFilingEvidence = apps.get_model('vouchers', 'TaxFilingEvidence')
    TaxFilingEvidence.objects.filter(source_report_run_public_id__isnull=True).update(
        source_mode='external_schedule',
        external_source_basis=(
            'Legacy F9.6 manually checksummed source schedule retained during the guided-source upgrade.'
        ),
        evidence_schema_version=1,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0017_treasuryremittanceline_tax_rule_checksum_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxfilingevidence',
            name='external_source_basis',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='taxfilingevidence',
            name='evidence_schema_version',
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='taxfilingevidence',
            name='source_mode',
            field=models.CharField(choices=[('grand_report', 'Approved GRAND tax report'), ('external_schedule', 'Advanced: external reviewed schedule')], default='grand_report', max_length=24),
        ),
        migrations.AddField(
            model_name='taxfilingevidence',
            name='source_report_run_public_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taxfilingevidence',
            name='source_report_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='taxfilingevidence',
            name='source_schedule_checksum',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='taxfilingevidence',
            name='source_schedule_reference',
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.RunPython(classify_legacy_manual_sources, migrations.RunPython.noop),
    ]
