# Generated by Django 5.2.17 on 2026-09-01 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0005_internal_howtos'),
        ('vouchers', '0018_taxfilingevidence_external_source_basis_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceFoundationIssuanceBoundary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_year', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finance_foundation_issuance_boundaries', to='departments.department')),
            ],
            options={
                'ordering': ('department__name', 'fiscal_year'),
                'constraints': [models.UniqueConstraint(fields=('department', 'fiscal_year'), name='unique_finance_foundation_issuance_boundary')],
            },
        ),
    ]
