# Generated by Django 5.2.17 on 2026-09-03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vouchers', '0019_financefoundationissuanceboundary'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoucherCaseSavedView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('name_key', models.CharField(editable=False, max_length=80)),
                ('filters', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voucher_case_saved_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name_key', 'pk'),
                'constraints': [models.UniqueConstraint(fields=('owner', 'name_key'), name='unique_private_voucher_case_view_name')],
            },
        ),
    ]
