# Generated by Django 5.2.17 on 2026-09-08 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0020_vouchercasesavedview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vouchernonfinancialamendment',
            name='status',
            field=models.CharField(choices=[('awaiting_signatures', 'Awaiting replacement signatures'), ('completed', 'Completed'), ('superseded', 'Superseded by returned DV correction')], default='awaiting_signatures', max_length=24),
        ),
    ]
