# Generated by Django 5.2.17 on 2026-09-09 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0021_amendment_return_supersession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetobligation',
            name='source_kind',
            field=models.CharField(default='legacy_shadow', max_length=64),
        ),
    ]
