# Generated by Django 5.2.17 on 2026-09-09 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0022_alter_budgetobligation_source_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetobligation',
            name='budget_source_reference',
            field=models.TextField(),
        ),
    ]
