# Generated by Django 5.2.17 on 2026-09-10 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0023_alter_budgetobligation_budget_source_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingvalidation',
            name='prior_payable_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
