# Generated by Django 5.2.17 on 2026-09-10 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0024_accountingvalidation_prior_payable_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentinstrument',
            name='prior_payable_allocation',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
