# Generated by Django 5.2.17 on 2026-09-12 11:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0025_paymentinstrument_prior_payable_allocation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RemittanceReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('version', models.PositiveIntegerField()),
                ('proposal', models.JSONField(default=dict)),
                ('proposal_checksum', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('proposed', 'For independent review'), ('approved', 'Approved; Accounting posting'), ('rejected', 'Returned for correction'), ('posted', 'Return posted')], default='proposed', max_length=16)),
                ('prepared_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_reason', models.TextField(blank=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='vouchers.treasuryremittancebatch')),
                ('posting_request', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='remittance_return', to='vouchers.remittancepostingrequest')),
                ('prepared_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prepared_remittance_returns', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_remittance_returns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-version',),
                'constraints': [models.UniqueConstraint(fields=('batch', 'version'), name='unique_remittance_return_version')],
            },
        ),
    ]
