# Generated by Django 5.2.17 on 2026-09-12 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0026_remittance_return'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remittancereturn',
            name='status',
            field=models.CharField(choices=[('proposed', 'For independent review'), ('approved', 'Approved; Accounting posting'), ('rejected', 'Returned for correction'), ('posted', 'Return posted'), ('withdrawn', 'Withdrawn before posting')], default='proposed', max_length=16),
        ),
    ]
