# Generated by Django 5.2.17 on 2026-09-12 12:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0027_remittance_return_withdrawal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='remittancereturn',
            name='status',
            field=models.CharField(choices=[('proposed', 'For independent review'), ('approved', 'Approved; Accounting posting'), ('rejected', 'Returned for correction'), ('posted', 'Return posted'), ('withdrawn', 'Withdrawn before posting'), ('corrected', 'Receipt reversed by posted correction')], default='proposed', max_length=16),
        ),
        migrations.CreateModel(
            name='RemittanceReturnCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('version', models.PositiveIntegerField()),
                ('proposal', models.JSONField(default=dict)),
                ('proposal_checksum', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('proposed', 'For independent correction review'), ('approved', 'Approved; correction posting'), ('rejected', 'Correction rejected'), ('posted', 'Correction posted'), ('withdrawn', 'Correction withdrawn before posting')], default='proposed', max_length=16)),
                ('prepared_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_reason', models.TextField(blank=True)),
                ('posting_request', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipt_correction', to='vouchers.remittancepostingrequest')),
                ('prepared_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prepared_receipt_corrections', to=settings.AUTH_USER_MODEL)),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='corrections', to='vouchers.remittancereturn')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_receipt_corrections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-version',),
                'constraints': [models.UniqueConstraint(fields=('receipt', 'version'), name='unique_receipt_correction_version')],
            },
        ),
    ]
