# Generated by Django 5.2.17 on 2026-09-12 13:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0005_internal_howtos'),
        ('finance', '0023_collection_sources'),
        ('vouchers', '0028_posted_receipt_corrections'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucherpostingrequest',
            name='kind',
            field=models.CharField(choices=[('collection', 'Record an actual Treasury collection'), ('deposit', 'Deposit previously recorded collections'), ('recognition', 'Recognize expense, asset, or payable'), ('adjustment', 'Adjust an earlier recognition'), ('liquidation', 'Record liquidation'), ('payment', 'Settle payable / record payment'), ('remittance', 'Remit deductions or withholdings'), ('cancellation', 'Record cancellation effect'), ('reversal', 'Reverse an earlier entry'), ('replacement', 'Record replacement effect')], default='recognition', max_length=20),
        ),
        migrations.CreateModel(
            name='TreasuryCollectionSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('finance_department_id', models.PositiveBigIntegerField()),
                ('finance_department_label', models.CharField(max_length=160)),
                ('kind', models.CharField(choices=[('receipt', 'Collection receipt'), ('deposit', 'Deposit of collections')], max_length=16)),
                ('book_reference', models.CharField(blank=True, max_length=80)),
                ('document_reference', models.CharField(max_length=80)),
                ('version', models.PositiveIntegerField(default=1)),
                ('source_date', models.DateField()),
                ('fund_code', models.CharField(max_length=80)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('proposal', models.JSONField(default=dict)),
                ('proposal_checksum', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('proposed', 'For independent review'), ('approved', 'Approved; Accounting posting'), ('rejected', 'Returned for correction'), ('posted', 'Posted'), ('withdrawn', 'Withdrawn before posting')], default='proposed', max_length=16)),
                ('prepared_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_reason', models.TextField(blank=True)),
                ('configuration_release', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collection_sources', to='finance.financeconfigurationrelease')),
                ('prepared_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prepared_collection_sources', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_collection_sources', to=settings.AUTH_USER_MODEL)),
                ('supersedes', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='successor', to='vouchers.treasurycollectionsource')),
                ('transaction_variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collection_sources', to='finance.financetransactionvariant')),
                ('treasury_department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collection_sources', to='departments.department')),
            ],
            options={
                'ordering': ('-source_date', '-pk'),
                'permissions': (('view_collection_register', 'Can view the Treasury collection and deposit register'), ('prepare_collections', 'Can record actual Treasury collection receipts'), ('prepare_collection_deposits', 'Can allocate collected receipts to actual bank deposits'), ('review_collections', 'Can independently review collection and deposit sources')),
            },
        ),
        migrations.CreateModel(
            name='CollectionPostingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('jev_number', models.CharField(max_length=60)),
                ('jev_date', models.DateField()),
                ('finance_department_id', models.PositiveBigIntegerField()),
                ('finance_department_label', models.CharField(max_length=160)),
                ('posting_rule_snapshot', models.JSONField(default=dict)),
                ('posting_rule_checksum', models.CharField(max_length=64)),
                ('payload', models.JSONField(default=dict)),
                ('payload_checksum', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Waiting for JEV creation'), ('materialized', 'Draft JEV created'), ('posted', 'JEV posted'), ('failed', 'Needs intervention'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('accounting_entry_public_id', models.UUIDField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('materialized_at', models.DateTimeField(blank=True, null=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('posting_rule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collection_posting_requests', to='finance.financepostingrule')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collection_posting_requests', to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posting_requests', to='vouchers.treasurycollectionsource')),
            ],
        ),
        migrations.AddConstraint(
            model_name='treasurycollectionsource',
            constraint=models.UniqueConstraint(fields=('treasury_department', 'kind', 'book_reference', 'document_reference', 'version'), name='unique_collection_document_version'),
        ),
        migrations.AddConstraint(
            model_name='treasurycollectionsource',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='positive_collection_source_amount'),
        ),
        migrations.AddConstraint(
            model_name='collectionpostingrequest',
            constraint=models.UniqueConstraint(fields=('source', 'version'), name='unique_collection_posting_version'),
        ),
        migrations.AddConstraint(
            model_name='collectionpostingrequest',
            constraint=models.UniqueConstraint(fields=('finance_department_id', 'jev_number'), name='unique_collection_jev_number'),
        ),
    ]
