# Generated by Django 5.2.17 on 2026-09-12 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0029_collection_sources'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='treasurycollectionsource',
            name='withdrawal_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='treasurycollectionsource',
            name='withdrawn_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='treasurycollectionsource',
            name='withdrawn_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='withdrawn_collection_sources', to=settings.AUTH_USER_MODEL),
        ),
    ]
