# Generated by Django 5.2.17 on 2026-09-12 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0030_collection_sources'),
    ]

    operations = [
        migrations.AddField(
            model_name='treasurycollectionsource',
            name='correction_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='corrections', to='vouchers.treasurycollectionsource'),
        ),
        migrations.AlterField(
            model_name='treasurycollectionsource',
            name='kind',
            field=models.CharField(choices=[('receipt', 'Collection receipt'), ('deposit', 'Deposit of collections'), ('correction', 'Posted source correction')], max_length=16),
        ),
    ]
