# Generated by Django 5.2.17 on 2026-09-15 12:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0032_collection_sources'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionChequeClearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('version', models.PositiveIntegerField()),
                ('cleared_on', models.DateField()),
                ('snapshot', models.JSONField(default=dict)),
                ('checksum', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('proposed', 'For independent review'), ('approved', 'Bank clearing confirmed'), ('rejected', 'Returned for correction'), ('withdrawn', 'Clearing evidence withdrawn')], default='proposed', max_length=16)),
                ('prepared_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_reason', models.TextField(blank=True)),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('withdrawal_reason', models.TextField(blank=True)),
                ('deposit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deposit_clearances', to='vouchers.treasurycollectionsource')),
                ('prepared_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cheque_clearances', to='vouchers.treasurycollectionsource')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('withdrawn_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-version',),
                'constraints': [models.UniqueConstraint(fields=('receipt', 'version'), name='unique_cheque_clearance_version')],
            },
        ),
    ]
