# Generated by Django 5.2.17 on 2026-09-15 13:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0005_internal_howtos'),
        ('vouchers', '0033_cheque_clearance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentPresentationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('observed_on', models.DateField()),
                ('reason', models.TextField()),
                ('evidence_reference', models.TextField()),
                ('snapshot', models.JSONField()),
                ('checksum', models.CharField(max_length=64)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('is_open', models.BooleanField(default=True)),
                ('state_version', models.PositiveIntegerField(default=1)),
                ('active_instrument', models.GeneratedField(db_persist=True, expression=models.Case(models.When(is_open=True, then=models.F('instrument_id')), default=None), null=True, output_field=models.BigIntegerField(), unique=True)),
                ('accounting_department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='presentation_reviews', to='departments.department')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='presentation_reports', to='vouchers.paymentinstrument')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_presentations', to=settings.AUTH_USER_MODEL)),
                ('treasury_department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='presentation_reports', to='departments.department')),
            ],
            options={
                'ordering': ('-reported_at', '-pk'),
                'permissions': (('record_payment_presentations', 'Can record cheque presentation reports'), ('review_payment_presentations', 'Can independently review cheque presentation reports')),
            },
        ),
        migrations.CreateModel(
            name='PaymentPresentationDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('outcome', models.CharField(choices=[('pending', 'Awaiting bank evidence'), ('paid', 'Bank confirms payment — reconcile'), ('returned', 'Bank confirms return — reconcile'), ('not_paid', 'Bank confirms not paid — resolve'), ('mistaken', 'Mistaken report — resolve')], max_length=16)),
                ('effective_on', models.DateField()),
                ('evidence_reference', models.TextField()),
                ('reason', models.TextField()),
                ('next_action', models.TextField(blank=True)),
                ('snapshot', models.JSONField()),
                ('checksum', models.CharField(max_length=64)),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='presentation_decisions', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decisions', to='vouchers.paymentpresentationreport')),
            ],
            options={
                'ordering': ('version',),
                'constraints': [models.UniqueConstraint(fields=('report', 'version'), name='unique_presentation_decision_version')],
            },
        ),
    ]
