# Generated by Django 5.2.17 on 2026-09-15 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0034_payment_presentations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentpresentationdecision',
            name='outcome',
            field=models.CharField(choices=[('pending', 'Awaiting bank evidence'), ('paid', 'Bank confirms payment — reconcile'), ('returned', 'Bank confirms return — reconcile'), ('not_paid', 'Bank confirms not paid — resolve'), ('mistaken', 'Mistaken report — resolve'), ('paid_reconciled', 'Payment reconciled to original source'), ('return_linked', 'Return resolved through Accounting')], max_length=16),
        ),
    ]
