# Generated by Django 5.2.17 on 2026-09-15 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0035_presentation_resolution_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='treasurycollectionsource',
            name='return_deposit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deposit_returns', to='vouchers.treasurycollectionsource'),
        ),
        migrations.AddField(
            model_name='treasurycollectionsource',
            name='return_receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cheque_returns', to='vouchers.treasurycollectionsource'),
        ),
        migrations.AlterField(
            model_name='treasurycollectionsource',
            name='kind',
            field=models.CharField(choices=[('receipt', 'Collection receipt'), ('deposit', 'Deposit of collections'), ('correction', 'Posted source correction'), ('cheque_return', 'Incoming cheque bank return')], max_length=16),
        ),
        migrations.AlterField(
            model_name='treasurycollectionsource',
            name='status',
            field=models.CharField(choices=[('proposed', 'For independent review'), ('approved', 'Approved; Accounting posting'), ('rejected', 'Returned for correction'), ('posted', 'Posted'), ('withdrawn', 'Withdrawn before posting'), ('corrected', 'Retired by posted exact correction')], default='proposed', max_length=16),
        ),
        migrations.AlterField(
            model_name='voucherpostingrequest',
            name='kind',
            field=models.CharField(choices=[('collection', 'Record an actual Treasury collection'), ('deposit', 'Deposit previously recorded collections'), ('cheque_return', 'Record an incoming cheque bank debit'), ('recognition', 'Recognize expense, asset, or payable'), ('adjustment', 'Adjust an earlier recognition'), ('liquidation', 'Record liquidation'), ('payment', 'Settle payable / record payment'), ('remittance', 'Remit deductions or withholdings'), ('cancellation', 'Record cancellation effect'), ('reversal', 'Reverse an earlier entry'), ('replacement', 'Record replacement effect')], default='recognition', max_length=20),
        ),
        migrations.AddField(
            model_name='treasurycollectionsource',
            name='active_return_receipt',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(kind='cheque_return', status__in=('proposed', 'approved', 'posted'), then=models.F('return_receipt_id')), default=models.Value(None)), null=True, output_field=models.BigIntegerField(), unique=True),
        ),
    ]
