# Generated by Django 5.2.17 on 2026-09-15 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0036_treasurycollectionsource_return_deposit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='treasurycollectionsource',
            name='redemption_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='treasurycollectionsource',
            name='redemption_return',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='redemption_receipts', to='vouchers.treasurycollectionsource'),
        ),
        migrations.AddField(
            model_name='treasurycollectionsource',
            name='active_redemption_return',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(kind='receipt', redemption_active=True, status__in=('proposed', 'approved', 'posted'), then=models.F('redemption_return_id')), default=models.Value(None)), null=True, output_field=models.BigIntegerField(), unique=True),
        ),
    ]
