# Generated by Django 5.2.17 on 2026-09-15 14:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracepoint', '0005_packethandoff_is_terminal_receipt_and_more'),
        ('vouchers', '0037_treasurycollectionsource_redemption_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionChequeCustodyLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('snapshot', models.JSONField()),
                ('checksum', models.CharField(max_length=64)),
                ('linked_at', models.DateTimeField(auto_now_add=True)),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('withdrawal_reason', models.TextField(blank=True)),
                ('active_source', models.GeneratedField(db_persist=True, expression=models.Case(models.When(then=models.F('source_id'), withdrawn_at__isnull=True), default=models.Value(None)), null=True, output_field=models.BigIntegerField(), unique=True)),
                ('active_item', models.GeneratedField(db_persist=True, expression=models.Case(models.When(then=models.F('item_id'), withdrawn_at__isnull=True), default=models.Value(None)), null=True, output_field=models.BigIntegerField(), unique=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cheque_custody_links', to='tracepoint.packetitem')),
                ('linked_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='linked_cheque_custody', to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='custody_links', to='vouchers.treasurycollectionsource')),
                ('withdrawn_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='withdrawn_cheque_custody', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('version',),
                'permissions': (('link_collection_custody', 'Can link incoming cheque sources to TracePoint custody'),),
                'constraints': [models.UniqueConstraint(fields=('source', 'version'), name='unique_cheque_custody_version')],
            },
        ),
    ]
