# Generated by Django 5.2 on 2025-06-09 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='dashboard_template',
            field=models.CharField(blank=True, help_text="Path to the dashboard template, e.g., 'home/authed/dashboards/hr.htmlMake sure to include the full path relative to the templates directory and create corresponding templates.", max_length=255),
        ),
        migrations.AddField(
            model_name='department',
            name='dashboard_view_name',
            field=models.CharField(blank=True, help_text="Enter the name of the view used for this department's dashboard (e.g., 'hr_dashboard')", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='slug',
            field=models.SlugField(blank=True, help_text="Unique short code like 'hr', 'gso', 'acctg'", null=True),
        ),
    ]
