# Generated by Django 5.2 on 2025-06-09 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0003_department_dashboard_template_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='dashboard_template',
            field=models.CharField(blank=True, help_text="Path to the dashboard template, e.g., 'home/authed/dashboards/hr.html'\nMake sure to include the full path relative to the templates directory and create corresponding templates.", max_length=255),
        ),
        migrations.AlterField(
            model_name='department',
            name='slug',
            field=models.SlugField(blank=True, help_text="Unique short code like 'hr', 'gso', 'acctg'", null=True, unique=True),
        ),
    ]
