# Generated by Django 5.2.17 on 2026-08-28 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0004_alter_department_dashboard_template_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InternalHowTo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=120)),
                ('version', models.PositiveIntegerField(default=1)),
                ('title', models.CharField(max_length=180)),
                ('summary', models.TextField()),
                ('required_permission', models.CharField(blank=True, help_text='Optional app_label.codename. Leave blank for every employee currently assigned to this department.', max_length=150)),
                ('page_patterns', models.JSONField(blank=True, default=list, help_text='Optional named-route patterns such as accounting:opening_*; blank makes the guide department-wide.')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('retired', 'Retired')], default='draft', max_length=12)),
                ('sort_order', models.PositiveSmallIntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_internal_how_tos', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='internal_how_tos', to='departments.department')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_internal_how_tos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('sort_order', 'title', '-version'),
                'permissions': (('manage_internal_how_tos', 'Can manage department internal how-to guides'),),
            },
        ),
        migrations.CreateModel(
            name='InternalHowToStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField()),
                ('title', models.CharField(max_length=180)),
                ('instruction', models.TextField()),
                ('expected_result', models.TextField(blank=True)),
                ('caution', models.TextField(blank=True)),
                ('action_label', models.CharField(blank=True, max_length=80)),
                ('action_route_name', models.CharField(blank=True, help_text='Optional named URL without arguments, for example accounting:opening_workspace.', max_length=150)),
                ('how_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='steps', to='departments.internalhowto')),
            ],
            options={
                'ordering': ('position', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='InternalHowToStepCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='internal_howto_completions', to='departments.department')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='completions', to='departments.internalhowtostep')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_howto_step_completions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('completed_at', 'pk'),
            },
        ),
        migrations.AddConstraint(
            model_name='internalhowto',
            constraint=models.UniqueConstraint(fields=('department', 'slug', 'version'), name='unique_internal_howto_version'),
        ),
        migrations.AddConstraint(
            model_name='internalhowto',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'published')), fields=('department', 'slug'), name='unique_published_internal_howto'),
        ),
        migrations.AddConstraint(
            model_name='internalhowtostep',
            constraint=models.UniqueConstraint(fields=('how_to', 'position'), name='unique_internal_howto_step_position'),
        ),
        migrations.AddConstraint(
            model_name='internalhowtostepcompletion',
            constraint=models.UniqueConstraint(fields=('user', 'step'), name='unique_user_internal_howto_step'),
        ),
    ]
