# Generated by Django 5.2.17 on 2026-08-28 01:26

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_id', models.PositiveBigIntegerField(db_index=True)),
                ('department_label', models.CharField(max_length=160)),
                ('fiscal_year', models.PositiveSmallIntegerField()),
                ('period_number', models.PositiveSmallIntegerField(help_text='Usually 1–12; period 13 may be used for year-end adjustments.')),
                ('label', models.CharField(max_length=80)),
                ('starts_on', models.DateField()),
                ('ends_on', models.DateField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=12)),
                ('closed_by_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('closed_by_label', models.CharField(blank=True, max_length=160)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-fiscal_year', 'period_number'),
                'constraints': [models.UniqueConstraint(fields=('department_id', 'fiscal_year', 'period_number'), name='unique_accounting_period'), models.CheckConstraint(condition=models.Q(('period_number__gte', 1), ('period_number__lte', 13)), name='valid_accounting_period_number')],
            },
        ),
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_id', models.PositiveBigIntegerField(db_index=True)),
                ('department_label', models.CharField(max_length=160)),
                ('code', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('code',),
                'constraints': [models.UniqueConstraint(fields=('department_id', 'code'), name='unique_accounting_fund')],
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_id', models.PositiveBigIntegerField(db_index=True)),
                ('department_label', models.CharField(max_length=160)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('reference', models.CharField(max_length=60)),
                ('entry_date', models.DateField()),
                ('source_type', models.CharField(choices=[('manual', 'Manual journal'), ('voucher', 'Voucher'), ('adjustment', 'Adjusting entry'), ('opening', 'Opening balance')], default='manual', max_length=16)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'For posting'), ('posted', 'Posted'), ('voided', 'Voided')], default='draft', max_length=16)),
                ('created_by_id', models.PositiveBigIntegerField()),
                ('created_by_label', models.CharField(max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_by_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('submitted_by_label', models.CharField(blank=True, max_length=160)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('posted_by_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('posted_by_label', models.CharField(blank=True, max_length=160)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_entries', to='accounting.fund')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_entries', to='accounting.accountingperiod')),
            ],
            options={
                'ordering': ('-entry_date', '-pk'),
                'permissions': (('view_accounting_workspace', 'Can view the accounting workspace'), ('manage_accounting_setup', 'Can manage accounting setup'), ('prepare_journal_entries', 'Can prepare journal entries'), ('post_journal_entries', 'Can independently post journal entries'), ('view_general_ledger', 'Can view the general ledger and trial balance')),
            },
        ),
        migrations.CreateModel(
            name='AccountingAuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_id', models.PositiveBigIntegerField(db_index=True)),
                ('department_label', models.CharField(max_length=160)),
                ('action', models.CharField(max_length=40)),
                ('actor_id', models.PositiveBigIntegerField()),
                ('actor_label', models.CharField(max_length=160)),
                ('reason', models.TextField(blank=True)),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to='accounting.journalentry')),
            ],
            options={
                'ordering': ('-created_at', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='LedgerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_id', models.PositiveBigIntegerField(db_index=True)),
                ('department_label', models.CharField(max_length=160)),
                ('code', models.CharField(max_length=40)),
                ('title', models.CharField(max_length=180)),
                ('account_type', models.CharField(choices=[('asset', 'Asset'), ('liability', 'Liability'), ('equity', 'Equity'), ('revenue', 'Revenue'), ('expense', 'Expense')], max_length=16)),
                ('normal_balance', models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], max_length=8)),
                ('allow_posting', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='accounting.ledgeraccount')),
            ],
            options={
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='ResponsibilityCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_id', models.PositiveBigIntegerField(db_index=True)),
                ('department_label', models.CharField(max_length=160)),
                ('code', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('code',),
                'constraints': [models.UniqueConstraint(fields=('department_id', 'code'), name='unique_responsibility_center')],
            },
        ),
        migrations.CreateModel(
            name='JournalLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveSmallIntegerField()),
                ('debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('memo', models.CharField(blank=True, max_length=255)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.journalentry')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_lines', to='accounting.ledgeraccount')),
                ('responsibility_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journal_lines', to='accounting.responsibilitycenter')),
            ],
            options={
                'ordering': ('sequence', 'pk'),
            },
        ),
        migrations.AddConstraint(
            model_name='journalentry',
            constraint=models.UniqueConstraint(fields=('department_id', 'reference'), name='unique_journal_reference'),
        ),
        migrations.AddConstraint(
            model_name='ledgeraccount',
            constraint=models.UniqueConstraint(fields=('department_id', 'code'), name='unique_ledger_account'),
        ),
        migrations.AddConstraint(
            model_name='journalline',
            constraint=models.UniqueConstraint(fields=('entry', 'sequence'), name='unique_journal_line_sequence'),
        ),
        migrations.AddConstraint(
            model_name='journalline',
            constraint=models.CheckConstraint(condition=models.Q(('credit__gte', 0), ('debit__gte', 0)), name='nonnegative_journal_amounts'),
        ),
    ]
