# Generated by Django 5.2.17 on 2026-08-28 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostingMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_id', models.PositiveBigIntegerField(db_index=True)),
                ('department_label', models.CharField(max_length=160)),
                ('category', models.CharField(choices=[('payable', 'Voucher net payable'), ('deduction', 'Deduction / withholding'), ('bank', 'Bank account')], max_length=16)),
                ('source_code', models.CharField(help_text='The controlled code used by Finance Setup or the Voucher Workbench.', max_length=80)),
                ('label', models.CharField(max_length=160)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('category', 'source_code'),
            },
        ),
        migrations.AddField(
            model_name='journalentry',
            name='source_reference',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='source_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddConstraint(
            model_name='journalentry',
            constraint=models.UniqueConstraint(fields=('department_id', 'source_type', 'source_reference'), name='unique_accounting_source_reference'),
        ),
        migrations.AddField(
            model_name='postingmapping',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posting_mappings', to='accounting.ledgeraccount'),
        ),
        migrations.AddConstraint(
            model_name='postingmapping',
            constraint=models.UniqueConstraint(fields=('department_id', 'category', 'source_code'), name='unique_accounting_posting_mapping'),
        ),
    ]
