# Generated by Django 5.2.17 on 2026-08-28 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_postingmapping_journalentry_source_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='reversal_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversal_entries', to='accounting.journalentry'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='reversal_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='source_type',
            field=models.CharField(choices=[('manual', 'Manual journal'), ('voucher', 'Voucher'), ('adjustment', 'Adjusting entry'), ('reversal', 'Reversing entry'), ('opening', 'Opening balance')], default='manual', max_length=16),
        ),
    ]
