# Generated by Django 5.2.17 on 2026-08-28 11:19

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_fiscal_year_classification_foundation'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpeningBalanceBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_id', models.PositiveBigIntegerField(db_index=True)),
                ('department_label', models.CharField(max_length=160)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=180)),
                ('source_reference', models.CharField(max_length=120)),
                ('source_filename', models.CharField(blank=True, max_length=255)),
                ('source_checksum', models.CharField(blank=True, max_length=64)),
                ('import_schema_version', models.PositiveSmallIntegerField(default=1)),
                ('expected_row_count', models.PositiveIntegerField(default=0)),
                ('expected_debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('expected_credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('is_zero_balance_declaration', models.BooleanField(default=False)),
                ('validation_summary', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('draft', 'Draft staging'), ('validated', 'Validated'), ('for_review', 'For review'), ('approved', 'Approved for posting'), ('posted', 'Posted; reconciliation pending'), ('reconciled', 'Reconciled'), ('returned', 'Returned for correction')], default='draft', max_length=20)),
                ('created_by_id', models.PositiveBigIntegerField()),
                ('created_by_label', models.CharField(max_length=160)),
                ('submitted_by_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('submitted_by_label', models.CharField(blank=True, max_length=160)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('approved_by_label', models.CharField(blank=True, max_length=160)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('posted_by_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('posted_by_label', models.CharField(blank=True, max_length=160)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('reconciled_by_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('reconciled_by_label', models.CharField(blank=True, max_length=160)),
                ('reconciled_at', models.DateTimeField(blank=True, null=True)),
                ('state_version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opening_balance_batches', to='accounting.fiscalyear')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opening_balance_batches', to='accounting.accountingperiod')),
            ],
            options={
                'ordering': ('-fiscal_year__year', '-created_at', '-pk'),
                'permissions': (('prepare_opening_balances', 'Can stage and correct opening balances'), ('approve_opening_balances', 'Can independently approve opening balances'), ('post_opening_balances', 'Can post and reconcile opening balances')),
            },
        ),
        migrations.CreateModel(
            name='OpeningBalanceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_id', models.PositiveBigIntegerField(db_index=True)),
                ('department_label', models.CharField(max_length=160)),
                ('action', models.CharField(max_length=40)),
                ('actor_id', models.PositiveBigIntegerField()),
                ('actor_label', models.CharField(max_length=160)),
                ('reason', models.TextField(blank=True)),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='accounting.openingbalancebatch')),
            ],
            options={
                'ordering': ('-created_at', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='OpeningBalancePosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', models.DecimalField(decimal_places=2, max_digits=20)),
                ('credit', models.DecimalField(decimal_places=2, max_digits=20)),
                ('row_count', models.PositiveIntegerField()),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='postings', to='accounting.openingbalancebatch')),
                ('entry', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='opening_balance_posting', to='accounting.journalentry')),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opening_balance_postings', to='accounting.fund')),
            ],
            options={
                'ordering': ('fund__code', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='OpeningBalanceRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField()),
                ('raw_fund_code', models.CharField(max_length=80)),
                ('raw_account_code', models.CharField(max_length=80)),
                ('raw_responsibility_center_code', models.CharField(blank=True, max_length=80)),
                ('raw_debit', models.CharField(blank=True, max_length=80)),
                ('raw_credit', models.CharField(blank=True, max_length=80)),
                ('subsidiary_reference', models.CharField(blank=True, max_length=160)),
                ('memo', models.CharField(blank=True, max_length=255)),
                ('debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('validation_status', models.CharField(choices=[('pending', 'Pending validation'), ('valid', 'Valid'), ('error', 'Needs correction')], default='pending', max_length=12)),
                ('validation_errors', models.JSONField(blank=True, default=list)),
                ('correction_version', models.PositiveIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='opening_balance_rows', to='accounting.ledgeraccount')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='accounting.openingbalancebatch')),
                ('fund', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='opening_balance_rows', to='accounting.fund')),
                ('responsibility_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='opening_balance_rows', to='accounting.responsibilitycenter')),
            ],
            options={
                'ordering': ('row_number', 'pk'),
            },
        ),
        migrations.AddConstraint(
            model_name='openingbalancebatch',
            constraint=models.UniqueConstraint(fields=('department_id', 'fiscal_year', 'source_reference'), name='unique_opening_source_reference'),
        ),
        migrations.AddConstraint(
            model_name='openingbalanceposting',
            constraint=models.UniqueConstraint(fields=('batch', 'fund'), name='unique_opening_posting_per_fund'),
        ),
        migrations.AddConstraint(
            model_name='openingbalancerow',
            constraint=models.UniqueConstraint(fields=('batch', 'row_number'), name='unique_opening_batch_row'),
        ),
        migrations.AddConstraint(
            model_name='openingbalancerow',
            constraint=models.CheckConstraint(condition=models.Q(('credit__gte', 0), ('debit__gte', 0)), name='nonnegative_opening_amounts'),
        ),
    ]
