# Generated by Django 5.2.17 on 2026-08-30 15:27

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_opening_balance_control_intake'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlAccountReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_id', models.PositiveBigIntegerField(db_index=True)),
                ('department_label', models.CharField(max_length=160)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('as_of_date', models.DateField()),
                ('is_balanced', models.BooleanField(default=False)),
                ('absolute_difference_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('result_snapshot', models.JSONField(default=dict)),
                ('result_checksum', models.CharField(max_length=64)),
                ('prepared_by_id', models.PositiveBigIntegerField()),
                ('prepared_by_label', models.CharField(max_length=160)),
                ('prepared_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-as_of_date', '-prepared_at', '-pk'),
                'permissions': (('reconcile_control_accounts', 'Can record payable and withholding control reconciliations'),),
            },
        ),
        migrations.CreateModel(
            name='JournalSubsidiaryLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('payable', 'Payable by claimant / payee'), ('withholding', 'Deduction / withholding payable')], max_length=16)),
                ('reference_key', models.CharField(help_text='Stable payee key, deduction code, or other governed subsidiary identity.', max_length=100)),
                ('reference_label', models.CharField(max_length=220)),
                ('source_code', models.CharField(max_length=80)),
                ('source_reference', models.CharField(max_length=120)),
                ('debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('source_snapshot', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subsidiary_lines', to='accounting.journalentry')),
                ('journal_line', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='subsidiary_posting', to='accounting.journalline')),
            ],
            options={
                'ordering': ('entry__entry_date', 'entry_id', 'journal_line__sequence'),
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('credit', 0), ('debit__gt', 0)), models.Q(('credit__gt', 0), ('debit', 0)), _connector='OR'), name='one_sided_positive_subsidiary_amount')],
            },
        ),
    ]
