# Generated by Django 5.2.17 on 2026-08-30 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_controlaccountreconciliation_journalsubsidiaryline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='source_type',
            field=models.CharField(choices=[('manual', 'Manual journal'), ('voucher', 'Voucher'), ('remittance', 'Deduction / withholding remittance'), ('adjustment', 'Adjusting entry'), ('reversal', 'Reversing entry'), ('opening', 'Opening balance')], default='manual', max_length=16),
        ),
    ]
