# Generated by Django 5.2.17 on 2026-08-30 16:24

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_alter_journalentry_source_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankStatementBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_id', models.PositiveBigIntegerField(db_index=True)),
                ('department_label', models.CharField(max_length=160)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('statement_reference', models.CharField(max_length=100)),
                ('bank_account_code', models.CharField(max_length=80)),
                ('bank_name', models.CharField(max_length=160)),
                ('account_number_masked', models.CharField(blank=True, max_length=40)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('received_on', models.DateField()),
                ('opening_balance', models.DecimalField(decimal_places=2, max_digits=18)),
                ('closing_balance', models.DecimalField(decimal_places=2, max_digits=18)),
                ('expected_row_count', models.PositiveIntegerField()),
                ('expected_deposits', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('expected_withdrawals', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('status', models.CharField(choices=[('draft', 'Draft / staging'), ('validated', 'Statement controls validated'), ('for_review', 'For independent review'), ('reconciled', 'Reconciled'), ('returned', 'Returned for correction')], default='draft', max_length=16)),
                ('source_version', models.PositiveIntegerField(default=0)),
                ('source_filename', models.CharField(blank=True, max_length=255)),
                ('source_checksum', models.CharField(blank=True, max_length=64)),
                ('validation_summary', models.JSONField(blank=True, default=dict)),
                ('created_by_id', models.PositiveBigIntegerField()),
                ('created_by_label', models.CharField(max_length=160)),
                ('submitted_by_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('submitted_by_label', models.CharField(blank=True, max_length=160)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reconciled_by_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('reconciled_by_label', models.CharField(blank=True, max_length=160)),
                ('reconciled_at', models.DateTimeField(blank=True, null=True)),
                ('reconciliation_checksum', models.CharField(blank=True, max_length=64)),
                ('state_version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bank_statement_batches', to='accounting.fund')),
            ],
            options={
                'ordering': ('-period_end', 'bank_account_code', '-pk'),
                'permissions': (('view_bank_reconciliation', 'Can view bank reconciliation workspaces'), ('prepare_bank_reconciliation', 'Can stage and match bank statements'), ('approve_bank_reconciliation', 'Can independently approve bank reconciliations'), ('export_bank_reconciliation', 'Can export bank reconciliation evidence')),
            },
        ),
        migrations.CreateModel(
            name='BankReconciliationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_id', models.PositiveBigIntegerField(db_index=True)),
                ('department_label', models.CharField(max_length=160)),
                ('action', models.CharField(max_length=40)),
                ('actor_id', models.PositiveBigIntegerField()),
                ('actor_label', models.CharField(max_length=160)),
                ('reason', models.TextField(blank=True)),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='accounting.bankstatementbatch')),
            ],
            options={
                'ordering': ('-created_at', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='BankOutstandingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('outstanding_deposit', 'Deposit in transit'), ('outstanding_check', 'Outstanding check / withdrawal')], max_length=24)),
                ('explanation', models.TextField()),
                ('evidence_reference', models.CharField(max_length=160)),
                ('expected_clearance_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('superseded', 'Superseded')], default='active', max_length=12)),
                ('source_snapshot', models.JSONField(default=dict)),
                ('source_checksum', models.CharField(max_length=64)),
                ('created_by_id', models.PositiveBigIntegerField()),
                ('created_by_label', models.CharField(max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('superseded_at', models.DateTimeField(blank=True, null=True)),
                ('journal_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bank_outstanding_items', to='accounting.journalline')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outstanding_items', to='accounting.bankstatementbatch')),
            ],
            options={
                'ordering': ('journal_line__entry__entry_date', 'journal_line_id', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='BankStatementRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_version', models.PositiveIntegerField()),
                ('row_number', models.PositiveIntegerField()),
                ('transaction_date', models.DateField()),
                ('bank_reference', models.CharField(blank=True, max_length=120)),
                ('description', models.CharField(max_length=255)),
                ('withdrawal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('deposit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('running_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('row_checksum', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rows', to='accounting.bankstatementbatch')),
            ],
            options={
                'ordering': ('source_version', 'row_number', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='BankStatementMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('auto', 'Unique exact suggestion'), ('manual', 'Guided manual match')], max_length=12)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('superseded', 'Superseded')], default='active', max_length=12)),
                ('source_snapshot', models.JSONField(default=dict)),
                ('source_checksum', models.CharField(max_length=64)),
                ('created_by_id', models.PositiveBigIntegerField()),
                ('created_by_label', models.CharField(max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('superseded_at', models.DateTimeField(blank=True, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matches', to='accounting.bankstatementbatch')),
                ('journal_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bank_statement_matches', to='accounting.journalline')),
                ('statement_row', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matches', to='accounting.bankstatementrow')),
            ],
            options={
                'ordering': ('statement_row__row_number', '-created_at', '-pk'),
            },
        ),
        migrations.AddConstraint(
            model_name='bankstatementbatch',
            constraint=models.UniqueConstraint(fields=('department_id', 'bank_account_code', 'statement_reference'), name='unique_bank_statement_reference'),
        ),
        migrations.AddConstraint(
            model_name='bankoutstandingitem',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('batch', 'journal_line'), name='unique_active_bank_outstanding_item'),
        ),
        migrations.AddConstraint(
            model_name='bankstatementrow',
            constraint=models.UniqueConstraint(fields=('batch', 'source_version', 'row_number'), name='unique_statement_version_row'),
        ),
        migrations.AddConstraint(
            model_name='bankstatementrow',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('deposit', 0), ('withdrawal__gt', 0)), models.Q(('deposit__gt', 0), ('withdrawal', 0)), _connector='OR'), name='one_sided_bank_statement_amount'),
        ),
        migrations.AddConstraint(
            model_name='bankstatementmatch',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('statement_row',), name='unique_active_statement_row_match'),
        ),
        migrations.AddConstraint(
            model_name='bankstatementmatch',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('journal_line',), name='unique_active_bank_journal_match'),
        ),
    ]
