# Generated by Django 5.2.17 on 2026-08-31 02:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_bank_outstanding_carry_forward'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodClosePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_id', models.PositiveBigIntegerField(db_index=True)),
                ('department_label', models.CharField(max_length=160)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('version', models.PositiveSmallIntegerField()),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('mode', models.CharField(choices=[('observe', 'Observe and explain exceptions'), ('enforce', 'Enforce accepted close gates')], default='observe', max_length=12)),
                ('require_control_reconciliation', models.BooleanField(default=True)),
                ('require_bank_reconciliation', models.BooleanField(default=True)),
                ('require_statement_reports', models.BooleanField(default=True)),
                ('require_handoff_clearance', models.BooleanField(default=True)),
                ('require_year_end_closing_entries', models.BooleanField(default=True)),
                ('authority_reference', models.TextField(blank=True)),
                ('local_acceptance_note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Editable draft'), ('submitted', 'For independent review'), ('returned', 'Returned for correction'), ('starter', 'Controlled starter'), ('active', 'Locally accepted active policy'), ('superseded', 'Superseded')], default='draft', max_length=16)),
                ('snapshot_checksum', models.CharField(blank=True, max_length=64)),
                ('created_by_id', models.PositiveBigIntegerField()),
                ('created_by_label', models.CharField(max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_by_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('submitted_by_label', models.CharField(blank=True, max_length=160)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('reviewed_by_label', models.CharField(blank=True, max_length=160)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='successors', to='accounting.periodclosepolicy')),
            ],
            options={
                'ordering': ('-version', '-pk'),
                'permissions': (('manage_period_close_policies', 'Can prepare period-close policies'), ('approve_period_close_policies', 'Can independently approve period-close policies')),
            },
        ),
        migrations.CreateModel(
            name='PeriodCloseRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_id', models.PositiveBigIntegerField(db_index=True)),
                ('department_label', models.CharField(max_length=160)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('version', models.PositiveSmallIntegerField()),
                ('policy_snapshot', models.JSONField(default=dict)),
                ('policy_checksum', models.CharField(max_length=64)),
                ('checklist_snapshot', models.JSONField(default=dict)),
                ('checklist_checksum', models.CharField(max_length=64)),
                ('adjustment_review_note', models.TextField()),
                ('evidence_reference', models.TextField()),
                ('preparer_note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft checklist'), ('returned', 'Returned for correction'), ('submitted', 'For independent close review'), ('closed', 'Period closed'), ('reopen_requested', 'Reopen requested'), ('reopened', 'Period reopened')], default='draft', max_length=24)),
                ('prepared_by_id', models.PositiveBigIntegerField()),
                ('prepared_by_label', models.CharField(max_length=160)),
                ('prepared_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_by_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('submitted_by_label', models.CharField(blank=True, max_length=160)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('decided_by_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('decided_by_label', models.CharField(blank=True, max_length=160)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True)),
                ('reopen_requested_by_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('reopen_requested_by_label', models.CharField(blank=True, max_length=160)),
                ('reopen_requested_at', models.DateTimeField(blank=True, null=True)),
                ('reopen_reason', models.TextField(blank=True)),
                ('reopen_authority_reference', models.TextField(blank=True)),
                ('reopened_by_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('reopened_by_label', models.CharField(blank=True, max_length=160)),
                ('reopened_at', models.DateTimeField(blank=True, null=True)),
                ('reopen_review_note', models.TextField(blank=True)),
                ('state_version', models.PositiveIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='close_runs', to='accounting.accountingperiod')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='close_runs', to='accounting.periodclosepolicy')),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='successors', to='accounting.periodcloserun')),
            ],
            options={
                'ordering': ('-period__fiscal_year', '-period__period_number', '-version'),
                'permissions': (('prepare_period_close', 'Can prepare and submit period close checklists'), ('approve_period_close', 'Can independently approve period close'), ('reopen_period', 'Can independently decide period reopen requests'), ('export_period_close', 'Can export period close evidence')),
            },
        ),
        migrations.CreateModel(
            name='PeriodCloseEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_id', models.PositiveBigIntegerField(db_index=True)),
                ('department_label', models.CharField(max_length=160)),
                ('action', models.CharField(max_length=60)),
                ('actor_id', models.PositiveBigIntegerField()),
                ('actor_label', models.CharField(max_length=160)),
                ('reason', models.TextField(blank=True)),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='accounting.periodcloserun')),
            ],
            options={
                'ordering': ('-created_at', '-pk'),
            },
        ),
        migrations.AddConstraint(
            model_name='periodclosepolicy',
            constraint=models.UniqueConstraint(fields=('department_id', 'version'), name='unique_period_close_policy_version'),
        ),
        migrations.AddConstraint(
            model_name='periodclosepolicy',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('department_id',), name='one_active_period_close_policy'),
        ),
        migrations.AddConstraint(
            model_name='periodcloserun',
            constraint=models.UniqueConstraint(fields=('period', 'version'), name='unique_period_close_run_version'),
        ),
    ]
