# Generated by Django 5.2.17 on 2026-09-09 14:16

from django.db import migrations, models


def require_unique_active_matches(apps, schema_editor):
    matches = apps.get_model('accounting', 'BankStatementMatch').objects.using(schema_editor.connection.alias).filter(status='active')
    for field in ('statement_row_id', 'journal_line_id'):
        if matches.values(field).annotate(count=models.Count('pk')).filter(count__gt=1).exists():
            raise RuntimeError(
                'Duplicate active bank matches require controlled investigation before this migration. '
                'No match or reconciliation evidence has been deduplicated or rewritten.'
            )


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0010_periodclosepolicy_periodcloserun_periodcloseevent_and_more'),
    ]

    operations = [
        migrations.RunPython(require_unique_active_matches, migrations.RunPython.noop),
        migrations.RemoveConstraint(
            model_name='bankstatementmatch',
            name='unique_active_statement_row_match',
        ),
        migrations.RemoveConstraint(
            model_name='bankstatementmatch',
            name='unique_active_bank_journal_match',
        ),
        migrations.AddField(
            model_name='bankstatementmatch',
            name='active_identity_marker',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(status='active', then=models.Value(1)), default=models.Value(None)), null=True, output_field=models.PositiveSmallIntegerField()),
        ),
        migrations.AddConstraint(
            model_name='bankstatementmatch',
            constraint=models.UniqueConstraint(fields=('statement_row', 'active_identity_marker'), name='unique_active_statement_row_match'),
        ),
        migrations.AddConstraint(
            model_name='bankstatementmatch',
            constraint=models.UniqueConstraint(fields=('journal_line', 'active_identity_marker'), name='unique_active_bank_journal_match'),
        ),
    ]
