# Generated by Django 5.2.17 on 2026-09-10 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0011_remove_bankstatementmatch_unique_active_statement_row_match_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='source_type',
            field=models.CharField(choices=[('manual', 'Manual journal'), ('voucher', 'Voucher'), ('remittance', 'Deduction / withholding remittance'), ('adjustment', 'Adjusting entry'), ('reversal', 'Reversing entry'), ('opening', 'Opening balance'), ('closing', 'Nominal-account closing transfer')], default='manual', max_length=16),
        ),
    ]
