# Generated by Django 5.2.17 on 2026-09-10 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0013_journal_equity_movement_sources'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalline',
            name='cash_flow_category',
            field=models.CharField(blank=True, choices=[('', 'Not classified / not a cash line'), ('op_taxes', 'Collections from taxpayers'), ('op_transfers', 'National tax allotment / operating transfers received'), ('op_services', 'Business and service receipts'), ('op_interest_in', 'Interest received - operating'), ('op_dividends', 'Dividends received - operating'), ('op_other_in', 'Other operating receipts'), ('op_expenses', 'Operating expenses paid'), ('op_suppliers', 'Operating suppliers and creditors paid'), ('op_employees', 'Employees paid'), ('op_interest_out', 'Interest paid - operating'), ('op_other_out', 'Other operating payments'), ('inv_asset_sales', 'Proceeds from sale of long-term assets'), ('inv_investments_in', 'Investment disposals / maturities'), ('inv_loans_in', 'Collections of loans made'), ('inv_other_in', 'Other investing receipts'), ('inv_assets', 'Acquisition of long-term assets'), ('inv_investments_out', 'Investments purchased'), ('inv_loans_out', 'Loans made'), ('inv_other_out', 'Other investing payments'), ('fin_borrowings', 'Borrowing proceeds'), ('fin_other_in', 'Other financing receipts'), ('fin_principal', 'Loan principal repayments'), ('fin_other_out', 'Other financing payments'), ('exchange', 'Exchange-rate effect on cash / cash equivalents'), ('internal', 'Transfer within cash / cash equivalents')], help_text='For cash/cash-equivalent lines, identify the actual receipt, payment or transfer. Split a mixed-purpose cash line before posting.', max_length=24),
        ),
    ]
