# Generated by Django 5.2.17 on 2026-09-10 02:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0014_cash_flow_line_classification'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashFlowClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_id', models.PositiveBigIntegerField(db_index=True)),
                ('department_label', models.CharField(max_length=160)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('version', models.PositiveIntegerField()),
                ('base_version', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('submitted', 'For independent review'), ('approved', 'Approved'), ('returned', 'Returned')], default='submitted', max_length=12)),
                ('source_snapshot', models.JSONField()),
                ('source_checksum', models.CharField(max_length=64)),
                ('cash_scope_snapshot', models.JSONField()),
                ('allocations', models.JSONField()),
                ('evidence_reference', models.CharField(max_length=255)),
                ('reason', models.TextField()),
                ('proposed_by_id', models.PositiveBigIntegerField()),
                ('proposed_by_label', models.CharField(max_length=160)),
                ('proposed_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('reviewed_by_label', models.CharField(blank=True, max_length=160)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True)),
                ('approval_checksum', models.CharField(blank=True, max_length=64)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_classifications', to='accounting.journalentry')),
            ],
            options={
                'ordering': ('-version',),
            },
        ),
        migrations.CreateModel(
            name='CashFlowClassificationHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='current_head', to='accounting.cashflowclassification')),
                ('entry', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='cash_classification_head', to='accounting.journalentry')),
            ],
        ),
        migrations.AddConstraint(
            model_name='cashflowclassification',
            constraint=models.UniqueConstraint(fields=('entry', 'version'), name='unique_cash_classification_version'),
        ),
    ]
