# Generated by Django 5.2.17 on 2026-09-10 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0015_reviewed_cash_classifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalline',
            name='payable_claim_reference',
            field=models.CharField(blank=True, help_text='Invoice or claim reference for this liability credit.', max_length=120),
        ),
        migrations.AddField(
            model_name='journalline',
            name='payable_origin',
            field=models.ForeignKey(blank=True, help_text='For a liability debit, select the posted claim being settled. Split the debit when settling several claims.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payable_applications', to='accounting.journalline'),
        ),
        migrations.AddField(
            model_name='journalline',
            name='payable_party_key',
            field=models.CharField(blank=True, help_text='Stable supplier/payee key for a newly recognized payable claim.', max_length=100),
        ),
    ]
