# Generated by Django 5.2.17 on 2026-09-10 04:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0016_individual_payable_claims'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayableClaimReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('reservation_key', models.CharField(max_length=100, unique=True)),
                ('case_public_id', models.UUIDField(db_index=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('source_snapshot', models.JSONField()),
                ('source_checksum', models.CharField(max_length=64)),
                ('created_by_id', models.PositiveBigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('released_by_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('release_reason', models.TextField(blank=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claim_reservations', to='accounting.journalline')),
            ],
        ),
        migrations.AddField(
            model_name='journalline',
            name='payable_reservation',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='accounting.payableclaimreservation'),
        ),
    ]
