# Generated by Django 5.2.17 on 2026-09-10 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0017_payableclaimreservation_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='payableclaimreservation',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='positive_payable_reservation'),
        ),
    ]
