# Generated by Django 5.2.17 on 2026-09-10 05:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0018_payableclaimreservation_positive_payable_reservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayableClaimAttribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_id', models.PositiveBigIntegerField(db_index=True)),
                ('department_label', models.CharField(max_length=160)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('version', models.PositiveIntegerField()),
                ('base_version', models.PositiveIntegerField(default=0)),
                ('party_key', models.CharField(max_length=100)),
                ('claim_reference', models.CharField(max_length=120)),
                ('applications', models.JSONField(blank=True, default=list)),
                ('source_snapshot', models.JSONField()),
                ('source_checksum', models.CharField(max_length=64)),
                ('evidence_reference', models.CharField(max_length=255)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('submitted', 'For independent review'), ('approved', 'Approved'), ('returned', 'Returned')], default='submitted', max_length=12)),
                ('proposed_by_id', models.PositiveBigIntegerField()),
                ('proposed_by_label', models.CharField(max_length=160)),
                ('proposed_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('reviewed_by_label', models.CharField(blank=True, max_length=160)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True)),
                ('approval_checksum', models.CharField(blank=True, max_length=64)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claim_attributions', to='accounting.journalline')),
            ],
            options={
                'ordering': ('-version',),
            },
        ),
        migrations.CreateModel(
            name='PayableClaimAttributionHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribution', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='current_head', to='accounting.payableclaimattribution')),
                ('source', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='claim_attribution_head', to='accounting.journalline')),
            ],
        ),
        migrations.AddConstraint(
            model_name='payableclaimattribution',
            constraint=models.UniqueConstraint(fields=('source', 'version'), name='unique_payable_attribution_version'),
        ),
    ]
