# Generated by Django 5.2.17 on 2026-09-10 06:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0019_reviewed_historical_claim_attribution'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayableClaimReservationGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('group_key', models.CharField(max_length=100, unique=True)),
                ('case_public_id', models.UUIDField(db_index=True)),
                ('allocation_snapshot', models.JSONField()),
                ('allocation_checksum', models.CharField(max_length=64)),
                ('created_by_id', models.PositiveBigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='payableclaimreservation',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='accounting.payableclaimreservationgroup'),
        ),
    ]
