# Generated by Django 5.2.17 on 2026-09-10 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0020_payableclaimreservationgroup_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayableClaimRetirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('evidence', models.JSONField()),
                ('checksum', models.CharField(max_length=64)),
                ('created_by_id', models.PositiveBigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claim_retirements', to='accounting.journalentry')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retirements', to='accounting.payableclaimreservation')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('reservation', 'entry'), name='unique_claim_return_retirement'), models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='positive_claim_retirement')],
            },
        ),
    ]
