# Generated by Django 5.2.17 on 2026-09-10 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0021_payableclaimretirement'),
    ]

    operations = [
        migrations.AddField(
            model_name='payableclaimattribution',
            name='allocation_checksum',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='payableclaimattribution',
            name='claim_reference',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='payableclaimattribution',
            name='party_key',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='PayableClaimSlice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.UUIDField()),
                ('party_key', models.CharField(max_length=100)),
                ('claim_reference', models.CharField(max_length=120)),
                ('recognized', models.DecimalField(decimal_places=2, max_digits=18)),
                ('applications', models.JSONField(blank=True, default=dict)),
                ('attribution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_slices', to='accounting.payableclaimattribution')),
            ],
            options={
                'ordering': ('key',),
                'constraints': [models.UniqueConstraint(fields=('attribution', 'key'), name='unique_claim_slice_key'), models.UniqueConstraint(fields=('attribution', 'party_key', 'claim_reference'), name='unique_claim_slice_invoice'), models.CheckConstraint(condition=models.Q(('recognized__gt', 0)), name='positive_claim_slice_credit')],
            },
        ),
    ]
