# Generated by Django 5.2.17 on 2026-09-10 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0022_historical_claim_slices'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalline',
            name='payable_allocation',
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
    ]
