# Generated by Django 5.2.17 on 2026-09-10 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0023_journal_invoice_allocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='payableclaimreservation',
            name='invoice_key',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
