# Generated by Django 5.2.17 on 2026-09-10 12:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0024_invoice_reservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedPayableClaimProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_id', models.PositiveBigIntegerField(db_index=True)),
                ('department_label', models.CharField(max_length=160)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('source_ids', models.JSONField()),
                ('application_ids', models.JSONField(blank=True, default=list)),
                ('source_set_checksum', models.CharField(max_length=64)),
                ('version', models.PositiveIntegerField()),
                ('base_approvals', models.JSONField()),
                ('allocations', models.JSONField()),
                ('source_snapshot', models.JSONField()),
                ('source_checksum', models.CharField(max_length=64)),
                ('evidence_reference', models.CharField(max_length=255)),
                ('reason', models.TextField()),
                ('proposed_by_id', models.PositiveBigIntegerField()),
                ('proposed_by_label', models.CharField(max_length=160)),
                ('proposed_at', models.DateTimeField(auto_now_add=True)),
                ('proposal_checksum', models.CharField(max_length=64)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shared_claim_proposals', to='accounting.fund')),
            ],
            options={
                'ordering': ('-version',),
                'constraints': [models.UniqueConstraint(fields=('fund', 'source_set_checksum', 'version'), name='unique_shared_claim_proposal_version')],
            },
        ),
    ]
