# Generated by Django 5.2.17 on 2026-09-10 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0025_shared_claim_proposals'),
    ]

    operations = [
        migrations.AddField(
            model_name='payableclaimattribution',
            name='application_amounts',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='payableclaimattribution',
            name='shared_proposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attributions', to='accounting.sharedpayableclaimproposal'),
        ),
        migrations.AddConstraint(
            model_name='payableclaimattribution',
            constraint=models.UniqueConstraint(fields=('shared_proposal', 'source'), name='unique_shared_attribution_source'),
        ),
    ]
