# Generated by Django 5.2.17 on 2026-09-12 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0026_shared_claim_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='source_type',
            field=models.CharField(choices=[('collection', 'Treasury collection receipt'), ('deposit', 'Deposit of Treasury collections'), ('manual', 'Manual journal'), ('voucher', 'Voucher'), ('remittance', 'Deduction / withholding remittance'), ('adjustment', 'Adjusting entry'), ('reversal', 'Reversing entry'), ('opening', 'Opening balance'), ('closing', 'Nominal-account closing transfer'), ('policy_change', 'Accounting-policy adjustment to equity'), ('prior_error', 'Prior-period correction to equity'), ('opening_restate', 'Other opening-balance restatement'), ('equity_revenue', 'Net revenue recognized directly in equity'), ('equity_other', 'Other direct equity movement')], default='manual', max_length=16),
        ),
    ]
