# Generated by Django 5.2.17 on 2026-09-12 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0028_collection_sources'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalsubsidiaryline',
            name='category',
            field=models.CharField(choices=[('advance', 'Accountable officer advances (recognized asset)'), ('payable', 'Payable by claimant / payee'), ('withholding', 'Deduction / withholding payable')], max_length=16),
        ),
    ]
