# Generated by Django 5.2.17 on 2026-09-12 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0029_advance_subsidiary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journalsubsidiaryline',
            options={'ordering': ('entry__entry_date', 'entry_id', 'journal_line__sequence'), 'permissions': (('view_officer_advances', 'Can view officer advances and liquidation history'), ('export_officer_advances', 'Can export officer advance balances'))},
        ),
    ]
